
-----------------------		URL INSERTION QUERY FOR TZBRB - SIT   --------------------------
DELETE FROM S_URL_BUSINESS_MAP_MST  WHERE SYSTEM_ID='MB' AND BUSINESS_ID='TZBRB' AND URL_PATTERN='https://s04t.wload.global:32100/bmg';

INSERT INTO S_URL_BUSINESS_MAP_MST (SYSTEM_ID, BUSINESS_ID, URL_PATTERN, LANGUAGE_ID) VALUES ('MB','TZBRB','https://s04t.wload.global:32100/bmg','EN');
COMMIT;
