/**
 * USSDInputParamsEnum.java
 */
package com.barclays.ussd.utils;

// TODO: Auto-generated Javadoc
/**
 * The Enum USSDInputParamsEnum.
 *
 * @author BTCI
 */
public enum USSDSequenceNumberEnum {
SEQUENCE_NUMBER_ENDS(-1),
SEQUENCE_NUMBER_ONE(1),
SEQUENCE_NUMBER_TWO(2),
SEQUENCE_NUMBER_THREE(3),
SEQUENCE_NUMBER_FOUR(4),
SEQUENCE_NUMBER_FIVE(5),
SEQUENCE_NUMBER_SIX(6),
SEQUENCE_NUMBER_SEVEN(7),
SEQUENCE_NUMBER_EIGHT(8),
SEQUENCE_NUMBER_NINE(9),
SEQUENCE_NUMBER_TEN(10),
SEQUENCE_NUMBER_ELEVEN(11),
SEQUENCE_NUMBER_TWELVE(12),
SEQUENCE_NUMBER_THIRTEEN(13),
SEQUENCE_NUMBER_FOURTEEN(14),
SEQUENCE_NUMBER_FIFTEEN(15),
//CR82
SEQUENCE_NUMBER_SIXTEEN(16),
SEQUENCE_NUMBER_SEVENTEEN(17),
SEQUENCE_NUMBER_EIGHTTEEN(18),
SEQUENCE_NUMBER_NINETEEN(19),
SEQUENCE_NUMBER_TWENTY(20),
SEQUENCE_NUMBER_TWENTYONE(21),
SEQUENCE_NUMBER_TWENTYTWO(22),
SEQUENCE_NUMBER_TWENTYTHREE(23),
SEQUENCE_NUMBER_TWENTYFOUR(24)
;
private int sequenceNo;

private USSDSequenceNumberEnum(final int sequenceNo) {
    this.sequenceNo = sequenceNo;
}

public int getSequenceNo() {
    return sequenceNo;
}
}
