INSERT INTO S_SYSPARAM_MST (BUSINESS_ID,SYSTEM_ID,PARAM_ID,PARAM_VALUE,PARAM_COMPONENT_KEY,ACTIVITY_ID,SYSTEM_MAINTAIN,DISP_TYPE,MODIFIED_DTM,MODIFIED_BY,AUTHORISED_BY,AUTHORISED_DTM,DELETE_FLG,PARAM_DESC,CREATED_BY,CREATED_DTM) VALUES ('TZBRB','UB','SRV_BillPay','N',null,'SHM_USSD_SERVICE_ENABLER','N',null,null,null,null,null,null,'Enable or disable service',null,null);

INSERT INTO S_SYSPARAM_MST (BUSINESS_ID,SYSTEM_ID,PARAM_ID,PARAM_VALUE,PARAM_COMPONENT_KEY,ACTIVITY_ID,SYSTEM_MAINTAIN,DISP_TYPE,MODIFIED_DTM,MODIFIED_BY,AUTHORISED_BY,AUTHORISED_DTM,DELETE_FLG,PARAM_DESC,CREATED_BY,CREATED_DTM) VALUES ('TZBRB','UB','SRV_OtherBarclaysAcctFundTxReg','N',null,'SHM_USSD_SERVICE_ENABLER','N',null,null,null,null,null,null,'Enable or disable service',null,null);

INSERT INTO S_SYSPARAM_MST (BUSINESS_ID,SYSTEM_ID,PARAM_ID,PARAM_VALUE,PARAM_COMPONENT_KEY,ACTIVITY_ID,SYSTEM_MAINTAIN,DISP_TYPE,MODIFIED_DTM,MODIFIED_BY,AUTHORISED_BY,AUTHORISED_DTM,DELETE_FLG,PARAM_DESC,CREATED_BY,CREATED_DTM) VALUES ('TZBRB','UB','SRV_ExtBankAcctFundTx','N',null,'SHM_USSD_SERVICE_ENABLER','N',null,null,null,null,null,null,'Enable or disable service',null,null);

INSERT INTO S_SYSPARAM_MST (BUSINESS_ID,SYSTEM_ID,PARAM_ID,PARAM_VALUE,PARAM_COMPONENT_KEY,ACTIVITY_ID,SYSTEM_MAINTAIN,DISP_TYPE,MODIFIED_DTM,MODIFIED_BY,AUTHORISED_BY,AUTHORISED_DTM,DELETE_FLG,PARAM_DESC,CREATED_BY,CREATED_DTM) VALUES ('TZBRB','UB','SRV_OtherBarcAcctDelBenef','N',null,'SHM_USSD_SERVICE_ENABLER','N',null,null,null,null,null,null,'Enable or disable service',null,null);

INSERT INTO S_SYSPARAM_MST (BUSINESS_ID,SYSTEM_ID,PARAM_ID,PARAM_VALUE,PARAM_COMPONENT_KEY,ACTIVITY_ID,SYSTEM_MAINTAIN,DISP_TYPE,MODIFIED_DTM,MODIFIED_BY,AUTHORISED_BY,AUTHORISED_DTM,DELETE_FLG,PARAM_DESC,CREATED_BY,CREATED_DTM) VALUES ('TZBRB','UB','SRV_NonBarcAcctDelBenef','N',null,'SHM_USSD_SERVICE_ENABLER','N',null,null,null,null,null,null,'Enable or disable service',null,null);

INSERT INTO S_SYSPARAM_MST (BUSINESS_ID,SYSTEM_ID,PARAM_ID,PARAM_VALUE,PARAM_COMPONENT_KEY,ACTIVITY_ID,SYSTEM_MAINTAIN,DISP_TYPE,MODIFIED_DTM,MODIFIED_BY,AUTHORISED_BY,AUTHORISED_DTM,DELETE_FLG,PARAM_DESC,CREATED_BY,CREATED_DTM) VALUES ('TZBRB','UB','SRV_RegisterBarclaysBenf','N',null,'SHM_USSD_SERVICE_ENABLER','N',null,null,null,null,null,null,'Enable or disable service',null,null);

INSERT INTO S_SYSPARAM_MST (BUSINESS_ID,SYSTEM_ID,PARAM_ID,PARAM_VALUE,PARAM_COMPONENT_KEY,ACTIVITY_ID,SYSTEM_MAINTAIN,DISP_TYPE,MODIFIED_DTM,MODIFIED_BY,AUTHORISED_BY,AUTHORISED_DTM,DELETE_FLG,PARAM_DESC,CREATED_BY,CREATED_DTM) VALUES ('TZBRB','UB','SRV_RegisterOtherBankBenf','N',null,'SHM_USSD_SERVICE_ENABLER','N',null,null,null,null,null,null,'Enable or disable service',null,null);

INSERT INTO S_SYSPARAM_MST (BUSINESS_ID,SYSTEM_ID,PARAM_ID,PARAM_VALUE,PARAM_COMPONENT_KEY,ACTIVITY_ID,SYSTEM_MAINTAIN,DISP_TYPE,MODIFIED_DTM,MODIFIED_BY,AUTHORISED_BY,AUTHORISED_DTM,DELETE_FLG,PARAM_DESC,CREATED_BY,CREATED_DTM) VALUES ('TZBRB','UB','SRV_RegisterBillers','N',null,'SHM_USSD_SERVICE_ENABLER','N',null,null,null,null,null,null,'Enable or disable service',null,null);

INSERT INTO S_SYSPARAM_MST (BUSINESS_ID,SYSTEM_ID,PARAM_ID,PARAM_VALUE,PARAM_COMPONENT_KEY,ACTIVITY_ID,SYSTEM_MAINTAIN,DISP_TYPE,MODIFIED_DTM,MODIFIED_BY,AUTHORISED_BY,AUTHORISED_DTM,DELETE_FLG,PARAM_DESC,CREATED_BY,CREATED_DTM) VALUES ('TZBRB','UB','SRV_DeleteBillers','N',null,'SHM_USSD_SERVICE_ENABLER','N',null,null,null,null,null,null,'Enable or disable service',null,null);

INSERT INTO S_SYSPARAM_MST (BUSINESS_ID,SYSTEM_ID,PARAM_ID,PARAM_VALUE,PARAM_COMPONENT_KEY,ACTIVITY_ID,SYSTEM_MAINTAIN,DISP_TYPE,MODIFIED_DTM,MODIFIED_BY,AUTHORISED_BY,AUTHORISED_DTM,DELETE_FLG,PARAM_DESC,CREATED_BY,CREATED_DTM) VALUES ('TZBRB','UB','SRV_OtherBarclaysAcctFundTxUnReg','N',null,'SHM_USSD_SERVICE_ENABLER','N',null,null,null,null,null,null,'Enable or disable service',null,null);

INSERT INTO S_SYSPARAM_MST (BUSINESS_ID,SYSTEM_ID,PARAM_ID,PARAM_VALUE,PARAM_COMPONENT_KEY,ACTIVITY_ID,SYSTEM_MAINTAIN,DISP_TYPE,MODIFIED_DTM,MODIFIED_BY,AUTHORISED_BY,AUTHORISED_DTM,DELETE_FLG,PARAM_DESC,CREATED_BY,CREATED_DTM) VALUES ('TZBRB','UB','SRV_OneTimePayments','N',null,'SHM_USSD_SERVICE_ENABLER','N',null,null,null,null,null,null,'Enable or disable service',null,null);

INSERT INTO S_SYSPARAM_MST (BUSINESS_ID,SYSTEM_ID,PARAM_ID,PARAM_VALUE,PARAM_COMPONENT_KEY,ACTIVITY_ID,SYSTEM_MAINTAIN,DISP_TYPE,MODIFIED_DTM,MODIFIED_BY,AUTHORISED_BY,AUTHORISED_DTM,DELETE_FLG,PARAM_DESC,CREATED_BY,CREATED_DTM) VALUES ('TZBRB','UB','SRV_ApplyFd','N',null,'SHM_USSD_SERVICE_ENABLER','N',null,null,null,null,null,null,'Enable or disable service',null,null);

INSERT INTO S_SYSPARAM_MST (BUSINESS_ID,SYSTEM_ID,PARAM_ID,PARAM_VALUE,PARAM_COMPONENT_KEY,ACTIVITY_ID,SYSTEM_MAINTAIN,DISP_TYPE,MODIFIED_DTM,MODIFIED_BY,AUTHORISED_BY,AUTHORISED_DTM,DELETE_FLG,PARAM_DESC,CREATED_BY,CREATED_DTM) VALUES ('TZBRB','UB','SRV_MobileWalletTopUp','N',null,'SHM_USSD_SERVICE_ENABLER','N',null,null,null,null,null,null,'Enable or disable service',null,null);

INSERT INTO S_SYSPARAM_MST (BUSINESS_ID,SYSTEM_ID,PARAM_ID,PARAM_VALUE,PARAM_COMPONENT_KEY,ACTIVITY_ID,SYSTEM_MAINTAIN,DISP_TYPE,MODIFIED_DTM,MODIFIED_BY,AUTHORISED_BY,AUTHORISED_DTM,DELETE_FLG,PARAM_DESC,CREATED_BY,CREATED_DTM) VALUES ('TZBRB','UB','SRV_CashSendOneTimePayment','N',null,'SHM_USSD_SERVICE_ENABLER','N',null,null,null,null,null,null,'Enable or disable service',null,null);

INSERT INTO S_SYSPARAM_MST (BUSINESS_ID,SYSTEM_ID,PARAM_ID,PARAM_VALUE,PARAM_COMPONENT_KEY,ACTIVITY_ID,SYSTEM_MAINTAIN,DISP_TYPE,MODIFIED_DTM,MODIFIED_BY,AUTHORISED_BY,AUTHORISED_DTM,DELETE_FLG,PARAM_DESC,CREATED_BY,CREATED_DTM) VALUES ('TZBRB','UB','SRV_EditBenefInternal','N',null,'SHM_USSD_SERVICE_ENABLER','N',null,null,null,null,null,null,'Enable or disable service',null,null);

INSERT INTO S_SYSPARAM_MST (BUSINESS_ID,SYSTEM_ID,PARAM_ID,PARAM_VALUE,PARAM_COMPONENT_KEY,ACTIVITY_ID,SYSTEM_MAINTAIN,DISP_TYPE,MODIFIED_DTM,MODIFIED_BY,AUTHORISED_BY,AUTHORISED_DTM,DELETE_FLG,PARAM_DESC,CREATED_BY,CREATED_DTM) VALUES ('TZBRB','UB','SRV_EditBenefExternal','N',null,'SHM_USSD_SERVICE_ENABLER','N',null,null,null,null,null,null,'Enable or disable service',null,null);

--End point interface for Debit Card List Service CR35 TZBRB

INSERT INTO S_SYSPARAM_MST (BUSINESS_ID,SYSTEM_ID,PARAM_ID,PARAM_VALUE,PARAM_COMPONENT_KEY,ACTIVITY_ID,SYSTEM_MAINTAIN,DISP_TYPE,MODIFIED_DTM,MODIFIED_BY,AUTHORISED_BY,AUTHORISED_DTM,DELETE_FLG,PARAM_DESC,CREATED_BY,CREATED_DTM)
VALUES('TZBRB','UB','FinancialTransactionCardManagment_EndPoint','https://gbrdsr000000192.intranet.barcapint.com:8840/tcvm','Indi_Cust_Mgmt_EP','COMMON','Y','INPUT_TEXT',null,null,null,null,null,'MW service end point',null,null);

INSERT INTO S_SYSPARAM_MST (BUSINESS_ID,SYSTEM_ID,PARAM_ID,PARAM_VALUE,PARAM_COMPONENT_KEY,ACTIVITY_ID,SYSTEM_MAINTAIN,DISP_TYPE,MODIFIED_DTM,MODIFIED_BY,AUTHORISED_BY,AUTHORISED_DTM,DELETE_FLG,PARAM_DESC,CREATED_BY,CREATED_DTM)
VALUES('TZBRB','UB','DR_FinancialTransactionCardManagment_EndPoint','https://gbrdsr000000192.intranet.barcapint.com:8840/tcvm','Indi_Cust_Mgmt_EP','COMMON','Y','INPUT_TEXT',null,null,null,null,null,'MW service end point',null,null);
