-- INSERTING into C_BUSINESS_MST

DELETE FROM C_BUSINESS_MST WHERE BUSINESS_ID='BWBRB';

INSERT INTO C_BUSINESS_MST (BUSINESS_ID,NAME,ISO_COUNTRY_CD,DEFAULT_LANG_KEY,LCY_CD,DATE_FMT_KEY,AMOUNT_FMT_KEY,REGIONAL_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,TIMEZONE_OFFSET,CARDONLY_FLG,RATE_PRECISION,CREATED_DTM,CREATED_BY,CASE_RETENTION_MONTH,CAMPAIGN_RETENTION_MONTH,WAVE_RETENTION_PERIOD,PAST_OPPTY_RETENTION_PERIOD) VALUES ('BWBRB','Barclays Bank - Botswana','BW','EN','BWP','DMY','7.3G','N','E20015149',to_timestamp('16-JUN-11 10.47.32.398000000','DD-MON-RR HH24.MI.SS.FF'),'E20016813',to_timestamp('16-JUN-11 11.56.27.129000000','DD-MON-RR HH24.MI.SS.FF'),'N',2,'N','#,###,##0.0000',null,null,'1','2','3','4');

commit;