INSERT INTO C_INTEREST_RATE_MST
(BUSINESS_ID,PRODUCT_CD,EFFECTIVE_DTM,CCY,CHANNEL,CUSTOMER_SEGMENT,TENURE_MONTH,TENURE_DAY,AMT_SLAB_FROM,AMT_SLAB_TO,INTEREST_RATE,INTEREST_VARIANCE,
PENALTY_RATE,PENALTY_VARIANCE,TENURE_TYPE) VALUES ('BWBRB','250',SYSDATE,'BWP','A','MASS',1,0,1000,9999,0.50,null,null,null,null);

INSERT INTO C_INTEREST_RATE_MST
(BUSINESS_ID,PRODUCT_CD,EFFECTIVE_DTM,CCY,CHANNEL,CUSTOMER_SEGMENT,TENURE_MONTH,TENURE_DAY,AMT_SLAB_FROM,AMT_SLAB_TO,INTEREST_RATE,INTEREST_VARIANCE,
PENALTY_RATE,PENALTY_VARIANCE,TENURE_TYPE) VALUES ('BWBRB','250',SYSDATE,'BWP','A','MASS',1,0,10000,99999,1.00,null,null,null,null);

INSERT INTO C_INTEREST_RATE_MST
(BUSINESS_ID,PRODUCT_CD,EFFECTIVE_DTM,CCY,CHANNEL,CUSTOMER_SEGMENT,TENURE_MONTH,TENURE_DAY,AMT_SLAB_FROM,AMT_SLAB_TO,INTEREST_RATE,INTEREST_VARIANCE,
PENALTY_RATE,PENALTY_VARIANCE,TENURE_TYPE) VALUES ('BWBRB','250',SYSDATE,'BWP','A','MASS',1,0,100000,499999,1.00,null,null,null,null);

INSERT INTO C_INTEREST_RATE_MST
(BUSINESS_ID,PRODUCT_CD,EFFECTIVE_DTM,CCY,CHANNEL,CUSTOMER_SEGMENT,TENURE_MONTH,TENURE_DAY,AMT_SLAB_FROM,AMT_SLAB_TO,INTEREST_RATE,INTEREST_VARIANCE,
PENALTY_RATE,PENALTY_VARIANCE,TENURE_TYPE) VALUES ('BWBRB','250',SYSDATE,'BWP','A','MASS',1,0,500000,999999,1.00,null,null,null,null);

INSERT INTO C_INTEREST_RATE_MST
(BUSINESS_ID,PRODUCT_CD,EFFECTIVE_DTM,CCY,CHANNEL,CUSTOMER_SEGMENT,TENURE_MONTH,TENURE_DAY,AMT_SLAB_FROM,AMT_SLAB_TO,INTEREST_RATE,INTEREST_VARIANCE,
PENALTY_RATE,PENALTY_VARIANCE,TENURE_TYPE) VALUES ('BWBRB','250',SYSDATE,'BWP','A','MASS',3,0,1000,9999,4.00,null,null,null,null);

INSERT INTO C_INTEREST_RATE_MST
(BUSINESS_ID,PRODUCT_CD,EFFECTIVE_DTM,CCY,CHANNEL,CUSTOMER_SEGMENT,TENURE_MONTH,TENURE_DAY,AMT_SLAB_FROM,AMT_SLAB_TO,INTEREST_RATE,INTEREST_VARIANCE,
PENALTY_RATE,PENALTY_VARIANCE,TENURE_TYPE) VALUES ('BWBRB','250',SYSDATE,'BWP','A','MASS',3,0,10000,99999,4.00,null,null,null,null);

INSERT INTO C_INTEREST_RATE_MST
(BUSINESS_ID,PRODUCT_CD,EFFECTIVE_DTM,CCY,CHANNEL,CUSTOMER_SEGMENT,TENURE_MONTH,TENURE_DAY,AMT_SLAB_FROM,AMT_SLAB_TO,INTEREST_RATE,INTEREST_VARIANCE,
PENALTY_RATE,PENALTY_VARIANCE,TENURE_TYPE) VALUES ('BWBRB','250',SYSDATE,'BWP','A','MASS',3,0,100000,499999,4.00,null,null,null,null);

INSERT INTO C_INTEREST_RATE_MST
(BUSINESS_ID,PRODUCT_CD,EFFECTIVE_DTM,CCY,CHANNEL,CUSTOMER_SEGMENT,TENURE_MONTH,TENURE_DAY,AMT_SLAB_FROM,AMT_SLAB_TO,INTEREST_RATE,INTEREST_VARIANCE,
PENALTY_RATE,PENALTY_VARIANCE,TENURE_TYPE) VALUES ('BWBRB','250',SYSDATE,'BWP','A','MASS',3,0,500000,999999,4.00,null,null,null,null);

INSERT INTO C_INTEREST_RATE_MST
(BUSINESS_ID,PRODUCT_CD,EFFECTIVE_DTM,CCY,CHANNEL,CUSTOMER_SEGMENT,TENURE_MONTH,TENURE_DAY,AMT_SLAB_FROM,AMT_SLAB_TO,INTEREST_RATE,INTEREST_VARIANCE,
PENALTY_RATE,PENALTY_VARIANCE,TENURE_TYPE) VALUES ('BWBRB','250',SYSDATE,'BWP','A','MASS',6,0,1000,9999,4.03,null,null,null,null);

INSERT INTO C_INTEREST_RATE_MST
(BUSINESS_ID,PRODUCT_CD,EFFECTIVE_DTM,CCY,CHANNEL,CUSTOMER_SEGMENT,TENURE_MONTH,TENURE_DAY,AMT_SLAB_FROM,AMT_SLAB_TO,INTEREST_RATE,INTEREST_VARIANCE,
PENALTY_RATE,PENALTY_VARIANCE,TENURE_TYPE) VALUES ('BWBRB','250',SYSDATE,'BWP','A','MASS',6,0,10000,99999,4.10,null,null,null,null);

INSERT INTO C_INTEREST_RATE_MST
(BUSINESS_ID,PRODUCT_CD,EFFECTIVE_DTM,CCY,CHANNEL,CUSTOMER_SEGMENT,TENURE_MONTH,TENURE_DAY,AMT_SLAB_FROM,AMT_SLAB_TO,INTEREST_RATE,INTEREST_VARIANCE,
PENALTY_RATE,PENALTY_VARIANCE,TENURE_TYPE) VALUES ('BWBRB','250',SYSDATE,'BWP','A','MASS',6,0,100000,499999,4.15,null,null,null,null);

INSERT INTO C_INTEREST_RATE_MST
(BUSINESS_ID,PRODUCT_CD,EFFECTIVE_DTM,CCY,CHANNEL,CUSTOMER_SEGMENT,TENURE_MONTH,TENURE_DAY,AMT_SLAB_FROM,AMT_SLAB_TO,INTEREST_RATE,INTEREST_VARIANCE,
PENALTY_RATE,PENALTY_VARIANCE,TENURE_TYPE) VALUES ('BWBRB','250',SYSDATE,'BWP','A','MASS',6,0,500000,999999,4.20,null,null,null,null);

INSERT INTO C_INTEREST_RATE_MST
(BUSINESS_ID,PRODUCT_CD,EFFECTIVE_DTM,CCY,CHANNEL,CUSTOMER_SEGMENT,TENURE_MONTH,TENURE_DAY,AMT_SLAB_FROM,AMT_SLAB_TO,INTEREST_RATE,INTEREST_VARIANCE,
PENALTY_RATE,PENALTY_VARIANCE,TENURE_TYPE) VALUES ('BWBRB','250',SYSDATE,'BWP','A','MASS',12,0,1000,9999,4.25,null,null,null,null);

INSERT INTO C_INTEREST_RATE_MST
(BUSINESS_ID,PRODUCT_CD,EFFECTIVE_DTM,CCY,CHANNEL,CUSTOMER_SEGMENT,TENURE_MONTH,TENURE_DAY,AMT_SLAB_FROM,AMT_SLAB_TO,INTEREST_RATE,INTEREST_VARIANCE,
PENALTY_RATE,PENALTY_VARIANCE,TENURE_TYPE) VALUES ('BWBRB','250',SYSDATE,'BWP','A','MASS',12,0,10000,99999,4.65,null,null,null,null);

INSERT INTO C_INTEREST_RATE_MST
(BUSINESS_ID,PRODUCT_CD,EFFECTIVE_DTM,CCY,CHANNEL,CUSTOMER_SEGMENT,TENURE_MONTH,TENURE_DAY,AMT_SLAB_FROM,AMT_SLAB_TO,INTEREST_RATE,INTEREST_VARIANCE,
PENALTY_RATE,PENALTY_VARIANCE,TENURE_TYPE) VALUES ('BWBRB','250',SYSDATE,'BWP','A','MASS',12,0,100000,499999,4.70,null,null,null,null);

INSERT INTO C_INTEREST_RATE_MST
(BUSINESS_ID,PRODUCT_CD,EFFECTIVE_DTM,CCY,CHANNEL,CUSTOMER_SEGMENT,TENURE_MONTH,TENURE_DAY,AMT_SLAB_FROM,AMT_SLAB_TO,INTEREST_RATE,INTEREST_VARIANCE,
PENALTY_RATE,PENALTY_VARIANCE,TENURE_TYPE) VALUES ('BWBRB','250',SYSDATE,'BWP','A','MASS',12,0,500000,999999,4.75,null,null,null,null);

INSERT INTO C_INTEREST_RATE_MST
(BUSINESS_ID,PRODUCT_CD,EFFECTIVE_DTM,CCY,CHANNEL,CUSTOMER_SEGMENT,TENURE_MONTH,TENURE_DAY,AMT_SLAB_FROM,AMT_SLAB_TO,INTEREST_RATE,INTEREST_VARIANCE,
PENALTY_RATE,PENALTY_VARIANCE,TENURE_TYPE) VALUES ('BWBRB','250',SYSDATE,'BWP','A','MASS',24,0,1000,9999,4.60,null,null,null,null);

INSERT INTO C_INTEREST_RATE_MST
(BUSINESS_ID,PRODUCT_CD,EFFECTIVE_DTM,CCY,CHANNEL,CUSTOMER_SEGMENT,TENURE_MONTH,TENURE_DAY,AMT_SLAB_FROM,AMT_SLAB_TO,INTEREST_RATE,INTEREST_VARIANCE,
PENALTY_RATE,PENALTY_VARIANCE,TENURE_TYPE) VALUES ('BWBRB','250',SYSDATE,'BWP','A','MASS',24,0,10000,99999,4.80,null,null,null,null);

INSERT INTO C_INTEREST_RATE_MST
(BUSINESS_ID,PRODUCT_CD,EFFECTIVE_DTM,CCY,CHANNEL,CUSTOMER_SEGMENT,TENURE_MONTH,TENURE_DAY,AMT_SLAB_FROM,AMT_SLAB_TO,INTEREST_RATE,INTEREST_VARIANCE,
PENALTY_RATE,PENALTY_VARIANCE,TENURE_TYPE) VALUES ('BWBRB','250',SYSDATE,'BWP','A','MASS',24,0,100000,499999,4.85,null,null,null,null);

INSERT INTO C_INTEREST_RATE_MST
(BUSINESS_ID,PRODUCT_CD,EFFECTIVE_DTM,CCY,CHANNEL,CUSTOMER_SEGMENT,TENURE_MONTH,TENURE_DAY,AMT_SLAB_FROM,AMT_SLAB_TO,INTEREST_RATE,INTEREST_VARIANCE,
PENALTY_RATE,PENALTY_VARIANCE,TENURE_TYPE) VALUES ('BWBRB','250',SYSDATE,'BWP','A','MASS',24,0,500000,999999,5.30,null,null,null,null);

INSERT INTO C_INTEREST_RATE_MST
(BUSINESS_ID,PRODUCT_CD,EFFECTIVE_DTM,CCY,CHANNEL,CUSTOMER_SEGMENT,TENURE_MONTH,TENURE_DAY,AMT_SLAB_FROM,AMT_SLAB_TO,INTEREST_RATE,INTEREST_VARIANCE,
PENALTY_RATE,PENALTY_VARIANCE,TENURE_TYPE) VALUES ('BWBRB','250',SYSDATE,'BWP','A','MASS',36,0,1000,9999,4.70,null,null,null,null);

INSERT INTO C_INTEREST_RATE_MST
(BUSINESS_ID,PRODUCT_CD,EFFECTIVE_DTM,CCY,CHANNEL,CUSTOMER_SEGMENT,TENURE_MONTH,TENURE_DAY,AMT_SLAB_FROM,AMT_SLAB_TO,INTEREST_RATE,INTEREST_VARIANCE,
PENALTY_RATE,PENALTY_VARIANCE,TENURE_TYPE) VALUES ('BWBRB','250',SYSDATE,'BWP','A','MASS',36,0,10000,99999,5.00,null,null,null,null);

INSERT INTO C_INTEREST_RATE_MST
(BUSINESS_ID,PRODUCT_CD,EFFECTIVE_DTM,CCY,CHANNEL,CUSTOMER_SEGMENT,TENURE_MONTH,TENURE_DAY,AMT_SLAB_FROM,AMT_SLAB_TO,INTEREST_RATE,INTEREST_VARIANCE,
PENALTY_RATE,PENALTY_VARIANCE,TENURE_TYPE) VALUES ('BWBRB','250',SYSDATE,'BWP','A','MASS',36,0,100000,499999,5.30,null,null,null,null);

INSERT INTO C_INTEREST_RATE_MST
(BUSINESS_ID,PRODUCT_CD,EFFECTIVE_DTM,CCY,CHANNEL,CUSTOMER_SEGMENT,TENURE_MONTH,TENURE_DAY,AMT_SLAB_FROM,AMT_SLAB_TO,INTEREST_RATE,INTEREST_VARIANCE,
PENALTY_RATE,PENALTY_VARIANCE,TENURE_TYPE) VALUES ('BWBRB','250',SYSDATE,'BWP','A','MASS',36,0,500000,999999,5.50,null,null,null,null);