
-----------------------		URL INSERTION QUERY FOR SCBRB - PRODUCTION   --------------------------
DELETE FROM S_URL_BUSINESS_MAP_MST WHERE SYSTEM_ID='MB' AND BUSINESS_ID='SCBRB' AND URL_PATTERN='https://www.sc.secure.barclays.com/bmg';

INSERT INTO S_URL_BUSINESS_MAP_MST (SYSTEM_ID, BUSINESS_ID, URL_PATTERN, LANGUAGE_ID) VALUES ('MB','SCBRB','https://www.sc.secure.barclays.com/bmg','EN');

DELETE FROM S_URL_BUSINESS_MAP_MST WHERE SYSTEM_ID='MB' AND BUSINESS_ID='SCBRB' AND URL_PATTERN='https://scc2bir-dr.barclays.intranet/bmg';

DELETE FROM S_URL_BUSINESS_MAP_MST WHERE SYSTEM_ID='MB' AND BUSINESS_ID='SCBRB' AND URL_PATTERN='https://scc2bir-live.barclays.intranet/bmg';

INSERT INTO S_URL_BUSINESS_MAP_MST (SYSTEM_ID, BUSINESS_ID, URL_PATTERN, LANGUAGE_ID) VALUES ('MB','SCBRB','https://scc2bir-live.barclays.intranet/bmg','EN');

COMMIT;
