------------- BEM ENDPOINTS - NFT  ------------------------


UPDATE S_SYSPARAM_MST SET PARAM_VALUE = 'https://22.126.78.139:443/tcvm'
WHERE PARAM_ID = 'FinancialTransactionProcessing_EndPoint'
AND SYSTEM_ID = 'UB'
AND BUSINESS_ID = 'TZBRB';

UPDATE S_SYSPARAM_MST SET PARAM_VALUE = 'https://22.126.78.139:443/tcvm'
WHERE PARAM_ID = 'IndividualCustomerManagement_EndPoint'
AND SYSTEM_ID = 'UB'
AND BUSINESS_ID = 'TZBRB';

UPDATE S_SYSPARAM_MST SET PARAM_VALUE = 'https://22.126.78.139:443/tcvm'
WHERE PARAM_ID = 'ProblemManagement_EndPoint'
AND SYSTEM_ID = 'UB'
AND BUSINESS_ID = 'TZBRB';

UPDATE S_SYSPARAM_MST SET PARAM_VALUE = 'https://22.126.78.139:443/tcvm'
WHERE PARAM_ID = 'PinManagement_EndPoint'
AND SYSTEM_ID = 'UB'
AND BUSINESS_ID = 'TZBRB';

UPDATE S_SYSPARAM_MST SET PARAM_VALUE = 'https://22.126.78.139:443/tcvm'
WHERE PARAM_ID = 'HelloMoneyCustomerManagement_EndPoint'
AND SYSTEM_ID = 'UB'
AND BUSINESS_ID = 'TZBRB';

UPDATE S_SYSPARAM_MST SET PARAM_VALUE = 'https://22.126.78.139:443/tcvm'
WHERE PARAM_ID = 'AccountManagement_EndPoint'
AND SYSTEM_ID = 'UB'
AND BUSINESS_ID = 'TZBRB';

UPDATE S_SYSPARAM_MST SET PARAM_VALUE = 'https://22.126.78.139:443/tcvm'
WHERE PARAM_ID = 'AccountMandateManagement_EndPoint'
AND SYSTEM_ID = 'UB'
AND BUSINESS_ID = 'TZBRB';

UPDATE S_SYSPARAM_MST SET PARAM_VALUE = 'https://22.126.78.139:443/tcvm'
WHERE PARAM_ID = 'AccountReporting_EndPoint'
AND SYSTEM_ID = 'UB'
AND BUSINESS_ID = 'TZBRB';

UPDATE S_SYSPARAM_MST SET PARAM_VALUE = 'https://22.126.78.139:443/tcvm'
WHERE PARAM_ID = 'BeneficiaryManagement_EndPoint'
AND SYSTEM_ID = 'UB'
AND BUSINESS_ID = 'TZBRB';

UPDATE S_SYSPARAM_MST SET PARAM_VALUE = 'https://22.126.78.139:443/tcvm'
WHERE PARAM_ID = 'CheckBookManagement_EndPoint'
AND SYSTEM_ID = 'UB'
AND BUSINESS_ID = 'TZBRB';

UPDATE S_SYSPARAM_MST SET PARAM_VALUE = 'https://22.126.78.139:443/tcvm'
WHERE PARAM_ID = 'NotificationService_EndPoint'
AND SYSTEM_ID = 'UB'
AND BUSINESS_ID = 'TZBRB';

COMMIT;