DELETE FROM C_MESSAGE_MST where business_id = 'TZBRB' and system_id = 'UB' and message_key = 'REG01171';
INSERT INTO C_MESSAGE_MST (SYSTEM_ID,BUSINESS_ID,CATEGORY,MESSAGE_KEY,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,SOURCE_SYSTEM_ID) values ('UB','TZBRB','ERROR','REG01171',null,null,null,null,null,null);

commit;