--delete records
DELETE FROM C_LISTVALUE_RES_MST WHERE SYSTEM_ID='UB' AND BUSINESS_ID='UGBRB' AND GROUP_ID='SYS_PARAM_CS' AND LIST_VALUE_KEY='CS_MAX_AMT';
DELETE FROM C_LISTVALUE_RES_MST WHERE SYSTEM_ID='UB' AND BUSINESS_ID='UGBRB' AND GROUP_ID='SYS_PARAM_CS' AND LIST_VALUE_KEY='CS_MIN_AMT';
DELETE FROM C_LISTVALUE_RES_MST WHERE SYSTEM_ID='UB' AND BUSINESS_ID='UGBRB' AND GROUP_ID='SYS_PARAM_CS' AND LIST_VALUE_KEY='CS_MAX_DAYAMT';
DELETE FROM C_LISTVALUE_RES_MST WHERE SYSTEM_ID='UB' AND BUSINESS_ID='UGBRB' AND GROUP_ID='SYS_PARAM_CS' AND LIST_VALUE_KEY='CS_MAX_TXS';
DELETE FROM C_LISTVALUE_RES_MST WHERE SYSTEM_ID='UB' AND BUSINESS_ID='UGBRB' AND GROUP_ID='SYS_PARAM_CS' AND LIST_VALUE_KEY='CS_MULTIPLE_AMT';

-- Insert script for Cash Send table C_LISTVALUE_RES_MST

INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) VALUES ('UB','UGBRB','SYS_PARAM_CS','CS_MIN_AMT','EN','10000',2);
INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) VALUES ('UB','UGBRB','SYS_PARAM_CS','CS_MAX_AMT','EN','2000000',1);
INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) VALUES ('UB','UGBRB','SYS_PARAM_CS','CS_MAX_DAYAMT','EN','2000000',3);
INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) VALUES ('UB','UGBRB','SYS_PARAM_CS','CS_MAX_TXS','EN','5',4);
INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) VALUES ('UB','UGBRB','SYS_PARAM_CS','CS_MULTIPLE_AMT','EN','10000',5);


COMMIT;