-- INSERTING into C_BUSINESS_MST

DELETE FROM C_BUSINESS_MST WHERE BUSINESS_ID='GHBRB';

INSERT INTO C_BUSINESS_MST (BUSINESS_ID,NAME,ISO_COUNTRY_CD,DEFAULT_LANG_KEY,LCY_CD,DATE_FMT_KEY,AMOUNT_FMT_KEY,REGIONAL_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,TIMEZONE_OFFSET,CARDONLY_FLG,RATE_PRECISION,CREATED_DTM,CREATED_BY,CASE_RETENTION_MONTH,CAMPAIGN_RETENTION_MONTH,WAVE_RETENTION_PERIOD,PAST_OPPTY_RETENTION_PERIOD) VALUES ('GHBRB','Barclays Bank - Ghana','GH','EN','GHS','DMY','7.3G','N','E20015149',SYSDATE,'E20016813',SYSDATE,'N',0,'N','#,###,##0.0000',null,null,'1','2','3','4');


commit;