--Personal FD (ZMW) Rates > 35k < 500k
INSERT INTO "C_INTEREST_RATE_MST" (BUSINESS_ID,PRODUCT_CD,EFFECTIVE_DTM,CCY,CHANNEL,CUSTOMER_SEGMENT,TENURE_MONTH,TENURE_DAY,AMT_SLAB_FROM,AMT_SLAB_TO,
INTEREST_RATE,INTEREST_VARIANCE,PENALTY_RATE,PENALTY_VARIANCE,TENURE_TYPE) VALUES 
('ZMBRB','10',sysdate,'ZMW','A','MASS',1,0,35000,99999,4.5,null,null,null,'CR');
INSERT INTO "C_INTEREST_RATE_MST" (BUSINESS_ID,PRODUCT_CD,EFFECTIVE_DTM,CCY,CHANNEL,CUSTOMER_SEGMENT,TENURE_MONTH,TENURE_DAY,AMT_SLAB_FROM,AMT_SLAB_TO,
INTEREST_RATE,INTEREST_VARIANCE,PENALTY_RATE,PENALTY_VARIANCE,TENURE_TYPE) VALUES 
('ZMBRB','10',sysdate,'ZMW','A','MASS',1,0,100000,499999,5.5,null,null,null,'CR');

INSERT INTO "C_INTEREST_RATE_MST" (BUSINESS_ID,PRODUCT_CD,EFFECTIVE_DTM,CCY,CHANNEL,CUSTOMER_SEGMENT,TENURE_MONTH,TENURE_DAY,AMT_SLAB_FROM,AMT_SLAB_TO,
INTEREST_RATE,INTEREST_VARIANCE,PENALTY_RATE,PENALTY_VARIANCE,TENURE_TYPE) VALUES 
('ZMBRB','10',sysdate,'ZMW','A','MASS',3,0,35000,99999,5.5,null,null,null,'CR');
INSERT INTO "C_INTEREST_RATE_MST" (BUSINESS_ID,PRODUCT_CD,EFFECTIVE_DTM,CCY,CHANNEL,CUSTOMER_SEGMENT,TENURE_MONTH,TENURE_DAY,AMT_SLAB_FROM,AMT_SLAB_TO,
INTEREST_RATE,INTEREST_VARIANCE,PENALTY_RATE,PENALTY_VARIANCE,TENURE_TYPE) VALUES 
('ZMBRB','10',sysdate,'ZMW','A','MASS',3,0,100000,499999,6.5,null,null,null,'CR');

INSERT INTO "C_INTEREST_RATE_MST" (BUSINESS_ID,PRODUCT_CD,EFFECTIVE_DTM,CCY,CHANNEL,CUSTOMER_SEGMENT,TENURE_MONTH,TENURE_DAY,AMT_SLAB_FROM,AMT_SLAB_TO,
INTEREST_RATE,INTEREST_VARIANCE,PENALTY_RATE,PENALTY_VARIANCE,TENURE_TYPE) VALUES 
('ZMBRB','10',sysdate,'ZMW','A','MASS',6,0,35000,99999,8,null,null,null,'CR');
INSERT INTO "C_INTEREST_RATE_MST" (BUSINESS_ID,PRODUCT_CD,EFFECTIVE_DTM,CCY,CHANNEL,CUSTOMER_SEGMENT,TENURE_MONTH,TENURE_DAY,AMT_SLAB_FROM,AMT_SLAB_TO,
INTEREST_RATE,INTEREST_VARIANCE,PENALTY_RATE,PENALTY_VARIANCE,TENURE_TYPE) VALUES 
('ZMBRB','10',sysdate,'ZMW','A','MASS',6,0,100000,499999,9,null,null,null,'CR');

INSERT INTO "C_INTEREST_RATE_MST" (BUSINESS_ID,PRODUCT_CD,EFFECTIVE_DTM,CCY,CHANNEL,CUSTOMER_SEGMENT,TENURE_MONTH,TENURE_DAY,AMT_SLAB_FROM,AMT_SLAB_TO,
INTEREST_RATE,INTEREST_VARIANCE,PENALTY_RATE,PENALTY_VARIANCE,TENURE_TYPE) VALUES 
('ZMBRB','10',sysdate,'ZMW','A','MASS',12,0,35000,99999,9.5,null,null,null,'CR');
INSERT INTO "C_INTEREST_RATE_MST" (BUSINESS_ID,PRODUCT_CD,EFFECTIVE_DTM,CCY,CHANNEL,CUSTOMER_SEGMENT,TENURE_MONTH,TENURE_DAY,AMT_SLAB_FROM,AMT_SLAB_TO,
INTEREST_RATE,INTEREST_VARIANCE,PENALTY_RATE,PENALTY_VARIANCE,TENURE_TYPE) VALUES 
('ZMBRB','10',sysdate,'ZMW','A','MASS',12,0,100000,499999,10,null,null,null,'CR');


--Prestige FD (ZMW) Rates > 35k < 500k
INSERT INTO "C_INTEREST_RATE_MST" (BUSINESS_ID,PRODUCT_CD,EFFECTIVE_DTM,CCY,CHANNEL,CUSTOMER_SEGMENT,TENURE_MONTH,TENURE_DAY,AMT_SLAB_FROM,AMT_SLAB_TO,
INTEREST_RATE,INTEREST_VARIANCE,PENALTY_RATE,PENALTY_VARIANCE,TENURE_TYPE) VALUES 
('ZMBRB','23',sysdate,'ZMW','A','MASS',1,0,35000,99999,5,null,null,null,'CR');
INSERT INTO "C_INTEREST_RATE_MST" (BUSINESS_ID,PRODUCT_CD,EFFECTIVE_DTM,CCY,CHANNEL,CUSTOMER_SEGMENT,TENURE_MONTH,TENURE_DAY,AMT_SLAB_FROM,AMT_SLAB_TO,
INTEREST_RATE,INTEREST_VARIANCE,PENALTY_RATE,PENALTY_VARIANCE,TENURE_TYPE) VALUES 
('ZMBRB','23',sysdate,'ZMW','A','MASS',1,0,100000,499999,6,null,null,null,'CR');

INSERT INTO "C_INTEREST_RATE_MST" (BUSINESS_ID,PRODUCT_CD,EFFECTIVE_DTM,CCY,CHANNEL,CUSTOMER_SEGMENT,TENURE_MONTH,TENURE_DAY,AMT_SLAB_FROM,AMT_SLAB_TO,
INTEREST_RATE,INTEREST_VARIANCE,PENALTY_RATE,PENALTY_VARIANCE,TENURE_TYPE) VALUES 
('ZMBRB','23',sysdate,'ZMW','A','MASS',3,0,35000,99999,6.5,null,null,null,'CR');
INSERT INTO "C_INTEREST_RATE_MST" (BUSINESS_ID,PRODUCT_CD,EFFECTIVE_DTM,CCY,CHANNEL,CUSTOMER_SEGMENT,TENURE_MONTH,TENURE_DAY,AMT_SLAB_FROM,AMT_SLAB_TO,
INTEREST_RATE,INTEREST_VARIANCE,PENALTY_RATE,PENALTY_VARIANCE,TENURE_TYPE) VALUES 
('ZMBRB','23',sysdate,'ZMW','A','MASS',3,0,100000,499999,7.5,null,null,null,'CR');

INSERT INTO "C_INTEREST_RATE_MST" (BUSINESS_ID,PRODUCT_CD,EFFECTIVE_DTM,CCY,CHANNEL,CUSTOMER_SEGMENT,TENURE_MONTH,TENURE_DAY,AMT_SLAB_FROM,AMT_SLAB_TO,
INTEREST_RATE,INTEREST_VARIANCE,PENALTY_RATE,PENALTY_VARIANCE,TENURE_TYPE) VALUES 
('ZMBRB','23',sysdate,'ZMW','A','MASS',6,0,35000,99999,8.5,null,null,null,'CR');
INSERT INTO "C_INTEREST_RATE_MST" (BUSINESS_ID,PRODUCT_CD,EFFECTIVE_DTM,CCY,CHANNEL,CUSTOMER_SEGMENT,TENURE_MONTH,TENURE_DAY,AMT_SLAB_FROM,AMT_SLAB_TO,
INTEREST_RATE,INTEREST_VARIANCE,PENALTY_RATE,PENALTY_VARIANCE,TENURE_TYPE) VALUES 
('ZMBRB','23',sysdate,'ZMW','A','MASS',6,0,100000,499999,9.5,null,null,null,'CR');

INSERT INTO "C_INTEREST_RATE_MST" (BUSINESS_ID,PRODUCT_CD,EFFECTIVE_DTM,CCY,CHANNEL,CUSTOMER_SEGMENT,TENURE_MONTH,TENURE_DAY,AMT_SLAB_FROM,AMT_SLAB_TO,
INTEREST_RATE,INTEREST_VARIANCE,PENALTY_RATE,PENALTY_VARIANCE,TENURE_TYPE) VALUES 
('ZMBRB','23',sysdate,'ZMW','A','MASS',12,0,35000,99999,10,null,null,null,'CR');
INSERT INTO "C_INTEREST_RATE_MST" (BUSINESS_ID,PRODUCT_CD,EFFECTIVE_DTM,CCY,CHANNEL,CUSTOMER_SEGMENT,TENURE_MONTH,TENURE_DAY,AMT_SLAB_FROM,AMT_SLAB_TO,
INTEREST_RATE,INTEREST_VARIANCE,PENALTY_RATE,PENALTY_VARIANCE,TENURE_TYPE) VALUES 
('ZMBRB','23',sysdate,'ZMW','A','MASS',12,0,100000,499999,11,null,null,null,'CR');


--Premiere FD (ZMW) Rates > 35k < 500k
INSERT INTO "C_INTEREST_RATE_MST" (BUSINESS_ID,PRODUCT_CD,EFFECTIVE_DTM,CCY,CHANNEL,CUSTOMER_SEGMENT,TENURE_MONTH,TENURE_DAY,AMT_SLAB_FROM,AMT_SLAB_TO,
INTEREST_RATE,INTEREST_VARIANCE,PENALTY_RATE,PENALTY_VARIANCE,TENURE_TYPE) VALUES 
('ZMBRB','22',sysdate,'ZMW','A','MASS',1,0,35000,99999,5.5,null,null,null,'CR');
INSERT INTO "C_INTEREST_RATE_MST" (BUSINESS_ID,PRODUCT_CD,EFFECTIVE_DTM,CCY,CHANNEL,CUSTOMER_SEGMENT,TENURE_MONTH,TENURE_DAY,AMT_SLAB_FROM,AMT_SLAB_TO,
INTEREST_RATE,INTEREST_VARIANCE,PENALTY_RATE,PENALTY_VARIANCE,TENURE_TYPE) VALUES 
('ZMBRB','22',sysdate,'ZMW','A','MASS',1,0,100000,499999,6.5,null,null,null,'CR');

INSERT INTO "C_INTEREST_RATE_MST" (BUSINESS_ID,PRODUCT_CD,EFFECTIVE_DTM,CCY,CHANNEL,CUSTOMER_SEGMENT,TENURE_MONTH,TENURE_DAY,AMT_SLAB_FROM,AMT_SLAB_TO,
INTEREST_RATE,INTEREST_VARIANCE,PENALTY_RATE,PENALTY_VARIANCE,TENURE_TYPE) VALUES 
('ZMBRB','22',sysdate,'ZMW','A','MASS',3,0,35000,99999,6.5,null,null,null,'CR');
INSERT INTO "C_INTEREST_RATE_MST" (BUSINESS_ID,PRODUCT_CD,EFFECTIVE_DTM,CCY,CHANNEL,CUSTOMER_SEGMENT,TENURE_MONTH,TENURE_DAY,AMT_SLAB_FROM,AMT_SLAB_TO,
INTEREST_RATE,INTEREST_VARIANCE,PENALTY_RATE,PENALTY_VARIANCE,TENURE_TYPE) VALUES 
('ZMBRB','22',sysdate,'ZMW','A','MASS',3,0,100000,499999,7.5,null,null,null,'CR');

INSERT INTO "C_INTEREST_RATE_MST" (BUSINESS_ID,PRODUCT_CD,EFFECTIVE_DTM,CCY,CHANNEL,CUSTOMER_SEGMENT,TENURE_MONTH,TENURE_DAY,AMT_SLAB_FROM,AMT_SLAB_TO,
INTEREST_RATE,INTEREST_VARIANCE,PENALTY_RATE,PENALTY_VARIANCE,TENURE_TYPE) VALUES 
('ZMBRB','22',sysdate,'ZMW','A','MASS',6,0,35000,99999,9,null,null,null,'CR');
INSERT INTO "C_INTEREST_RATE_MST" (BUSINESS_ID,PRODUCT_CD,EFFECTIVE_DTM,CCY,CHANNEL,CUSTOMER_SEGMENT,TENURE_MONTH,TENURE_DAY,AMT_SLAB_FROM,AMT_SLAB_TO,
INTEREST_RATE,INTEREST_VARIANCE,PENALTY_RATE,PENALTY_VARIANCE,TENURE_TYPE) VALUES 
('ZMBRB','22',sysdate,'ZMW','A','MASS',6,0,100000,499999,10,null,null,null,'CR');

INSERT INTO "C_INTEREST_RATE_MST" (BUSINESS_ID,PRODUCT_CD,EFFECTIVE_DTM,CCY,CHANNEL,CUSTOMER_SEGMENT,TENURE_MONTH,TENURE_DAY,AMT_SLAB_FROM,AMT_SLAB_TO,
INTEREST_RATE,INTEREST_VARIANCE,PENALTY_RATE,PENALTY_VARIANCE,TENURE_TYPE) VALUES 
('ZMBRB','22',sysdate,'ZMW','A','MASS',12,0,35000,99999,11,null,null,null,'CR');
INSERT INTO "C_INTEREST_RATE_MST" (BUSINESS_ID,PRODUCT_CD,EFFECTIVE_DTM,CCY,CHANNEL,CUSTOMER_SEGMENT,TENURE_MONTH,TENURE_DAY,AMT_SLAB_FROM,AMT_SLAB_TO,
INTEREST_RATE,INTEREST_VARIANCE,PENALTY_RATE,PENALTY_VARIANCE,TENURE_TYPE) VALUES 
('ZMBRB','22',sysdate,'ZMW','A','MASS',12,0,100000,499999,12,null,null,null,'CR');