package com.barclays.bmg.constants;

public interface AccountServiceResponseCodeConstant {

    String SUCCESS_CODE = "00000";
    String BEM_SERVICE_EXCEPTION = "BMB90004";
    String WARNING_CODE = "00001";
    String FCR_NO_ACCOUNT_EXCEPTION = "06754";

    // Account Summary
    String ACCOUNT_SUMMARY_SERVICE_EXCEPTION = "ASM00299";
    String ACT_ACTSUMMARY_NOACTFORSUMMARY = "ASM00200";
    String ACT_ACTSUMMARY_NOACTFORCCD = "CCD00100";

    // ACCOUNT DETAILS
    String ACCOUNT_DETAILS_ACCOUNT_NO_EMPTY = "ADT00300";
    // String ACCOUNT_DETAILS_INVALID_ACCOUNT_NO="ADT00301";
    String ACCOUNT_DETAILS_INVALID_ACCOUNT_NO = "ADT00302";
    String ACT_ACTDETAIL_CANNOTACCESS = "ADT00302";
    String ACT_ACTDETAIL_NOACTAVAILABLE = "ADT00303";

    // ACCOUNT ACTIVITY
    String ACCOUNT_ACTIVITY_ACCOUNT_NO_EMPTY = "AAC00400";
    String ACCOUNT_ACTIVITY_INVALID_ACCOUNT_NO = "AAC00401";
    String ACCOUNT_ACTIVITY_EMPTY_BIL_DATE = "AAC00402";
    String ACCOUNT_ACTIVITY_INVALID_TXN_DAY = "AAC00403";
    String ACCOUNT_ACTIVITY_NO_TRANX_FOUND = "AAC00404";
    String ACCOUNT_ACTIVITY_CRD_NO_EMPTY = "AAC00405";
    String ACCOUNT_ACTIVITY_INVALID_CRD_NO = "AAC00406";
    String ACCOUNT_ACTIVITY_CANNOTACCESS = "AAC00407";
    String ACCOUNT_ACTIVITY_NO_STMT_TRANX_FOUND = "AAC00408";

    String ACT_ACTDETAIL_NOSTATEMENTDATE = "FTR00531";

    String FCR_HOST_ERROR = "AAC00409";
    String PRIME_HOST_ERROR = "AAC00410";
    String TELESCO_HOST_ERROR = "AAC00411";
    String NO_TRANSACTIONS_FOUND_FOR_REQUEST = "U9043";
    String NO_STATEMENTS_FOUND = "U9040";

}
