package com.barclays.bmg.constants;

public interface ActivityConstant {

    String COMMON_ID = "COMMON";
    String SEC_COMMON_ID = "SEC_COMMON";
    String LOGIN_ACTIVITY_ID = "SEC_LOGIN";
    String SEC_ONLN_REG = "SEC_ONLN_REG";
    String FUND_TRANSFER_ACTIVITY_ID = "PMT_FT_FACADE";
    String OWN_FT_ACTIVITY_KEY = "OWN_FT_ACTIVITY_KEY";
    String PMT_FT_OWN = "PMT_FT_OWN";
    String PMT_FT_CS = "PMT_FT_CS";
    String ACCOUNT_SUMMARY_ACTIVITY_ID = "ACT_ACCOUNTSERVICE_ACCOUNTSUMMARY";
    String BILL_PAYMENT_ACTIVITY_ID = "PMT_BP_FACADE";
    String CASA_DETAIL_ACTIVITY_ID = "ACT_ACCOUNT_DETAIL_CASA_DETAIL";
    String MINI_STMT_ACTIVITY_ID = "ACT_ACCOUNT_CASA_ACTIVITY";
    String BILL_PAYMENT_PAYEE_ACTIVITY_ID = "PMT_BP_BILLPAY_PAYEE";
    String CREDIT_DETAIL_ACTIVITY_ID = "ACT_ACCOUNT_DETAIL_CREDIT_DETAIL";
    // String MOBILE_TOPUP_PAYEE_ACTIVITY_ID = "PMT_BP_MOBILE_TOPUP_PAYEE";
    String ACT_INVEST_MUTUALFUNDS = "ACT_INVEST_MUTUALFUNDS";
    String ACT_INVEST_STRUCTUREDNOTES = "ACT_INVEST_STRUCTUREDNOTES";
    String ACT_INVEST_BONDS = "ACT_INVEST_BONDS";
    String MUTUAL_FUND = "Mutual Fund";
    String STRUCTURED_NOTE = "Structured Notes";
    String BOND = "Bond";

    String BARCLAY_CARD_PAYMENT_PAYEE_ACTIVITY_ID = "PMT_BP_BCD_PAYEE";
    String FUND_TRANSFER_CARD_PAYMENT_PAYEE_ACTIVITY_ID = "PMT_FT_CARD_PAYMENT_PAYEE";
    String FUND_TRANSFER_INTERNAL_PAYEE_ACTIVITY_ID = "PMT_FT_INTERNAL_PAYEE";
    String FUND_TRANSFER__EXTERNAL_PAYEE_ACTIVITY_ID = "PMT_FT_EXTERNAL_PAYEE";

    String INTEREST_RATES_TD = "CUS_INT_RATES_TD";
    String TD_CATEGORY_CODE = "TMD";
    String TD_ACCOUNT_DETAILS = "ACT_OPEN_TD";
    String FUND_TRANSFER_BANK_DRAFT_FACADE_ACTIVITY_ID = "PMT_FT_BKD_FACADE";
    String FUND_TRANSFER_BANK_DRAFT_ONETIME_ACTIVITY_ID = "PMT_FT_BKD_ONETIME";
    String FUND_TRANSFER_BANK_DRAFT_PAYEE_ACTIVITY_ID = "PMT_FT_BKD_PAYEE";
    String APPLY_TD_SOURCEACC_LIST = "APPLY_TD_SOURCE_ACC_LIST";
    String APPLY_TD_SOURCEACC_VALIDATION = "APPLY_TD_SOURCEACC_VALIDATIONS";
    String APPLY_TD_ADD_PROBLEM = "APPLY_TD_ADD_PROBLEM";

    String MOBILE_TOPUP_PAYEE_ACTIVITY_ID = "PMT_BP_MOBILE_TOPUP_ONETIME";
    String MOBILE_WALLET_PAYEE_ACTIVITY_ID = "PMT_BP_MOBILE_WALLET_ONETIME";

    String OPEN_TERMDEPOSIT_ACTIVITY_ID = "ACT_OPEN_TD";

    String CREDIT_CARD_ATAGLANCE_ACTIVITY_ID = "ACT_CREDIT_CARD_DETAIL";
    String CREDIT_CARD_UNBILLED_TRANS_ACTIVITY_ID = "ACT_CCD_UNBILLED_TRANS";
    String CREDIT_CARD_STATEMENT_TRANS_ACTIVITY_ID = "ACT_CCD_STATEMENT_TRANS";
    String CREDIT_CARD_OWN_PAYMENT_ACTIVITY_ID = "PMT_FT_CARD_PAYMENT_OWN";
    String ACT_ADD_PROSPECT = "ACT_ADD_PROSPECT";

    //CR#46
    String CREDIT_CARD_LINK_ACTIVITY_ID = "CREDIT_CARD_LINK";
    //KITS
    String KITS_LOOKUP = "KITS_LOOKUP";
    String KITS_REGISTRATION = "KITS_REGISTRATION";
    String KITS_DEREGISTRATION = "KITS_DEREGISTRATION";

    //	CR#83 ApplyProduct
    String APPLY_PRODUCT_ACTIVITY_ID = "APPLY_PRODUCT";
    String FREE_DIAL_MWALLET = "FREEDIALMTN";

    //LoanRepayment
    String LOAN_RE_PMT_ENQ_ACTIVITY_ID = "LOAN_RE_PMT_ENQ";
    String LOAN_RE_PMT_ACTIVITY_ID = "LOAN_RE_PMT_MKLPMT";
    
    //Botswana welcome banner INC INC0063990 
    String BANNER_GROUP_ID = "LOGIN_ANNOUNCEMENT";

}
