package com.barclays.bmg.constants;

/**
 * @author BTCI
 * 
 */
public interface BeneficiaryResponseCodeConstants {

    String INVALID_ACCOUNT = "BNF00647";
    String BENEFICIARY_ID_EMPTY = "BNF00640";
    String INVALID_BENEFICIARY = "BNF00651";
    String BENEFICIARY_ACC_NUMBER_EMPTY = "BNF00641";
    String NO_PAYEES_REGISTERED = "BPY00616";
    String PAYEE_ALREADY_REGISTERED = "BNF00643";
    String ADD_BENEFICIARY_NEVER_INITIATED = "BNF00652";
    String BENEFICIARY_PAYEE_TYPE_EMPTY = "BNF00644";
    String BENEFICIARY_BANK_CODE_EMPTY = "BNF00645";
    String BENEFICIARY_BRANCH_CODE_EMPTY = "BNF00646";
    String BENEFICIARY_BNF_NAME_EMPTY = "BNF00648";
    String BENEFICIARY_BNF_NICK_NAME_EMPTY = "BNF00649";
    String BENEFICIARY_TXN_REF_NO_EMPTY = "BNF00650";

    String BENEFICIARY_VIEW_LIMIT_COUNT = "BNF90010";
    String BENEFICIARY_NICK_NAME_LENGTH = "BNF90011";

    String UPDATE_BENEFICIARY_NEVER_INITIATED = "BNF00700";

}
