package com.barclays.bmg.constants;

public interface BillPaymentResponseCodeConstants {

    String PAYMENT_BENEFICIARY_ID_EMPTY = "BPY00600";
    String PAYMENT_INVALID_BENEFICIARY = "BPY00601";
    String PAYEE_GROUP_EMPTY = "BPY00608";
    String NO_ACCOUNTS_FOR_SUMMARY = "BPY00605";
    String NO_OUTSTANDING_BILL = "BPY00609";
    String MTP_SERVICE_EMPTY = "BPY00610";
    String PAYMENT_AMOUNT_EMPTY = "BPY00603";
    String PAYMENT_FROM_ACCOUNT_EMPTY = "BPY00602";

    String PAYMENT_AMOUNT_GREATER_THEN_ZERO = "BPY00604";
    String INVALID_FROM_ACCOUNT = "BPY00607";
    String INVALID_BILL_PAY_AMT = "BPY00611";
    String BILL_PAY_NEVER_INITIATED = "BPY00612";
    String BP_TRANSACTIONABILITY_ERROR = "BPY00613";
    String BP_INSUFFICIENT_BALANCE = "BPY00614";
    String VAS_INVALID_ACCT_NO = "BPY00615";
    String NO_PAYEES_REGISTERED = "BPY00660";
    String INVALID_SALIK_AMOUNT = "BPY00617";
    String MTP_NOT_ACCORDING_INTERVAL = "BPY00618";
    String BCD_INVALID_CARD_NUMBER = "BPY00619";
    String BILLPAYMENT_MINIMAL_TXN_AMT = "BPY00620";
    String BP_BCD_PRIME_06878 = "BPY00621";

    // AIR TIME TOP UP
    String NO_BILLER_FOUND_FOR_USER = "BPY00622";

    // One Time Bill Pay
    String BILLER_ID_EMPTY = "BPY00650";
    String BILLER_REF_NO_EMPTY = "BPY00651";

}