package com.barclays.bmg.constants;

public interface FundTransferResponseCodeConstants {

    String FUNDTRANSFERDATACOMMAND_SOURCEACCOUNT_EMPTY = "FTR00502";
    String FUNDTRANSFERDATACOMMAND_TARGETACCOUNT_EMPTY = "FTR00503";
    String FUNDTRANSFERDATACOMMAND_TXAMOUNT_EMPTY = "FTR00504";
    String FUNDTRANSFERDATACOMMAND_TXDATE_EMPTY = "FTR00505";
    String FUNDTRANSFERDATACOMMAND_FORBID_SAME_ACCOUNT = "FTR00506";

    String OWN_FT_INIT_NOACCOUNTS_FOUND = "FTR00501";
    String OWN_FT_ONLY_ONE_ACCOUNT = "FTR00514";

    String FUNDTRANSER_INSUFFICIENT_BALANCE = "FTR00509";

    String TXN_LIMIT_COM_ONCE = "BMB90002";
    String TXN_DAILY_LIMIT_COM = "BMB90003";
    String BRANCH_LOOKUP_EMPTY_CITY_NAME = "BMB09902";
    String BRANCH_LOOKUP_EMPTY_BRANCH_NAME = "BMB09903";

    String INVALID_SRC_ACCT = "FTR00507";
    String INVALID_DEST_ACCT = "FTR00508";
    String FUNDTRANSFEREXECUTECOMMAND_TXREFKEY_EMPTY = "FTR00516";
    String FT_NEVER_INITIATED = "FTR00512";
    String FT_TRANSACTIONABILITY_ERROR = "FTR00513";

    String PAYMENT_INVALID_BENEFICIARY = "FTR00517";
    String PMT_COM_CCY_NOT_SAME = "FTR00518";
    String NO_PAYEE_IFT = "FTR00519";
    String NO_ACCTS_IFT = "FTR00520";
    String INVALID_TXN_AMT = "FTR00521";
    String PAYMENT_AMOUNT_GREATER_THEN_ZERO = "FTR00522";
    // External Fund Transfer
    String EXTERNAL_CHARGE_DESC_EMPTY = "FTR00524";
    String EXTERNAL_CURRENCY_EMPTY = "FTR00525";
    String EXTERNAL_REMITTANCE_PART1_EMPTY = "FTR00526";
    String EXTERNAL_PAYEE_REASON_DTLS_EMPTY = "FTR00527";
    String PMT_FT_INVALID_TRANSFER_CURRENCY = "FTR00528";
    String PMT_FT_INVALID_CURRENCY_TRANSACTION = "FTR00529";

    String BANK_CARD_NO_ACCOUNTS_FOUND = "BKD00001";

    String EMPTY_DELIVERY_TYPE = "FTR00530";
    String EMPTY_DRAFT_TYPE = "FTR00531";

    String NO_BRANCHES_FOUND = "BMB09901";
    String BRANCH_LOOKUP_EMPTY_BANK_NAME = "FTR00546";

    String EMPTY_BRANCH_CODE = "FTR00549";
    String EMPTY_BRANCH_NAME = "FTR00550";
    String EMPTY_PAYABLE_AT = "FTR00551";
    String EMPTY_CURRENCY = "FTR00552";
    String EMPTY_PAYMENT_REMARKS = "FTR00553";

    // Internal NonRegistered Fund tranfer;
    String INTERNAL_NON_REGISTERED_FUNDTRANSFERDATACOMMAND_FRMACCOUNT_EMPTY = "INRFTR001";
    String INTERNAL_NON_REGISTERED_FUNDTRANSFERDATACOMMAND_BENEFICIARYACCOUNT_EMPTY = "INRFTR002";
    String INTERNAL_NON_REGISTERED_FUNDTRANSFERDATACOMMAND_TXAMOUNT_EMPTY = "INRFTR003";
    String INTERNAL_NON_REGISTERED_FUNDTRANSFERDATACOMMAND_TXDATE_EMPTY = "INRFTR004";
    String INTERNAL_NON_REGISTERED_FUNDTRANSFERDATACOMMAND_EMPTY_BRANCH_CODE = "INRFTR005";
    String INTERNAL_NON_REGISTERED_FUNDTRANSFERDATACOMMAND_EMPTY_BENEFICIARY_NAME = "INRFTR006";
    String INTERNAL_NON_REGISTERED_FUNDTRANSFERDATACOMMAND_EMPTY_CURRENCY = "INRFTR007";
    String INTERNAL_NON_REGISTERED_FUNDTRANSFERDATACOMMAND_EMPTY_PAYDESC = "INRFTR008";

    // Transaction Second Auth
    String SECOND_AUTHCOMMAND_TXREFKEY_EMPTY = "SA55666";
    String SECOND_AUTHCOMMAND_POSITION1_EMPTY = "SA65666";
    String SECOND_AUTHCOMMAND_POSITION2_EMPTY = "SA75666";

    // Transaction Second Auth
    String CHALLENGE_QUES_COMMAND_MOBILENO_EMPTY = "SA88666";
    String CHALLENGE_QUES_COMMAND_SCVID_EMPTY = "SA85666";

    String TXN_LIMIT_COUNT = "BMB90010";
    String TXN_LIMIT_RANGE_UB = "BMB90011";

    // Cash Send Service
    String CASH_SEND_ACCOUNT_EMPTY = "CS001";
    String CASH_SEND_TXAMOUNT_EMPTY = "CS002";
    String CASH_SEND_EMPTY_CURRENCY = "CS003";
    String CASH_SEND_EMPTY_MOBILE_NO = "CS004";
    String CASH_SEND_EMPTY_VPIN = "CS005";
    String CASH_SEND_EMPTY_TXREFKEY_EMPTY = "CS006";
    String CASH_SEND_NEVER_INITIATED = "CS007";

    String CC_TXN_LIMIT_COUNT = "BMB90123";
    String CC_TXN_LIMIT_RANGE_UB = "BMB90124";
    String CC_TXN_LIMIT_COM_ONCE = "BMB90125";
    String CC_TXN_DAILY_LIMIT_COM = "BMB90126";

}
