package com.barclays.bmg.constants;

public interface ResponseIdConstants_forsvn {

    String RESPONSE_SERVICE_VERSION = "2.0";

    String LOGIN_RESPONSE_ID = "RES0100";
    String SQA_RESPONSE_ID = "RES0102";
    String OTP_RESPONSE_ID = "RES0101";
    String ACCOUNT_SUMMARY_RESPONSE_ID = "RES0200";
    String CASA_DETAILS_RESPONSE_ID = "RES0301";
    String TD_ACCOUNT_DETAILS_RESPONSE_ID = "RES0302";
    String CREDIT_CARD_DETAILS_RESPONSE_ID = "RES0303";
    String CASA_ACTIVITY_RESPONSE_ID = "RES0401";
    String OWN_FUND_TRANSFER_INIT_RESPONSE_ID = "RES0500";
    String OWN_FUND_TRANSFER_VALIDATE_RESPONSE_ID = "RES0501";
    String OWN_FUND_TRANSFER_EXECUTE_RESPONSE_ID = "RES0502";
    String TERMS_OF_USE_RESPONSE_ID = "RES0106";

    String RESEND_OTP_RESPONSE_ID = "RES0103";
    String LOGOUT_RESPONSE_ID = "RES0104";
    String CANCEL_LOGIN = "RES0111";
    String SESSION_INVALIDATED = "RES0199";
    String FEATURE_BLACKOUT = "RES0198";
    String AUTH_FAILURE_RESPONSE_ID = "RES0105";
    String INVALID_SECOND_AUTH_RESPONSE_ID = "RES0105";
    String SECOND_AUTH_SUCCESS = "RES0106";
    String OTP_VALIDATION_RESPONSE_ID = "RES0107";
    String SQA_VALIDATION_RESPONSE_ID = "RES0108";
    String CREDIT_CARD_ULBILD_RESPONSE_ID = "RES0402";
    String CREDIT_CARD_STMT_TXNS_RESPONSE_ID = "RES0403";
    String EXCEPTION_RESPONSE_ID = "RES9999";
    String MUTUAL_FUND_RESPONSE_ID = "RES0304";
    String STRUCTURED_NOTES_RESPONSE_ID = "RES0305";
    String BOND_RESPONSE_ID = "RES0306";

    // Bill Payment
    String RETRIEVE_BP_PAYEE_LIST_RESPONSE_ID = "RES0600";
    String RETRIEVE_BP_PAYEE_INFORMATION_RESPONSE_ID = "RES0601";
    String BP_PAYMENT_TRANSFER_FORM_SUBMIT_RESPONSE_ID = "RES0602";
    String CONFIRM_BILL_PAYMENT_RESPONSE_ID = "RES0603";

    // Mobile Top up
    String RETRIEVE_MTP_PAYEE_LIST_RESPONSE_ID = "RES0610";
    String RETRIEVE_MTP_PAYEE_INFORMATION_RESPONSE_ID = "RES0611";
    String MTP_PAYMENT_TRANSFER_FORM_SUBMIT_RESPONSE_ID = "RES0612";
    String CONFIRM_MTP_PAYEMENT_RESPONSE_ID = "RES0613";

    // Barclay Card
    String RETRIEVE_BCD_PAYEE_LIST_RESPONSE_ID = "RES0620";
    String RETRIEVE_BCD_PAYEE_INFORMATION_RESPONSE_ID = "RES0621";
    String BCD_PAYMENT_TRANSFER_FORM_SUBMIT_RESPONSE_ID = "RES0622";
    String CONFIRM_BCD_PAYEMENT_RESPONSE_ID = "RES0623";

    // String RETRIEVE_BCD_PAYEE_LIST_RESPONSE_ID="RES0620";
    String RETRIEVE_CCP_PAYEE_INFORMATION_RESPONSE_ID = "RES0631";
    String CCP_PAYMENT_TRANSFER_FORM_SUBMIT_RESPONSE_ID = "RES0632";
    String CONFIRM_CCP_PAYEMENT_RESPONSE_ID = "RES0633";

    String HYPHEN_SEPERATOR = "-";

    // Internal Fund Transfer
    String INTERNAL_FUND_TRANSFER_INIT_RESPONSE_ID = "RES0510";
    String INTERNAL_TRANSFER_VALIDATE_RESPONSE_ID = "RES0511";
    String INTERNAL_FUND_TRANSFER_EXECUTE_RESPONSE_ID = "RES0512";
    String INTERNAL_FUND_TRANSFER_DETAILS_RESPONSE_ID = "RES0513";

    // Internal Non Registered Fund Transfer
    String INTERNAL_NON_REGISTERED_FUND_TRANSFER_INIT_RESPONSE_ID = "RES0568";
    String INTERNAL_NON_REGISTERED_FUND_TRANSFER_DETAILS_RESPONSE_ID = "RES0569";
    String INTERNAL_NON_REGISTERED_FUND_TRANSFER_DETAILS_DONE = "RES0570";

    // Term Deposit Interest Rates
    String TD_INT_RATES_RESPONSE_ID = "RES0701";

    String TXN_SECOND_AUTH_OTP_RESPONSE_ID = "RES0107";
    String TXN_SECOND_AUTH_SQA_RESPONSE_ID = "RES0108";

    // Geo Coding
    String GEO_CODING_RESPONSE_ID = "RES0800";

    // External Fund Transfer

    String External_Fund_Transfer_Payee_List = "RES0520";
    String EXTERNAL_FUND_TRANSFER_PAY_INFO = "RES0521";
    String EXTERNAL_FUND_TRANSFER_FORM_SUBMIT = "RES0522";
    String EXTERNAL_FUND_TRANSFER_DONE = "RES0523";
    String EXTERNAL_FT_PAYEE_DETAILS = "RES0524";

    // International Fund Transfer

    String INTERNATIONAL_Fund_Transfer_Payee_List = "RES0530";
    String INTERNATIONAL_FUND_TRANSFER_PAY_INFO = "RES0531";
    String INTERNATIONAL_FUND_TRANSFER_FORM_SUBMIT = "RES0532";
    String INTERNATIONAL_FUND_TRANSFER_DONE = "RES0533";
    String INTERNATIONAL_FT_PAYEE_DETAILS = "RES0534";

    // Urgent External Fund Transfer

    String URGENT_External_Fund_Transfer_Payee_List = "RES0560";
    String URGENT_EXTERNAL_FUND_TRANSFER_PAY_INFO = "RES0561";
    String URGENT_EXTERNAL_FUND_TRANSFER_FORM_SUBMIT = "RES0562";
    String URGENT_EXTERNAL_FUND_TRANSFER_DONE = "RES0563";
    String URGENT_EXTERNAL_FT_PAYEE_DETAILS = "RES0564";

    // Bank Draft

    String BANK_DRAFT_FIRST_STEP = "RES0540";
    String BANK_DRAFT_SECOND_STEP = "RES0541";
    String BANK_DRAFT_THIRD_STEP = "RES0542";
    String BANK_DRAFT_FOURTH_STEP = "RES0543";

    String MANAGERS_CHEQUE_FIRST_STEP = "RES0544";
    String MANAGERS_CHEQUE_SECOND_STEP = "RES0545";
    String MANAGERS_CHEQUE_THIRD_STEP = "RES0546";
    String MANAGERS_CHEQUE_FOURTH_STEP = "RES0547";

    // Branch LookUp
    String BRANCH_LOOKUP = "RES9901";

    // Cheque Book

    String CHEQUE_BOOK_INIT = "RES0901";
    String CHEQUE_BOOK_CONFIRM = "RES0902";
    String CHEQUE_BOOK_EXECUTE = "RES0903";

    // Promotional offers
    String DINE_OFFERS = "RES1000";
    String DINE_OFFER_DETLS = "RES1001";
    String DINE_OFFERS_SEARCH = "RES1002";
    String EIP_OFFERS = "RES1010";
    String EIP_OFFER_DETLS = "RES1011";
    String EIP_OFFERS_SEARCH = "RES1012";
    String PROMO_OFFER_TERMSCOND = "RES1020";

    // Order paper Statement Request
    String STATMENT_REQUEST_INIT = "RES0910";
    String STATMENT_REQUEST_VALIDATE = "RES0911";
    String STATMENT_REQUEST_EXECUTE = "RES0912";

    String DELETE_BENEFICIARY = "RES0640";
    String ADD_BENEFICIARY_FORM_SUBMIT = "RES0641";
    String ADD_BENEFICIARY_EXECUTE = "RES0642";
    String SEARCH_TRANSACTION_HISTORY_BP = "RES0643";
    String SEARCH_TRANSACTION_HISTORY = "RES0645";
    String VIEW_BILL_PAYMENT_DETAILS = "RES0644";
    String VIEW_TXN_HISTORY_DETAILS = "RES0646";

    String CHANGE_USERNAME_PASSWORD = "RES0112";

    String ADD_ORG_FORMSUBMISSION_BENEFICIARY = "RES7771";
    String ADD_ORG_VALIDATIONCONTROLLER_BENEFICIARY = "RES7772";
    String ADD_ORG_EXECUTIONCONTROLLER_BENEFICIARY = "RES7773";
    String ADD_ORG_BENEFICIARY = "RES7773";
    String APPLY_TD__ACCOUNT_DETAILS_RESPONSE_ID = "RES1234";
    String APPLY_TD__ACCOUNT_VALIDATIONS_RESPONSE_ID = "RES1235";
    String APPLY_TD__ACCOUNT_EXECUTION_RESPONSE_ID = "RES1236";
    String VALIDATEUSER_SUCCESS = "RES5555";
    String VERIFY_USER_SUCCESS = "RES0198";

    String VALIDATEUSER_FAILURE_RESPONSE_ID = "RES5556";
    String VERIFY_USER_FAILURE_RESPONSE_ID = "RES0199";
    String APPLY_TD_VALIDATIONOPERATION_ = "RES1235";

    String ONE_TIME_BILL_PAY_INIT = "RES0650";
    String ONE_TIME_BILL_PAY_FORM_SUBMIT = "RES0651";
    String ONE_TIME_BILL_PAY_EXECUTE = "RES0652";

    String AIR_MTP_VALIDATION = "RES0621";

    String AIR_TIME_TOP_UP = "RES0660";
    String AIR_TIME_TOP_UP_JSONBLD_VALD = "RES0661";

    String M_WALLET_INIT = "RES0640";
    String M_WALLET_VALIDATION = "RES0641";

}
