package com.barclays.bmg.constants;

public interface StatementResponseCodeConstant {

    String STATEMENT_ACCOUNT_NUMBER_NO_EMPTY = "STM0910";
    String STATEMENT_FROMDATE_NO_EMPTY = "STM0911";
    String STATEMENT_FROMTO_NO_EMPTY = "STM0912";
    String STATEMENT_DATE_SAME = "STM0913";
    String STATEMENT_NOT_COMPLETE = "STM0914";
    String STATMENT_REMOTE_EXCEPTION = "STM0915";
    String STATEMENT_FROM_DATE_GRATER_TO_DATE = "STM0916";
    String STATEMENT_FROM_OR_TO_DATE_GRATER_CURRENT_DATE = "STM0917";

}
