---------- Rollback ------

DELETE FROM C_LISTVALUE_MST WHERE BUSINESS_ID='GHBRB' and SYSTEM_ID='UB';

DELETE FROM C_LISTVALUE_RES_MST WHERE BUSINESS_ID='GHBRB' and SYSTEM_ID='UB';

DELETE  FROM C_BIZ_FUNC_MMAP where BUSINESS_ID='GHBRB' and SYSTEM_ID='UB';

COMMIT;

