
UPDATE S_SYSPARAM_MST SET PARAM_VALUE = 'BWP,USD,CAD,GBP,CHF,ZAR,JPY,AUD,DKK,NZD,HKD,KES,ZMK,ZWD,NOK,SEK,INR,MWK,EUR'  WHERE (BUSINESS_ID = 'BWBRB' AND SYSTEM_ID = 'MB' AND PARAM_ID = 'PMT_FT_SUPPORT_CURRENCY' AND ACTIVITY_ID = 'PMT_FT_SI_INTERNAL_ONETIME');

UPDATE S_SYSPARAM_MST SET PARAM_VALUE = 'BWP,USD,CAD,GBP,CHF,ZAR,JPY,AUD,DKK,NZD,HKD,KES,ZMK,ZWD,NOK,SEK,INR,MWK,EUR'  WHERE (BUSINESS_ID = 'BWBRB' AND SYSTEM_ID = 'MB' AND PARAM_ID = 'PMT_FT_SUPPORT_CURRENCY' AND ACTIVITY_ID = 'PMT_FT_INTERNAL_ONETIME');

UPDATE S_SYSPARAM_MST SET PARAM_VALUE = 'BWP,USD,CAD,GBP,CHF,ZAR,JPY,AUD,DKK,NZD,HKD,KES,ZMK,ZWD,NOK,SEK,INR,MWK,EUR'  WHERE (BUSINESS_ID = 'BWBRB' AND SYSTEM_ID = 'MB' AND PARAM_ID = 'PMT_FT_SUPPORT_CURRENCY' AND ACTIVITY_ID = 'PMT_FT_INTL_ONETIME');

UPDATE S_SYSPARAM_MST SET PARAM_VALUE = 'BWP,USD,CAD,GBP,CHF,ZAR,JPY,AUD,DKK,NZD,HKD,KES,ZMK,ZWD,NOK,SEK,INR,MWK,EUR'  WHERE (BUSINESS_ID = 'BWBRB' AND SYSTEM_ID = 'MB' AND PARAM_ID = 'PMT_FT_SUPPORT_CURRENCY' AND ACTIVITY_ID = 'PMT_FT_INTERNAL_PAYEE');

UPDATE S_SYSPARAM_MST SET PARAM_VALUE = 'BWP,USD,CAD,GBP,CHF,ZAR,JPY,AUD,DKK,NZD,HKD,KES,ZMK,ZWD,NOK,SEK,INR,MWK,EUR'  WHERE (BUSINESS_ID = 'BWBRB' AND SYSTEM_ID = 'MB' AND PARAM_ID = 'PMT_FT_SUPPORT_CURRENCY' AND ACTIVITY_ID = 'PMT_FT_INTL_PAYEE');

UPDATE S_SYSPARAM_MST SET PARAM_VALUE = 'USD,CAD,GBP,CHF,ZAR,JPY,AUD,DKK,BWP,KES,MUR,UGX,ZMK,NOK,SEK,LSL,MWK,SZL,TZS,EUR'  WHERE (BUSINESS_ID = 'ZWBRB' AND SYSTEM_ID = 'MB' AND PARAM_ID = 'PMT_FT_SUPPORT_CURRENCY' AND ACTIVITY_ID = 'PMT_FT_SI_INTERNAL_ONETIME');

UPDATE S_SYSPARAM_MST SET PARAM_VALUE = 'USD,CAD,GBP,CHF,ZAR,JPY,AUD,DKK,BWP,KES,MUR,UGX,ZMK,NOK,SEK,LSL,MWK,SZL,TZS,EUR'  WHERE (BUSINESS_ID = 'ZWBRB' AND SYSTEM_ID = 'MB' AND PARAM_ID = 'PMT_FT_SUPPORT_CURRENCY' AND ACTIVITY_ID = 'PMT_FT_INTERNAL_ONETIME');

UPDATE S_SYSPARAM_MST SET PARAM_VALUE = 'USD,CAD,GBP,CHF,ZAR,JPY,AUD,DKK,BWP,KES,MUR,UGX,ZMK,NOK,SEK,LSL,MWK,SZL,TZS,EUR'  WHERE (BUSINESS_ID = 'ZWBRB' AND SYSTEM_ID = 'MB' AND PARAM_ID = 'PMT_FT_SUPPORT_CURRENCY' AND ACTIVITY_ID = 'PMT_FT_INTL_ONETIME');

UPDATE S_SYSPARAM_MST SET PARAM_VALUE = 'USD,CAD,GBP,CHF,ZAR,JPY,AUD,DKK,BWP,KES,MUR,UGX,ZMK,NOK,SEK,LSL,MWK,SZL,TZS,EUR'  WHERE (BUSINESS_ID = 'ZWBRB' AND SYSTEM_ID = 'MB' AND PARAM_ID = 'PMT_FT_SUPPORT_CURRENCY' AND ACTIVITY_ID = 'PMT_FT_INTERNAL_PAYEE');

UPDATE S_SYSPARAM_MST SET PARAM_VALUE = 'USD,CAD,GBP,CHF,ZAR,JPY,AUD,DKK,BWP,KES,MUR,UGX,ZMK,NOK,SEK,LSL,MWK,SZL,TZS,EUR'  WHERE (BUSINESS_ID = 'ZWBRB' AND SYSTEM_ID = 'MB' AND PARAM_ID = 'PMT_FT_SUPPORT_CURRENCY' AND ACTIVITY_ID = 'PMT_FT_INTL_PAYEE');

UPDATE S_SYSPARAM_MST SET PARAM_VALUE = 'USD,CAD,GBP,CHF,ZAR,JPY,AUD,DKK,NZD,BWP,GHS,HKD,KES,MUR,SCR,SGD,UGX,AED,ZMK,NOK,SEK,EGP,INR,THB,TZS,EUR'  WHERE (BUSINESS_ID = 'MUBOB' AND SYSTEM_ID = 'MB' AND PARAM_ID = 'PMT_FT_SUPPORT_CURRENCY' AND ACTIVITY_ID = 'PMT_FT_INTL_PAYEE');

UPDATE S_SYSPARAM_MST SET PARAM_VALUE = 'USD,CAD,GBP,CHF,ZAR,JPY,AUD,DKK,NZD,BWP,GHS,HKD,KES,MUR,SCR,SGD,UGX,AED,ZMK,NOK,SEK,EGP,INR,THB,TZS,EUR'  WHERE (BUSINESS_ID = 'MUBOB' AND SYSTEM_ID = 'MB' AND PARAM_ID = 'PMT_FT_SUPPORT_CURRENCY' AND ACTIVITY_ID = 'PMT_FT_INTERNAL_ONETIME');

UPDATE S_SYSPARAM_MST SET PARAM_VALUE = 'USD,CAD,GBP,CHF,ZAR,JPY,AUD,DKK,NZD,BWP,GHS,HKD,KES,MUR,SCR,SGD,UGX,AED,ZMK,NOK,SEK,EGP,INR,THB,TZS,EUR'  WHERE (BUSINESS_ID = 'MUBOB' AND SYSTEM_ID = 'MB' AND PARAM_ID = 'PMT_FT_SUPPORT_CURRENCY' AND ACTIVITY_ID = 'PMT_FT_SI_INTERNAL_ONETIME');

UPDATE S_SYSPARAM_MST SET PARAM_VALUE = 'USD,CAD,GBP,CHF,ZAR,JPY,AUD,DKK,NZD,BWP,GHS,HKD,KES,MUR,SCR,SGD,UGX,AED,ZMK,NOK,SEK,EGP,INR,THB,TZS,EUR'  WHERE (BUSINESS_ID = 'MUBOB' AND SYSTEM_ID = 'MB' AND PARAM_ID = 'PMT_FT_SUPPORT_CURRENCY' AND ACTIVITY_ID = 'PMT_FT_INTL_ONETIME');

UPDATE S_SYSPARAM_MST SET PARAM_VALUE = 'USD,CAD,GBP,CHF,ZAR,JPY,AUD,DKK,NZD,BWP,GHS,HKD,KES,MUR,SCR,SGD,UGX,AED,ZMK,NOK,SEK,EGP,INR,THB,TZS,EUR'  WHERE (BUSINESS_ID = 'MUBOB' AND SYSTEM_ID = 'MB' AND PARAM_ID = 'PMT_FT_SUPPORT_CURRENCY' AND ACTIVITY_ID = 'PMT_FT_INTERNAL_PAYEE');

COMMIT;