CREATE OR REPLACE
PROCEDURE BIR_Procedure_SSA( var_business_id IN  VARCHAR2 )
IS

BEGIN

---------- C_BIZ_FUNC_MMAP  ------

	DELETE  FROM C_BIZ_FUNC_MMAP where business_id=var_business_id and system_id='MB';

	INSERT INTO  C_BIZ_FUNC_MMAP (SELECT BUSINESS_ID, ACTIVITY_ID, 'MB', FROM_TIME,  TO_TIME, HOLIDAY_ALLOWED_FLG,  BLOCKED_FLG   FROM C_BIZ_FUNC_MMAP   WHERE SYSTEM_ID = 'IB' AND BUSINESS_ID = var_business_id);

	DELETE FROM C_BIZ_FUNC_MMAP where BUSINESS_ID=var_business_id and SYSTEM_ID='MB' AND ACTIVITY_ID='PMT_FT_MRC_PAYEE';

	INSERT INTO C_BIZ_FUNC_MMAP (BUSINESS_ID,ACTIVITY_ID,SYSTEM_ID,FROM_TIME,TO_TIME,HOLIDAY_ALLOWED_FLG,BLOCKED_FLG) values (var_business_id,'PMT_FT_MRC_PAYEE','MB',null,null,'N','N');

	DELETE FROM C_BIZ_FUNC_MMAP where BUSINESS_ID=var_business_id and SYSTEM_ID='MB' AND ACTIVITY_ID='PMT_FT_BKD_PAYEE';

	INSERT INTO C_BIZ_FUNC_MMAP (BUSINESS_ID,ACTIVITY_ID,SYSTEM_ID,FROM_TIME,TO_TIME,HOLIDAY_ALLOWED_FLG,BLOCKED_FLG) values (var_business_id,'PMT_FT_BKD_PAYEE','MB',null,null,'N','N');

---------- C_FORMATTER_MST ------

	DELETE  FROM C_FORMATTER_MST where business_id=var_business_id and system_id='MB';

	INSERT INTO  C_FORMATTER_MST (SELECT FORMATTER_ID,FORMATTER_STRING,'MB',BUSINESS_ID,MAKER_ID,CHECKER_ID,STATUS,LAST_MODIFIED,LAST_AUTHORIZED,ACTION,DELETED_FLAG,AUTHORIZED_INDICATOR,MESSAGE_KEY   FROM C_FORMATTER_MST   WHERE SYSTEM_ID = 'IB' AND BUSINESS_ID = var_business_id  );

---------- C_FUNCTION_SCREEN_MMAP ----

	DELETE  FROM C_FUNCTION_SCREEN_MMAP  where business_id=var_business_id and system_id='MB';

	INSERT INTO  C_FUNCTION_SCREEN_MMAP (SELECT BUSINESS_ID,'MB',ACTIVITY_ID,SCREEN_ID  FROM C_FUNCTION_SCREEN_MMAP   WHERE SYSTEM_ID = 'IB' AND BUSINESS_ID=var_business_id );

----------- C_MESSAGE_MST ----

	DELETE  FROM C_MESSAGE_MST  where business_id=var_business_id and system_id='MB';

	INSERT INTO  C_MESSAGE_MST (SELECT 'MB',BUSINESS_ID, CATEGORY, MESSAGE_KEY, MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG, SOURCE_SYSTEM_ID  FROM C_MESSAGE_MST   WHERE SYSTEM_ID = 'IB' AND  BUSINESS_ID=var_business_id  );

--------- C_MESSAGE_RES_MST ------

	DELETE  FROM C_MESSAGE_RES_MST  where business_id=var_business_id and system_id='MB';

	INSERT INTO  C_MESSAGE_RES_MST (SELECT LANGUAGE_ID, MESSAGE_VALUE, 'MB', BUSINESS_ID, MESSAGE_KEY  FROM C_MESSAGE_RES_MST   WHERE SYSTEM_ID = 'IB' AND  BUSINESS_ID=var_business_id  );

--------- C_SCRIPT_MST -----------

	DELETE  FROM C_SCRIPT_MST  where business_id=var_business_id and system_id='MB';

	INSERT INTO  C_SCRIPT_MST (SELECT 'MB',BUSINESS_ID,CATEGORY_ID,SCRIPT_KEY,MAKER_ID,CHECKER_ID,STATUS,LAST_MODIFIED,LAST_AUTHORIZED,ACTION,DELETED_FLAG, AUTHORIZED_INDICATOR  FROM C_SCRIPT_MST  WHERE SYSTEM_ID = 'IB'  AND  BUSINESS_ID=var_business_id );

----------------- C_SCRIPT_RES_MST ---------

	DELETE  FROM C_SCRIPT_RES_MST  where business_id=var_business_id and system_id='MB';

	INSERT INTO  C_SCRIPT_RES_MST (SELECT LANGUAGE_ID, SEQUENCE_NO, SCRIPT_VALUE, MAKER_ID, CHECKER_ID, STATUS, LAST_MODIFIED, LAST_AUTHORIZED, ACTION, DELETED_FLAG, AUTHORIZED_INDICATOR, SCRIPT_KEY, 'MB', BUSINESS_ID  FROM C_SCRIPT_RES_MST  WHERE SYSTEM_ID = 'IB'  AND  BUSINESS_ID=var_business_id  );

----------- S_SES_SUMMARY_HST --------------

	DELETE  FROM S_SES_SUMMARY_HST  where business_id=var_business_id and system_id='MB';

	INSERT INTO  S_SES_SUMMARY_HST (SELECT BUSINESS_ID,'MB',USER_ID,SESS_ID,TXN_TYP,TXN_TIME,ACCT_FROM,ACCT_TO,AMOUNT,STATUS,REF_NO,DETAILS  FROM S_SES_SUMMARY_HST  WHERE SYSTEM_ID = 'IB'  AND BUSINESS_ID=var_business_id);

--------- S_SYSPARAM_MST --------------

	DELETE  FROM S_SYSPARAM_MST  where business_id=var_business_id and system_id='MB';

	INSERT INTO  S_SYSPARAM_MST (SELECT BUSINESS_ID,'MB',PARAM_ID, PARAM_VALUE, PARAM_COMPONENT_KEY, ACTIVITY_ID,SYSTEM_MAINTAIN,DISP_TYPE,MODIFIED_DTM,MODIFIED_BY,AUTHORISED_BY,AUTHORISED_DTM,DELETE_FLG,PARAM_DESC,CREATED_BY,CREATED_DTM  FROM S_SYSPARAM_MST  WHERE SYSTEM_ID = 'IB'  AND  BUSINESS_ID=var_business_id);

------------ C_COMPONENT_MST ------------

	DELETE  FROM C_COMPONENT_MST  where business_id=var_business_id and system_id='MB';

	INSERT INTO  C_COMPONENT_MST (SELECT SCREEN_ID,'MB',BUSINESS_ID,COMPONENT_KEY,RENDERED_FLG,REQUIRED_FLG,HAS_HELP_TEXT_FLG,FORMATTER_ID,LISTVALUE_GROUP_ID,DEFAULT_VALUE,DISP_ORDER,PARENT_COMPONENT_KEY,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,CONFIG_FLG,COMPONENT_TYPE,READONLY_FLG  FROM C_COMPONENT_MST  WHERE SYSTEM_ID = 'IB'  AND  BUSINESS_ID=var_business_id );

------------- C_COMPONENT_RES_MST -----------

	DELETE  FROM C_COMPONENT_RES_MST  where business_id=var_business_id and system_id='MB';

	INSERT INTO  C_COMPONENT_RES_MST (SELECT LANGUAGE_ID,LABEL_VALUE,TOOL_TIP,HELP_TEXT,LENGTH,SCREEN_ID,'MB',BUSINESS_ID,COMPONENT_KEY  FROM C_COMPONENT_RES_MST  WHERE SYSTEM_ID = 'IB'  AND  BUSINESS_ID=var_business_id );

---------------- S_FUNCTION_CONFIG ---------------

	DELETE  FROM S_FUNCTION_CONFIG  where business_id=var_business_id and system_id='MB';

	INSERT INTO  S_FUNCTION_CONFIG(SELECT BUSINESS_ID,'MB',ACTIVITY_ID,TXN_LIMIT_TYP,FEATURE_BLKOUT_FLG,ADV_TXT_FLG,ADV_IMG_TOP_FLG,ADV_IMG_RIGHTNAV_FLG,MODIFIED_DTM,MODIFIED_BY  FROM S_FUNCTION_CONFIG  WHERE SYSTEM_ID = 'IB'  AND  BUSINESS_ID=var_business_id );

	COMMIT;

END;
/






























