CREATE OR REPLACE
PROCEDURE BOC_Procedure_SSA( var_business_id IN  VARCHAR2 )
IS

BEGIN

---------------  C_BIZ_FUNC_MMAP  ------

	DELETE  FROM C_BIZ_FUNC_MMAP where BUSINESS_ID=var_business_id and SYSTEM_ID='MB';

	INSERT INTO  C_BIZ_FUNC_MMAP (SELECT BUSINESS_ID, ACTIVITY_ID, 'MB', FROM_TIME,  TO_TIME, HOLIDAY_ALLOWED_FLG,  BLOCKED_FLG   FROM C_BIZ_FUNC_MMAP   WHERE SYSTEM_ID = 'IB' AND BUSINESS_ID = var_business_id);

	DELETE FROM C_BIZ_FUNC_MMAP where BUSINESS_ID=var_business_id and SYSTEM_ID='MB' AND ACTIVITY_ID='PMT_FT_MRC_PAYEE';

	INSERT INTO C_BIZ_FUNC_MMAP (BUSINESS_ID,ACTIVITY_ID,SYSTEM_ID,FROM_TIME,TO_TIME,HOLIDAY_ALLOWED_FLG,BLOCKED_FLG) values (var_business_id,'PMT_FT_MRC_PAYEE','MB',null,null,'N','N');

	DELETE FROM C_BIZ_FUNC_MMAP where BUSINESS_ID=var_business_id and SYSTEM_ID='MB' AND ACTIVITY_ID='PMT_FT_BKD_PAYEE';

	INSERT INTO C_BIZ_FUNC_MMAP (BUSINESS_ID,ACTIVITY_ID,SYSTEM_ID,FROM_TIME,TO_TIME,HOLIDAY_ALLOWED_FLG,BLOCKED_FLG) values (var_business_id,'PMT_FT_BKD_PAYEE','MB',null,null,'N','N');

---------------- C_LISTVALUE_MST ----------

	DELETE  FROM C_LISTVALUE_MST where BUSINESS_ID=var_business_id and SYSTEM_ID='MB';

	INSERT INTO  C_LISTVALUE_MST (SELECT 'MB',BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG, EDITABLE_FLG  FROM C_LISTVALUE_MST  WHERE SYSTEM_ID = 'IB'  AND  BUSINESS_ID=var_business_id);

---------------- C_LISTVALUE_RES_MST ----------

	DELETE  FROM C_LISTVALUE_RES_MST where BUSINESS_ID=var_business_id and SYSTEM_ID='MB';

	INSERT INTO  C_LISTVALUE_RES_MST (SELECT 'MB',BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER  FROM C_LISTVALUE_RES_MST  WHERE SYSTEM_ID = 'IB'  AND  BUSINESS_ID=var_business_id);

--------------- INSERTING into C_LISTVALUE_MST - for 'FT_DELIVERY_TYPE'
	DELETE FROM C_LISTVALUE_MST where SYSTEM_ID='MB' and GROUP_ID='FT_DELIVERY_TYPE'  AND BUSINESS_ID=var_business_id;

	INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('MB',var_business_id,'FT_DELIVERY_TYPE','BEN',null,null,'N',null,null,null,null,'N','Y');
	INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('MB',var_business_id,'FT_DELIVERY_TYPE','BRN',null,null,'N',null,null,null,null,'N','Y');
	INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('MB',var_business_id,'FT_DELIVERY_TYPE','REM',null,null,'N',null,null,null,null,'N','Y');


-------------- INSERTING into C_LISTVALUE_RES_MST - for 'FT_DELIVERY_TYPE'
	DELETE FROM C_LISTVALUE_RES_MST where SYSTEM_ID='MB' and GROUP_ID='FT_DELIVERY_TYPE' AND BUSINESS_ID=var_business_id;

	INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('MB',var_business_id,'FT_DELIVERY_TYPE','REM','EN','Mail to Remitter',0);
	INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('MB',var_business_id,'FT_DELIVERY_TYPE','BEN','EN','Mail to Beneficiary',2);
	INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('MB',var_business_id,'FT_DELIVERY_TYPE','BRN','EN','Collect at Branch',4);

-------------- INSERTING into C_LISTVALUE_MST - for 'FT_DRAFT_TYPE'
	DELETE FROM C_LISTVALUE_MST where SYSTEM_ID='MB' and GROUP_ID='FT_DRAFT_TYPE'  AND BUSINESS_ID=var_business_id;

	INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('MB',var_business_id,'FT_DRAFT_TYPE','BD',null,null,'N',null,null,null,null,'N','Y');
	INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('MB',var_business_id,'FT_DRAFT_TYPE','MC',null,null,'N',null,null,null,null,'N','Y');

-------------- INSERTING into C_LISTVALUE_RES_MST - for 'FT_DRAFT_TYPE'
	DELETE FROM C_LISTVALUE_RES_MST where SYSTEM_ID='MB' and GROUP_ID='FT_DRAFT_TYPE'  AND BUSINESS_ID=var_business_id;

	INSERT INTO	C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('MB',var_business_id,'FT_DRAFT_TYPE','BD','EN','Bank Draft',1);
	INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('MB',var_business_id,'FT_DRAFT_TYPE','MC','EN','Manager''s Cheque',2);


---------------  C_COMPONENT_MST ----------------

	DELETE  FROM C_COMPONENT_MST where business_id=var_business_id and system_id='MB';

	INSERT INTO  C_COMPONENT_MST (SELECT SCREEN_ID,'MB',BUSINESS_ID,COMPONENT_KEY,RENDERED_FLG,REQUIRED_FLG,HAS_HELP_TEXT_FLG,FORMATTER_ID,LISTVALUE_GROUP_ID,DEFAULT_VALUE,DISP_ORDER,PARENT_COMPONENT_KEY,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,CONFIG_FLG,COMPONENT_TYPE,READONLY_FLG  FROM C_COMPONENT_MST  WHERE SYSTEM_ID = 'IB'  AND  BUSINESS_ID=var_business_id);

---------------  C_COMPONENT_RES_MST --------------

	DELETE  FROM C_COMPONENT_RES_MST where business_id=var_business_id and system_id='MB';

	INSERT INTO  C_COMPONENT_RES_MST (SELECT LANGUAGE_ID,LABEL_VALUE,TOOL_TIP,HELP_TEXT,LENGTH,SCREEN_ID,'MB',BUSINESS_ID,COMPONENT_KEY  FROM C_COMPONENT_RES_MST  WHERE SYSTEM_ID = 'IB'  AND  BUSINESS_ID=var_business_id);

---------------- S_FUNCTION_CONFIG -----------------

	DELETE  FROM S_FUNCTION_CONFIG where business_id=var_business_id and system_id='MB';

	INSERT INTO  S_FUNCTION_CONFIG(SELECT BUSINESS_ID,'MB',ACTIVITY_ID,TXN_LIMIT_TYP,FEATURE_BLKOUT_FLG,ADV_TXT_FLG,ADV_IMG_TOP_FLG,ADV_IMG_RIGHTNAV_FLG,MODIFIED_DTM,MODIFIED_BY  FROM S_FUNCTION_CONFIG  WHERE SYSTEM_ID = 'IB'  AND  BUSINESS_ID=var_business_id);

---------------  S_LIMIT_GLOBAL_MST	------

	DELETE FROM  S_LIMIT_GLOBAL_MST   WHERE SYSTEM_ID = 'MB' AND BUSINESS_ID=var_business_id ;

	INSERT INTO  S_LIMIT_GLOBAL_MST (SELECT BUSINESS_ID,  'MB', TXN_LIMIT_TYP,  DAILY_LIMIT_AMT , TXN_LIMIT_AMT,  THRESHOLD_LIMIT_AMT, MODIFIED_BY, MODIFIED_DTM, AUTHORISED_BY, AUTHORISED_DTM, DELETE_FLG    FROM S_LIMIT_GLOBAL_MST   WHERE SYSTEM_ID = 'IB' AND BUSINESS_ID=var_business_id );

---------------- S_LIMIT_CUST_MST ------

	DELETE FROM  S_LIMIT_CUST_MST   WHERE SYSTEM_ID = 'MB' AND BUSINESS_ID=var_business_id ;

	INSERT INTO  S_LIMIT_CUST_MST (SELECT BUSINESS_ID,  'MB', TXN_LIMIT_TYP,  CUST_ID , DAILY_LIMIT_AMT,  TXN_LIMIT_AMT, THRESHOLD_LIMIT_AMT, MODIFIED_BY, MODIFIED_DTM, AUTHORISED_BY, AUTHORISED_DTM, DELETE_FLG   FROM S_LIMIT_CUST_MST   WHERE SYSTEM_ID = 'IB' AND BUSINESS_ID=var_business_id );

	COMMIT;


END;
/
