
INSERT INTO C_BIZ_FUNC_MMAP (BUSINESS_ID,ACTIVITY_ID,SYSTEM_ID,FROM_TIME,TO_TIME,HOLIDAY_ALLOWED_FLG,BLOCKED_FLG) values ('GHBRB','PMT_FT_CARD_PAYMENT_PAYEE','MB',null,null,'N','N');
INSERT INTO C_BIZ_FUNC_MMAP (BUSINESS_ID,ACTIVITY_ID,SYSTEM_ID,FROM_TIME,TO_TIME,HOLIDAY_ALLOWED_FLG,BLOCKED_FLG) values ('BWBRB','PMT_FT_CARD_PAYMENT_PAYEE','MB',null,null,'N','N');
INSERT INTO C_BIZ_FUNC_MMAP (BUSINESS_ID,ACTIVITY_ID,SYSTEM_ID,FROM_TIME,TO_TIME,HOLIDAY_ALLOWED_FLG,BLOCKED_FLG) values ('MUBRB','PMT_FT_CARD_PAYMENT_PAYEE','MB',null,null,'N','N');
INSERT INTO C_BIZ_FUNC_MMAP (BUSINESS_ID,ACTIVITY_ID,SYSTEM_ID,FROM_TIME,TO_TIME,HOLIDAY_ALLOWED_FLG,BLOCKED_FLG) values ('SCBRB','PMT_FT_CARD_PAYMENT_PAYEE','MB',null,null,'N','N');
INSERT INTO C_BIZ_FUNC_MMAP (BUSINESS_ID,ACTIVITY_ID,SYSTEM_ID,FROM_TIME,TO_TIME,HOLIDAY_ALLOWED_FLG,BLOCKED_FLG) values ('TZBRB','PMT_FT_CARD_PAYMENT_PAYEE','MB',null,null,'N','N');
INSERT INTO C_BIZ_FUNC_MMAP (BUSINESS_ID,ACTIVITY_ID,SYSTEM_ID,FROM_TIME,TO_TIME,HOLIDAY_ALLOWED_FLG,BLOCKED_FLG) values ('ZMBRB','PMT_FT_CARD_PAYMENT_PAYEE','MB',null,null,'N','N');
INSERT INTO C_BIZ_FUNC_MMAP (BUSINESS_ID,ACTIVITY_ID,SYSTEM_ID,FROM_TIME,TO_TIME,HOLIDAY_ALLOWED_FLG,BLOCKED_FLG) values ('ZWBRB','PMT_FT_CARD_PAYMENT_PAYEE','MB',null,null,'N','N');

COMMIT;