
Insert into C_PRODUCT_MST (PRODUCT_CD,	BUSINESS_ID,PRODUCT_DESC,PRODUCT_GROUP,PRODUCT_SUBGROUP,SOURCE_SYSTEM_ID,MODIFIED_BY,MODIFIED_DTM, AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG  ,CURRENCY_CD,TENURE_TYP,MIN_AMOUNT,MAX_AMOUNT,ESAVER_IND,INTERNET_ENABLED,INT_PAYOUT_FRQ,INT_COMPD_FRQ,SUPPORT_CHEQUE) values('911','TZBRB','Classic Fixed Term Deposit','TMD',null,null,null,null,null,null,'N','TZS',null,null,null,null,null,null,null,null);
Insert into C_PRODUCT_MST (PRODUCT_CD,	BUSINESS_ID,PRODUCT_DESC,PRODUCT_GROUP,PRODUCT_SUBGROUP,SOURCE_SYSTEM_ID,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG  ,CURRENCY_CD,TENURE_TYP,MIN_AMOUNT,MAX_AMOUNT,ESAVER_IND,INTERNET_ENABLED,INT_PAYOUT_FRQ,INT_COMPD_FRQ,SUPPORT_CHEQUE) values('912','TZBRB','Flexi Term Deposit','TMD',null,null,null,null,null,null,'N'  ,'TZS',null,null,null,null,null,null,null,null);
Insert into C_PRODUCT_MST (PRODUCT_CD,	BUSINESS_ID,PRODUCT_DESC,PRODUCT_GROUP,PRODUCT_SUBGROUP,SOURCE_SYSTEM_ID,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG  ,CURRENCY_CD,TENURE_TYP,MIN_AMOUNT,MAX_AMOUNT,ESAVER_IND,INTERNET_ENABLED,INT_PAYOUT_FRQ,INT_COMPD_FRQ,SUPPORT_CHEQUE) values('913','TZBRB','Regular  Interest Term Deposite','TMD',null,null,null,null,null,null,'N'  ,'TZS',null,null,null,null,null,null,null,null);

commit;

