--------- C_ROLE_FUNC_MMAP ---------

	DELETE  FROM C_ROLE_FUNC_MMAP  where  system_id='MB';

	INSERT INTO   C_ROLE_FUNC_MMAP (SELECT ROLE_ID,ACTIVITY_ID,'MB',EFFECTIVE_START_DT,EFFECTIVE_END_DT,CHECKER_FLG,MAKER_FLG,ACWS_FLG, CONSULSTANT_FLG  FROM C_ROLE_FUNC_MMAP  WHERE SYSTEM_ID = 'IB' );
	COMMIT;

