
--------------- PRODUCTION INTERNET URL ------------

DELETE FROM S_URL_BUSINESS_MAP_MST WHERE BUSINESS_ID='GHBRB' AND URL_PATTERN='https://www.gh.secure.barclays.com/bmg';
COMMIT;

DELETE FROM S_URL_BUSINESS_MAP_MST WHERE BUSINESS_ID='BWBRB' AND URL_PATTERN='https://www.bw.secure.barclays.com/bmg';
COMMIT;

DELETE FROM S_URL_BUSINESS_MAP_MST WHERE BUSINESS_ID='MUBRB' AND URL_PATTERN='https://www.muon.secure.barclays.com/bmg';
COMMIT;

DELETE FROM S_URL_BUSINESS_MAP_MST WHERE BUSINESS_ID='ZWBRB' AND URL_PATTERN='https://www.zw.secure.barclays.com/bmg';
COMMIT;

DELETE FROM S_URL_BUSINESS_MAP_MST WHERE BUSINESS_ID='EGBRB' AND URL_PATTERN='https://www.eg.secure.barclays.com/bmg';
COMMIT;

DELETE FROM S_URL_BUSINESS_MAP_MST WHERE BUSINESS_ID='SCBRB' AND URL_PATTERN='https://www.sc.secure.barclays.com/bmg';
COMMIT;

DELETE FROM S_URL_BUSINESS_MAP_MST WHERE BUSINESS_ID='TZBRB' AND URL_PATTERN='https://www.tz.secure.barclays.com/bmg';
COMMIT;

DELETE FROM S_URL_BUSINESS_MAP_MST WHERE BUSINESS_ID='ZMBRB' AND URL_PATTERN='https://www.zm.secure.barclays.com/bmg';
COMMIT;

INSERT INTO S_URL_BUSINESS_MAP_MST (SYSTEM_ID, BUSINESS_ID, URL_PATTERN, LANGUAGE_ID) VALUES ('MB','GHBRB','https://www.gh.secure.barclays.com/bmg','EN');
COMMIT;
INSERT INTO S_URL_BUSINESS_MAP_MST (SYSTEM_ID, BUSINESS_ID, URL_PATTERN, LANGUAGE_ID) VALUES ('MB','BWBRB','https://www.bw.secure.barclays.com/bmg','EN');
COMMIT;
INSERT INTO S_URL_BUSINESS_MAP_MST (SYSTEM_ID, BUSINESS_ID, URL_PATTERN, LANGUAGE_ID) VALUES ('MB','MUBRB','https://www.muon.secure.barclays.com/bmg','EN');
COMMIT;
INSERT INTO S_URL_BUSINESS_MAP_MST (SYSTEM_ID, BUSINESS_ID, URL_PATTERN, LANGUAGE_ID) VALUES ('MB','ZWBRB','https://www.zw.secure.barclays.com/bmg','EN');
COMMIT;
INSERT INTO S_URL_BUSINESS_MAP_MST (SYSTEM_ID, BUSINESS_ID, URL_PATTERN, LANGUAGE_ID) VALUES ('MB','EGBRB','https://www.eg.secure.barclays.com/bmg','EN');
COMMIT;
INSERT INTO S_URL_BUSINESS_MAP_MST (SYSTEM_ID, BUSINESS_ID, URL_PATTERN, LANGUAGE_ID) VALUES ('MB','SCBRB','https://www.sc.secure.barclays.com/bmg','EN');
COMMIT;
INSERT INTO S_URL_BUSINESS_MAP_MST (SYSTEM_ID, BUSINESS_ID, URL_PATTERN, LANGUAGE_ID) VALUES ('MB','TZBRB','https://www.tz.secure.barclays.com/bmg','EN');
COMMIT;
INSERT INTO S_URL_BUSINESS_MAP_MST (SYSTEM_ID, BUSINESS_ID, URL_PATTERN, LANGUAGE_ID) VALUES ('MB','ZMBRB','https://www.zm.secure.barclays.com/bmg','EN');
COMMIT;


--------------- PRODUCTION INTRANET URL ------------

DELETE FROM S_URL_BUSINESS_MAP_MST WHERE BUSINESS_ID='GHBRB' AND URL_PATTERN='https://ghc2bir-live.barclays.intranet/bmg';
COMMIT;

DELETE FROM S_URL_BUSINESS_MAP_MST WHERE BUSINESS_ID='BWBRB' AND URL_PATTERN='https://bwc2bir-live.barclays.intranet/bmg';
COMMIT;

DELETE FROM S_URL_BUSINESS_MAP_MST WHERE BUSINESS_ID='MUBRB' AND URL_PATTERN='https://muonc2bir-live.barclays.intranet/bmg';
COMMIT;

DELETE FROM S_URL_BUSINESS_MAP_MST WHERE BUSINESS_ID='ZWBRB' AND URL_PATTERN='https://zwc2bir-live.barclays.intranet/bmg';
COMMIT;

DELETE FROM S_URL_BUSINESS_MAP_MST WHERE BUSINESS_ID='EGBRB' AND URL_PATTERN='https://egc2bir-live.barclays.intranet/bmg';
COMMIT;

DELETE FROM S_URL_BUSINESS_MAP_MST WHERE BUSINESS_ID='SCBRB' AND URL_PATTERN='https://scc2bir-live.barclays.intranet/bmg';
COMMIT;

DELETE FROM S_URL_BUSINESS_MAP_MST WHERE BUSINESS_ID='TZBRB' AND URL_PATTERN='https://tzc2bir-live.barclays.intranet/bmg';
COMMIT;

DELETE FROM S_URL_BUSINESS_MAP_MST WHERE BUSINESS_ID='ZMBRB' AND URL_PATTERN='https://zmc2bir-live.barclays.intranet/bmg';
COMMIT;



INSERT INTO S_URL_BUSINESS_MAP_MST (SYSTEM_ID, BUSINESS_ID, URL_PATTERN, LANGUAGE_ID) VALUES ('MB','GHBRB','https://ghc2bir-live.barclays.intranet/bmg','EN');
COMMIT;
INSERT INTO S_URL_BUSINESS_MAP_MST (SYSTEM_ID, BUSINESS_ID, URL_PATTERN, LANGUAGE_ID) VALUES ('MB','BWBRB','https://bwc2bir-live.barclays.intranet/bmg','EN');
COMMIT;
INSERT INTO S_URL_BUSINESS_MAP_MST (SYSTEM_ID, BUSINESS_ID, URL_PATTERN, LANGUAGE_ID) VALUES ('MB','MUBRB','https://muonc2bir-live.barclays.intranet/bmg','EN');
COMMIT;
INSERT INTO S_URL_BUSINESS_MAP_MST (SYSTEM_ID, BUSINESS_ID, URL_PATTERN, LANGUAGE_ID) VALUES ('MB','ZWBRB','https://zwc2bir-live.barclays.intranet/bmg','EN');
COMMIT;
INSERT INTO S_URL_BUSINESS_MAP_MST (SYSTEM_ID, BUSINESS_ID, URL_PATTERN, LANGUAGE_ID) VALUES ('MB','EGBRB','https://egc2bir-live.barclays.intranet/bmg','EN');
COMMIT;
INSERT INTO S_URL_BUSINESS_MAP_MST (SYSTEM_ID, BUSINESS_ID, URL_PATTERN, LANGUAGE_ID) VALUES ('MB','SCBRB','https://scc2bir-live.barclays.intranet/bmg','EN');
COMMIT;
INSERT INTO S_URL_BUSINESS_MAP_MST (SYSTEM_ID, BUSINESS_ID, URL_PATTERN, LANGUAGE_ID) VALUES ('MB','TZBRB','https://tzc2bir-live.barclays.intranet/bmg','EN');
COMMIT;
INSERT INTO S_URL_BUSINESS_MAP_MST (SYSTEM_ID, BUSINESS_ID, URL_PATTERN, LANGUAGE_ID) VALUES ('MB','ZMBRB','https://zmc2bir-live.barclays.intranet/bmg','EN');
COMMIT;
