

-- C_MESSAGE_MST --

delete from C_MESSAGE_MST where MESSAGE_KEY like ('BMB9001%') and SYSTEM_ID='UB' and BUSINESS_ID='TZBRB';

INSERT into C_MESSAGE_MST (SYSTEM_ID,BUSINESS_ID,CATEGORY,MESSAGE_KEY,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,SOURCE_SYSTEM_ID) values ('UB','TZBRB','ERROR','BMB90010',null,null,null,null,null,null);
INSERT into C_MESSAGE_MST (SYSTEM_ID,BUSINESS_ID,CATEGORY,MESSAGE_KEY,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,SOURCE_SYSTEM_ID) values ('UB','TZBRB','ERROR','BMB90011',null,null,null,null,null,null);

COMMIT;
-------------C_MESSAGE_RES_MST----------------

delete from C_MESSAGE_RES_MST where MESSAGE_KEY like ('BMB9001%') and SYSTEM_ID='UB' and BUSINESS_ID='TZBRB';

INSERT into C_MESSAGE_RES_MST (LANGUAGE_ID,MESSAGE_VALUE,SYSTEM_ID,BUSINESS_ID,MESSAGE_KEY) values ('EN','The transaction count must be less than or equal to your transaction count limit','UB','TZBRB','BMB90010');
INSERT into C_MESSAGE_RES_MST (LANGUAGE_ID,MESSAGE_VALUE,SYSTEM_ID,BUSINESS_ID,MESSAGE_KEY) values ('EN','The transaction amount must be within transaction range limit','UB','TZBRB','BMB90011');

COMMIT;
--------


-- C_MESSAGE_MST --

delete from C_MESSAGE_MST where MESSAGE_KEY like ('BNF9001%') and SYSTEM_ID='UB' and BUSINESS_ID='TZBRB';

INSERT into C_MESSAGE_MST (SYSTEM_ID,BUSINESS_ID,CATEGORY,MESSAGE_KEY,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,SOURCE_SYSTEM_ID) values ('UB','TZBRB','ERROR','BNF90010',null,null,null,null,null,null);
INSERT into C_MESSAGE_MST (SYSTEM_ID,BUSINESS_ID,CATEGORY,MESSAGE_KEY,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,SOURCE_SYSTEM_ID) values ('UB','TZBRB','ERROR','BNF90011',null,null,null,null,null,null);

COMMIT;
-------------C_MESSAGE_RES_MST----------------

delete from C_MESSAGE_RES_MST where MESSAGE_KEY like ('BNF9001%') and SYSTEM_ID='UB' and BUSINESS_ID='TZBRB';

INSERT into C_MESSAGE_RES_MST (LANGUAGE_ID,MESSAGE_VALUE,SYSTEM_ID,BUSINESS_ID,MESSAGE_KEY) values ('EN','Max Benificiary View Limit Parameter is not set or set as 0','UB','TZBRB','BNF90010');
INSERT into C_MESSAGE_RES_MST (LANGUAGE_ID,MESSAGE_VALUE,SYSTEM_ID,BUSINESS_ID,MESSAGE_KEY) values ('EN','The beneficiary nick name length should be within defined limit','UB','TZBRB','BNF90011');

COMMIT;
--------



-- C_MESSAGE_MST --

delete from C_MESSAGE_MST where MESSAGE_KEY like ('TH00%') and SYSTEM_ID='UB' and BUSINESS_ID='TZBRB';

INSERT INTO C_MESSAGE_MST (SYSTEM_ID,BUSINESS_ID,CATEGORY,MESSAGE_KEY,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,SOURCE_SYSTEM_ID) values ('UB','TZBRB','ERROR','TH00640',null,null,null,null,null,null);
INSERT INTO C_MESSAGE_MST (SYSTEM_ID,BUSINESS_ID,CATEGORY,MESSAGE_KEY,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,SOURCE_SYSTEM_ID) values ('UB','TZBRB','ERROR','TH00641',null,null,null,null,null,null);
INSERT INTO C_MESSAGE_MST (SYSTEM_ID,BUSINESS_ID,CATEGORY,MESSAGE_KEY,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,SOURCE_SYSTEM_ID) values ('UB','TZBRB','ERROR','TH00642',null,null,null,null,null,null);

COMMIT;
-------------C_MESSAGE_RES_MST----------------

delete from C_MESSAGE_RES_MST where MESSAGE_KEY like ('TH00%') and SYSTEM_ID='UB' and BUSINESS_ID='TZBRB';

INSERT INTO C_MESSAGE_RES_MST (LANGUAGE_ID,MESSAGE_VALUE,SYSTEM_ID,BUSINESS_ID,MESSAGE_KEY) values ('EN','Transaction Type is Required.','UB','TZBRB','TH00640');
INSERT INTO C_MESSAGE_RES_MST (LANGUAGE_ID,MESSAGE_VALUE,SYSTEM_ID,BUSINESS_ID,MESSAGE_KEY) values ('EN','Transaction Reference Number is Empty.','UB','TZBRB','TH00641');
INSERT INTO C_MESSAGE_RES_MST (LANGUAGE_ID,MESSAGE_VALUE,SYSTEM_ID,BUSINESS_ID,MESSAGE_KEY) values ('EN','No Transaction History Found.','UB','TZBRB','TH00642');

COMMIT;


-- C_MESSAGE_MST --

delete from C_MESSAGE_MST where MESSAGE_KEY='ATH00200' and SYSTEM_ID='UB' and BUSINESS_ID='TZBRB';
delete from C_MESSAGE_MST where MESSAGE_KEY='ATH00130' and SYSTEM_ID='UB' and BUSINESS_ID='TZBRB';

INSERT INTO C_MESSAGE_MST (SYSTEM_ID,BUSINESS_ID,CATEGORY,MESSAGE_KEY,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,SOURCE_SYSTEM_ID) values ('UB','TZBRB','ERROR','ATH00200',null,null,null,null,null,'MCFE');

INSERT INTO C_MESSAGE_MST (SYSTEM_ID,BUSINESS_ID,CATEGORY,MESSAGE_KEY,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,SOURCE_SYSTEM_ID) values ('UB','TZBRB','ERROR','ATH00130',null,null,null,null,null,'MCFE');

commit;

-------------C_MESSAGE_RES_MST----------------

delete from C_MESSAGE_RES_MST where MESSAGE_KEY='ATH00200' and SYSTEM_ID='UB' and BUSINESS_ID='TZBRB';
delete from C_MESSAGE_RES_MST where MESSAGE_KEY='ATH00130' and SYSTEM_ID='UB' and BUSINESS_ID='TZBRB';


INSERT INTO C_MESSAGE_RES_MST (LANGUAGE_ID,MESSAGE_VALUE,SYSTEM_ID,BUSINESS_ID,MESSAGE_KEY) values ('EN','Password needs to be changed','UB','TZBRB','ATH00200');

INSERT INTO C_MESSAGE_RES_MST (LANGUAGE_ID,MESSAGE_VALUE,SYSTEM_ID,BUSINESS_ID,MESSAGE_KEY) values ('EN','Mobile Number is empty','UB','TZBRB','ATH00130');

commit;
