
DELETE FROM S_SYSPARAM_MST where BUSINESS_ID='TZBRB' and SYSTEM_ID='UB' and PARAM_ID='APPLY_TD_USER_ID';

Insert into S_SYSPARAM_MST (BUSINESS_ID,SYSTEM_ID,PARAM_ID,PARAM_VALUE,PARAM_COMPONENT_KEY,ACTIVITY_ID,SYSTEM_MAINTAIN,DISP_TYPE,MODIFIED_DTM,MODIFIED_BY,AUTHORISED_BY,AUTHORISED_DTM,DELETE_FLG,PARAM_DESC,CREATED_BY,CREATED_DTM) values ('TZBRB','UB','APPLY_TD_USER_ID','BIR','APPLY_TD_USER_ID','ACT_OPEN_TD','Y','INPUT_TEXT',null,null,null,null,null,'Apply TD User Id',null,to_timestamp('03-APR-12 13.46.28.000000000','DD-MON-RR HH24.MI.SS.FF'));

DELETE FROM S_SYSPARAM_MST where BUSINESS_ID='TZBRB' and SYSTEM_ID='UB' and PARAM_ID='APPLY_TD_SERVICE_TYPE';

Insert into S_SYSPARAM_MST (BUSINESS_ID,SYSTEM_ID,PARAM_ID,PARAM_VALUE,PARAM_COMPONENT_KEY,ACTIVITY_ID,SYSTEM_MAINTAIN,DISP_TYPE,MODIFIED_DTM,MODIFIED_BY,AUTHORISED_BY,AUTHORISED_DTM,DELETE_FLG,PARAM_DESC,CREATED_BY,CREATED_DTM) values ('TZBRB','UB','APPLY_TD_SERVICE_TYPE','ServiceType_293','APPLY_TD_SERVICE_TYPE','ACT_OPEN_TD','Y','INPUT_TEXT',null,null,null,null,null,'Apply TD Service Type',null,to_timestamp('03-APR-12 13.46.28.000000000','DD-MON-RR HH24.MI.SS.FF'));


commit;