
--------------------------------------------
SYS_PARAM_FTOWN-----------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------

DELETE FROM  C_LISTVALUE_MST WHERE SYSTEM_ID='UB' AND BUSINESS_ID='TZBRB' AND GROUP_ID='SYS_PARAM_FTOWN';
COMMIT;

Insert into C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('UB','TZBRB','SYS_PARAM_FTOWN','FTOWN_MAX_AMT',null,null,'N',null,null,null,null,null,'Y');

Insert into C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('UB','TZBRB','SYS_PARAM_FTOWN','FTOWN_MIN_AMT',null,null,'N',null,null,null,null,'N','Y');

Insert into C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('UB','TZBRB','SYS_PARAM_FTOWN','FTOWN_MAX_DAYAMT',null,null,'N',null,null,null,null,'N','Y');

Insert into C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('UB','TZBRB','SYS_PARAM_FTOWN','FTOWN_MAX_TXS',null,null,'N',null,null,null,null,'N','Y');


COMMIT;
-----------------------------------------------

DELETE FROM C_LISTVALUE_RES_MST  WHERE SYSTEM_ID='UB' AND BUSINESS_ID='TZBRB' AND GROUP_ID='SYS_PARAM_FTOWN';
COMMIT;


Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_FTOWN','FTOWN_MAX_AMT','EN','50000',1);

Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_FTOWN','FTOWN_MIN_AMT','EN','10',2);

Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_FTOWN','FTOWN_MAX_DAYAMT','EN','100000',3);

Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_FTOWN','FTOWN_MAX_TXS','EN','100',4);


COMMIT;

--------------------------------------------
SYS_PARAM_FTOTH-----------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------

DELETE FROM  C_LISTVALUE_MST WHERE SYSTEM_ID='UB' AND BUSINESS_ID='TZBRB' AND GROUP_ID='SYS_PARAM_FTOTH';
COMMIT;

Insert into C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('UB','TZBRB','SYS_PARAM_FTOTH','FTOTH_MAX_TXS',null,null,'N',null,null,null,null,null,'Y');

Insert into C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('UB','TZBRB','SYS_PARAM_FTOTH','FTOTH_MIN_AMT',null,null,'N',null,null,null,null,'N','Y');

Insert into C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('UB','TZBRB','SYS_PARAM_FTOTH','FTOTH_MAX_AMT',null,null,'N',null,null,null,null,'N','Y');

Insert into C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('UB','TZBRB','SYS_PARAM_FTOTH','FTOTH_MAX_DAYAMT',null,null,'N',null,null,null,null,'N','Y');


COMMIT;
-----------------------------------------------

DELETE FROM C_LISTVALUE_RES_MST  WHERE SYSTEM_ID='UB' AND BUSINESS_ID='TZBRB' AND GROUP_ID='SYS_PARAM_FTOTH';
COMMIT;


Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_FTOTH','FTOTH_MAX_TXS','EN','100',1);

Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_FTOTH','FTOTH_MIN_AMT','EN','10',2);

Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_FTOTH','FTOTH_MAX_AMT','EN','50000',3);

Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_FTOTH','FTOTH_MAX_DAYAMT','EN','100000',3);



COMMIT;

--------------------------------------------
SYS_PARAM_DFT-------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------

DELETE FROM  C_LISTVALUE_MST WHERE SYSTEM_ID='UB' AND BUSINESS_ID='TZBRB' AND GROUP_ID='SYS_PARAM_DFT';
COMMIT;

Insert into C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('UB','TZBRB','SYS_PARAM_DFT','FTDFT_MAX_AMT',null,null,'N',null,null,null,null,null,'Y');

Insert into C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('UB','TZBRB','SYS_PARAM_DFT','FTDFT_MAX_TXS',null,null,'N',null,null,null,null,'N','Y');

Insert into C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('UB','TZBRB','SYS_PARAM_DFT','FTDFT_MIN_AMT',null,null,'N',null,null,null,null,'N','Y');

Insert into C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('UB','TZBRB','SYS_PARAM_DFT','FTDFT_MAX_DAYAMT',null,null,'N',null,null,null,null,'N','Y');


COMMIT;
-----------------------------------------------

DELETE FROM C_LISTVALUE_RES_MST  WHERE SYSTEM_ID='UB' AND BUSINESS_ID='TZBRB' AND GROUP_ID='SYS_PARAM_DFT';
COMMIT;


Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_DFT','FTDFT_MAX_AMT','EN','50000',1);

Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_DFT','FTDFT_MAX_TXS','EN','100',2);

Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_DFT','FTDFT_MIN_AMT','EN','10',3);

Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_DFT','FTDFT_MAX_DAYAMT','EN','100000',3);


COMMIT;

--------------------------------------------
SYS_PARAM_MWALLET---------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------

DELETE FROM  C_LISTVALUE_MST WHERE SYSTEM_ID='UB' AND BUSINESS_ID='TZBRB' AND GROUP_ID='SYS_PARAM_MWALLET';
COMMIT;

Insert into C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('UB','TZBRB','SYS_PARAM_MWALLET','MWALLET_MAX_AMT',null,null,'N',null,null,null,null,null,'Y');

Insert into C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('UB','TZBRB','SYS_PARAM_MWALLET','MWALLET_MIN_AMT',null,null,'N',null,null,null,null,'N','Y');

Insert into C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('UB','TZBRB','SYS_PARAM_MWALLET','MWALLET_MAX_DAYAMT',null,null,'N',null,null,null,null,'N','Y');

Insert into C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('UB','TZBRB','SYS_PARAM_MWALLET','MWALLET_MAX_TXS',null,null,'N',null,null,null,null,'N','Y');


COMMIT;
-----------------------------------------------

DELETE FROM C_LISTVALUE_RES_MST  WHERE SYSTEM_ID='UB' AND BUSINESS_ID='TZBRB' AND GROUP_ID='SYS_PARAM_MWALLET';
COMMIT;


Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_MWALLET','MWALLET_MAX_AMT','EN','50000',1);

Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_MWALLET','MWALLET_MIN_AMT','EN','500',2);

Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_MWALLET','MWALLET_MAX_DAYAMT','EN','100000',3);

Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_MWALLET','MWALLET_MAX_TXS','EN','100',4);


COMMIT;

--------------------------------------------
SYS_PARAM_TOPUP-----------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------

DELETE FROM  C_LISTVALUE_MST WHERE SYSTEM_ID='UB' AND BUSINESS_ID='TZBRB' AND GROUP_ID='SYS_PARAM_TOPUP';
COMMIT;

Insert into C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('UB','TZBRB','SYS_PARAM_TOPUP','MIN_TOPUP_AMT',null,null,'N',null,null,null,null,null,'Y');

Insert into C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('UB','TZBRB','SYS_PARAM_TOPUP','MAX_TOPUP_AMT',null,null,'N',null,null,null,null,'N','Y');

Insert into C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('UB','TZBRB','SYS_PARAM_TOPUP','TOPUP_MAX_DAYAMT',null,null,'N',null,null,null,null,'N','Y');

Insert into C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('UB','TZBRB','SYS_PARAM_TOPUP','TOPUP_MAX_TXS',null,null,'N',null,null,null,null,'N','Y');


COMMIT;
-----------------------------------------------

DELETE FROM C_LISTVALUE_RES_MST  WHERE SYSTEM_ID='UB' AND BUSINESS_ID='TZBRB' AND GROUP_ID='SYS_PARAM_TOPUP';
COMMIT;


Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_TOPUP','MIN_TOPUP_AMT','EN','500',1);

Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_TOPUP','MAX_TOPUP_AMT','EN','50000',2);

Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_TOPUP','TOPUP_MAX_DAYAMT','EN','100000',3);

Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_TOPUP','TOPUP_MAX_TXS','EN','100',4);


COMMIT;

--------------------------------------------
SYS_PARAM_BNF-------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------

DELETE FROM C_LISTVALUE_MST  WHERE SYSTEM_ID='UB' AND BUSINESS_ID='TZBRB' AND GROUP_ID='SYS_PARAM_BNF';

COMMIT;

Insert into C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('UB','TZBRB','SYS_PARAM_BNF','VIEW_MAX_BENFCR',null,null,'N',null,null,null,null,null,'Y');

Insert into C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('UB','TZBRB','SYS_PARAM_BNF','VIEW_MAX_BILLER_SIZE',null,null,'N',null,null,null,null,null,'Y');

Insert into C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('UB','TZBRB','SYS_PARAM_BNF','PAYEE_NICK_LENGTH_MAX',null,null,'N',null,null,null,null,null,'Y');

COMMIT;
-----------------------------------------------

DELETE FROM C_LISTVALUE_RES_MST  WHERE SYSTEM_ID='UB' AND BUSINESS_ID='TZBRB' AND GROUP_ID='SYS_PARAM_BNF';
COMMIT;


Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_BNF','VIEW_MAX_BENFCR','EN','5',1);


Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_BNF','VIEW_MAX_BILLER_SIZE','EN','10',2);

Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_BNF','PAYEE_NICK_LENGTH_MAX','EN','10',3);

COMMIT;

--------------------------------------------------------------------

DELETE FROM C_LISTVALUE_MST  WHERE SYSTEM_ID='UB' AND BUSINESS_ID='TZBRB' AND GROUP_ID='SYS_PARAM_SMS_FTEXT';
DELETE FROM C_LISTVALUE_MST  WHERE SYSTEM_ID='UB' AND BUSINESS_ID='TZBRB' AND GROUP_ID='SYS_PARAM_SMS_FTINT';
DELETE FROM C_LISTVALUE_MST  WHERE SYSTEM_ID='UB' AND BUSINESS_ID='TZBRB' AND GROUP_ID='SYS_PARAM_SMS_FTINT';
DELETE FROM C_LISTVALUE_MST  WHERE SYSTEM_ID='UB' AND BUSINESS_ID='TZBRB' AND GROUP_ID='SYS_PARAM_SMS_BP';
DELETE FROM C_LISTVALUE_MST  WHERE SYSTEM_ID='UB' AND BUSINESS_ID='TZBRB' AND GROUP_ID='SYS_PARAM_SMS_CHPW';
DELETE FROM C_LISTVALUE_MST  WHERE SYSTEM_ID='UB' AND BUSINESS_ID='TZBRB' AND GROUP_ID='SYS_PARAM_SMS_BOCPIN';
DELETE FROM C_LISTVALUE_MST  WHERE SYSTEM_ID='UB' AND BUSINESS_ID='TZBRB' AND GROUP_ID='SYS_PARAM_SMS_BOCREG';
DELETE FROM C_LISTVALUE_MST  WHERE SYSTEM_ID='UB' AND BUSINESS_ID='TZBRB' AND GROUP_ID='SYS_PARAM_SMS_PIN';
DELETE FROM C_LISTVALUE_MST  WHERE SYSTEM_ID='UB' AND BUSINESS_ID='TZBRB' AND GROUP_ID='SYS_PARAM_SMS_BPPAYEE';
DELETE FROM C_LISTVALUE_MST  WHERE SYSTEM_ID='UB' AND BUSINESS_ID='TZBRB' AND GROUP_ID='SYS_PARAM_SMS_PAYEEEXT';
DELETE FROM C_LISTVALUE_MST  WHERE SYSTEM_ID='UB' AND BUSINESS_ID='TZBRB' AND GROUP_ID='SYS_PARAM_SMS_PAYEEINT';
DELETE FROM C_LISTVALUE_MST  WHERE SYSTEM_ID='UB' AND BUSINESS_ID='TZBRB' AND GROUP_ID='SYS_PARAM_SMS_TOPUP';

COMMIT;

INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG)VALUES ('UB','TZBRB','SYS_PARAM_SMS_FTEXT','SMS_FTEXT_PAYEE_SUCCESS',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,'Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG)VALUES ('UB','TZBRB','SYS_PARAM_SMS_FTEXT','SMS_FTEXT_PAYEE_FAIL',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,'Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG)VALUES ('UB','TZBRB','SYS_PARAM_SMS_FTINT','SMS_FTINT_PAYEE_SUCCESS',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,'Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG)VALUES ('UB','TZBRB','SYS_PARAM_SMS_FTINT','SMS_FTINT_PAYEE_FAIL',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,'Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG)VALUES ('UB','TZBRB','SYS_PARAM_SMS_FTOWN','SMS_FTOWN_SUCCESS',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,'Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG)VALUES ('UB','TZBRB','SYS_PARAM_SMS_FTOWN','SMS_FTOWN_FAIL',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,'Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG)VALUES ('UB','TZBRB','SYS_PARAM_SMS_BP','SMS_BP_PAYEE_SUCCESS',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,'Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG)VALUES ('UB','TZBRB','SYS_PARAM_SMS_BP','SMS_BP_PAYEE_FAIL',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,'Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG)VALUES ('UB','TZBRB','SYS_PARAM_SMS_CHPW','SMS_CHGPWD_SUCCESS',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,'Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG)VALUES ('UB','TZBRB','SYS_PARAM_SMS_BOCPIN','SMS_BOC_PIN_REISSUE',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,'Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG)VALUES ('UB','TZBRB','SYS_PARAM_SMS_BOCREG','SMS_BOC_REG_SUCCESS',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,'Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG)VALUES ('UB','TZBRB','SYS_PARAM_SMS_BOCREG','SMS_BOC_REG_FAIL',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,'Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG)VALUES ('UB','TZBRB','SYS_PARAM_SMS_PIN','SMS_PIN_REISSUE_SUCCESS',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,'Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG)VALUES ('UB','TZBRB','SYS_PARAM_SMS_PIN','SMS_PIN_REISSUE_FAIL',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,'Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG)VALUES ('UB','TZBRB','SYS_PARAM_SMS_TOPUP','SMS_BPMTOPUP_SUCCESS',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,'Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG)VALUES ('UB','TZBRB','SYS_PARAM_SMS_TOPUP','SMS_BPMTOPUP_FAIL',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,'Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG)VALUES ('UB','TZBRB','SYS_PARAM_SMS_BPPAYEE','SMS_BP_PAYEE_ADD_SUCCESS',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,'Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG)VALUES ('UB','TZBRB','SYS_PARAM_SMS_BPPAYEE','SMS_BP_PAYEE_ADD_FAIL',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,'Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG)VALUES ('UB','TZBRB','SYS_PARAM_SMS_PAYEEEXT','SMS_PAYEE_ADDEXT_SUCCESS',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,'Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG)VALUES ('UB','TZBRB','SYS_PARAM_SMS_PAYEEEXT','SMS_PAYEE_ADDEXT_FAIL',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,'Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG)VALUES ('UB','TZBRB','SYS_PARAM_SMS_PAYEEINT','SMS_PAYEE_ADDINT_SUCCESS',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,'Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG)VALUES ('UB','TZBRB','SYS_PARAM_SMS_PAYEEINT','SMS_PAYEE_ADDINT_FAIL',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,'Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG)VALUES ('UB','TZBRB','SYS_PARAM_SMS_MW','SMS_BP_MWALLET_SUCCESS',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,'Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG)VALUES ('UB','TZBRB','SYS_PARAM_SMS_MW','SMS_BP_MWALLET_FAIL',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,'Y');

INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG)VALUES ('UB','TZBRB','SYS_PARAM_SMS_FTEXT','SMS_FTEXPAYEE_SUCCESS_PRIORITY',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,'Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG)VALUES ('UB','TZBRB','SYS_PARAM_SMS_FTEXT','SMS_FTEXPAYEE_FAIL_PRIORITY',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,'Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG)VALUES ('UB','TZBRB','SYS_PARAM_SMS_FTINT','SMS_FTINPAYEE_SUCCESS_PRIORITY',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,'Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG)VALUES ('UB','TZBRB','SYS_PARAM_SMS_FTINT','SMS_FTINPAYEE_FAIL_PRIORITY',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,'Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG)VALUES ('UB','TZBRB','SYS_PARAM_SMS_FTOWN','SMS_FTOWN_SUCCESS_PRIORITY',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,'Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG)VALUES ('UB','TZBRB','SYS_PARAM_SMS_FTOWN','SMS_FTOWN_FAIL_PRIORITY',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,'Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG)VALUES ('UB','TZBRB','SYS_PARAM_SMS_BP','SMS_BPPAYEE_SUCCESS_PRIORITY',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,'Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG)VALUES ('UB','TZBRB','SYS_PARAM_SMS_BP','SMS_BPPAYEE_FAIL_PRIORITY',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,'Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG)VALUES ('UB','TZBRB','SYS_PARAM_SMS_CHPW','SMS_CHGPWD_SUCCESS_PRIORITY',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,'Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG)VALUES ('UB','TZBRB','SYS_PARAM_SMS_BOCPIN','SMS_BOCPIN_REISSUE_PRIORITY',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,'Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG)VALUES ('UB','TZBRB','SYS_PARAM_SMS_BOCREG','SMS_BOCREG_SUCCESS_PRIORITY',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,'Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG)VALUES ('UB','TZBRB','SYS_PARAM_SMS_BOCREG','SMS_BOCREG_FAIL_PRIORITY',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,'Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG)VALUES ('UB','TZBRB','SYS_PARAM_SMS_PIN','SMS_PINISSUE_SUCCESS_PRIORITY',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,'Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG)VALUES ('UB','TZBRB','SYS_PARAM_SMS_PIN','SMS_PINISSUE_FAIL_PRIORITY',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,'Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG)VALUES ('UB','TZBRB','SYS_PARAM_SMS_TOPUP','SMS_BPMTOPUP_SUCCESS_PRIORITY',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,'Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG)VALUES ('UB','TZBRB','SYS_PARAM_SMS_TOPUP','SMS_BPMTOPUP_FAIL_PRIORITY',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,'Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG)VALUES ('UB','TZBRB','SYS_PARAM_SMS_BPPAYEE','SMS_BPPAYEEADSUCCESS_PRIORITY',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,'Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG)VALUES ('UB','TZBRB','SYS_PARAM_SMS_BPPAYEE','SMS_BPPAYEEADD_FAIL_PRIORITY',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,'Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG)VALUES ('UB','TZBRB','SYS_PARAM_SMS_PAYEEEXT','SMS_PAYEEADDEXSUCCESS_PRIORITY',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,'Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG)VALUES ('UB','TZBRB','SYS_PARAM_SMS_PAYEEEXT','SMS_PAYEEADDEXTFAIL_PRIORITY',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,'Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG)VALUES ('UB','TZBRB','SYS_PARAM_SMS_PAYEEINT','SMS_PAYEEADDINSUCCESS_PRIORITY',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,'Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG)VALUES ('UB','TZBRB','SYS_PARAM_SMS_PAYEEINT','SMS_PAYEEADDINFAIL_PRIORITY',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,'Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG)VALUES ('UB','TZBRB','SYS_PARAM_SMS_MW','SMS_BPMWALLET_SUCCESS_PRIORITY',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,'Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG)VALUES ('UB','TZBRB','SYS_PARAM_SMS_MW','SMS_BPMWALLET_FAIL_PRIORITY',NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,'Y');


COMMIT;
-----------------------------------------------------------------------

DELETE FROM C_LISTVALUE_RES_MST  WHERE SYSTEM_ID='UB' AND BUSINESS_ID='TZBRB' AND GROUP_ID='SYS_PARAM_SMS_FTEXT';
DELETE FROM C_LISTVALUE_RES_MST  WHERE SYSTEM_ID='UB' AND BUSINESS_ID='TZBRB' AND GROUP_ID='SYS_PARAM_SMS_FTINT';
DELETE FROM C_LISTVALUE_RES_MST  WHERE SYSTEM_ID='UB' AND BUSINESS_ID='TZBRB' AND GROUP_ID='SYS_PARAM_SMS_FTINT';
DELETE FROM C_LISTVALUE_RES_MST  WHERE SYSTEM_ID='UB' AND BUSINESS_ID='TZBRB' AND GROUP_ID='SYS_PARAM_SMS_BP';
DELETE FROM C_LISTVALUE_RES_MST  WHERE SYSTEM_ID='UB' AND BUSINESS_ID='TZBRB' AND GROUP_ID='SYS_PARAM_SMS_CHPW';
DELETE FROM C_LISTVALUE_RES_MST  WHERE SYSTEM_ID='UB' AND BUSINESS_ID='TZBRB' AND GROUP_ID='SYS_PARAM_SMS_BOCPIN';
DELETE FROM C_LISTVALUE_RES_MST  WHERE SYSTEM_ID='UB' AND BUSINESS_ID='TZBRB' AND GROUP_ID='SYS_PARAM_SMS_BOCREG';
DELETE FROM C_LISTVALUE_RES_MST  WHERE SYSTEM_ID='UB' AND BUSINESS_ID='TZBRB' AND GROUP_ID='SYS_PARAM_SMS_PIN';
DELETE FROM C_LISTVALUE_RES_MST  WHERE SYSTEM_ID='UB' AND BUSINESS_ID='TZBRB' AND GROUP_ID='SYS_PARAM_SMS_BPPAYEE';
DELETE FROM C_LISTVALUE_RES_MST  WHERE SYSTEM_ID='UB' AND BUSINESS_ID='TZBRB' AND GROUP_ID='SYS_PARAM_SMS_PAYEEEXT';
DELETE FROM C_LISTVALUE_RES_MST  WHERE SYSTEM_ID='UB' AND BUSINESS_ID='TZBRB' AND GROUP_ID='SYS_PARAM_SMS_PAYEEINT';
DELETE FROM C_LISTVALUE_RES_MST  WHERE SYSTEM_ID='UB' AND BUSINESS_ID='TZBRB' AND GROUP_ID='SYS_PARAM_SMS_TOPUP';

COMMIT;

Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_SMS_FTEXT','SMS_FTEXT_PAYEE_SUCCESS','EN','HM001',1);
Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_SMS_FTEXT','SMS_FTEXT_PAYEE_FAIL','EN','HM002',1);
Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_SMS_FTINT','SMS_FTINT_PAYEE_SUCCESS','EN','HM003',1);
Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_SMS_FTINT','SMS_FTINT_PAYEE_FAIL','EN','HM004',1);
Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_SMS_FTOWN','SMS_FTOWN_SUCCESS','EN','HM005',1);
Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_SMS_FTOWN','SMS_FTOWN_FAIL','EN','HM006',1);
Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_SMS_BP','SMS_BP_PAYEE_SUCCESS','EN','HM008',1);
Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_SMS_BP','SMS_BP_PAYEE_FAIL','EN','HM009',1);
Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_SMS_CHPW','SMS_CHGPWD_SUCCESS','EN','HM0010',1);
Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_SMS_BOCPIN','SMS_BOC_PIN_REISSUE','EN','HM0011',1);
Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_SMS_BOCREG','SMS_BOC_REG_SUCCESS','EN','HM0012',1);
Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_SMS_BOCREG','SMS_BOC_REG_FAIL','EN','HM0013',1);
Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_SMS_PIN','SMS_PIN_REISSUE_SUCCESS','EN','HM0014',1);
Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_SMS_PIN','SMS_PIN_REISSUE_FAIL','EN','HM0015',1);
Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_SMS_TOPUP','SMS_BPMTOPUP_SUCCESS','EN','HM0016',1);
Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_SMS_TOPUP','SMS_BPMTOPUP_FAIL','EN','HM0017',1);
Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_SMS_BPPAYEE','SMS_BP_PAYEE_ADD_SUCCESS','EN','HM0018',1);
Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_SMS_BPPAYEE','SMS_BP_PAYEE_ADD_FAIL','EN','HM0019',1);
Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_SMS_PAYEEEXT','SMS_PAYEE_ADDEXT_SUCCESS','EN','HM0020',1);
Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_SMS_PAYEEEXT','SMS_PAYEE_ADDEXT_FAIL','EN','HM0021',1);
Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_SMS_PAYEEINT','SMS_PAYEE_ADDINT_SUCCESS','EN','HM0022',1);
Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_SMS_PAYEEINT','SMS_PAYEE_ADDINT_FAIL','EN','HM0023',1);
Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_SMS_MW','SMS_BP_MWALLET_SUCCESS','EN','HM0024',1);
Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_SMS_MW','SMS_BP_MWALLET_FAIL','EN','HM0025',1);

Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_SMS_FTEXT','SMS_FTEXPAYEE_SUCCESS_PRIORITY','EN','High',1);
Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_SMS_FTEXT','SMS_FTEXPAYEE_FAIL_PRIORITY','EN','High',1);
Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_SMS_FTINT','SMS_FTINPAYEE_SUCCESS_PRIORITY','EN','High',1);
Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_SMS_FTINT','SMS_FTINPAYEE_FAIL_PRIORITY','EN','High',1);
Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_SMS_FTOWN','SMS_FTOWN_SUCCESS_PRIORITY','EN','High',1);
Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_SMS_FTOWN','SMS_FTOWN_FAIL_PRIORITY','EN','High',1);
Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_SMS_BP','SMS_BPPAYEE_SUCCESS_PRIORITY','EN','High',1);
Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_SMS_BP','SMS_BPPAYEE_FAIL_PRIORITY','EN','High',1);
Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_SMS_CHPW','SMS_CHGPWD_SUCCESS_PRIORITY','EN','High',1);
Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_SMS_BOCPIN','SMS_BOCPIN_REISSUE_PRIORITY','EN','High',1);
Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_SMS_BOCREG','SMS_BOCREG_SUCCESS_PRIORITY','EN','High',1);
Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_SMS_BOCREG','SMS_BOCREG_FAIL_PRIORITY','EN','High',1);
Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_SMS_PIN','SMS_PINISSUE_SUCCESS_PRIORITY','EN','High',1);
Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_SMS_PIN','SMS_PINISSUE_FAIL_PRIORITY','EN','Medium',1);
Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_SMS_TOPUP','SMS_BPMTOPUP_SUCCESS_PRIORITY','EN','High',1);
Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_SMS_TOPUP','SMS_BPMTOPUP_FAIL_PRIORITY','EN','Medium',1);
Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_SMS_BPPAYEE','SMS_BPPAYEEADSUCCESS_PRIORITY','EN','High',1);
Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_SMS_BPPAYEE','SMS_BPPAYEEADD_FAIL_PRIORITY','EN','Medium',1);
Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_SMS_PAYEEEXT','SMS_PAYEEADDEXSUCCESS_PRIORITY','EN','High',1);
Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_SMS_PAYEEEXT','SMS_PAYEEADDEXTFAIL_PRIORITY','EN','Medium',1);
Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_SMS_PAYEEINT','SMS_PAYEEADDINSUCCESS_PRIORITY','EN','High',1);
Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_SMS_PAYEEINT','SMS_PAYEEADDINFAIL_PRIORITY','EN','Medium',1);
Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_SMS_MW','SMS_BPMWALLET_SUCCESS_PRIORITY','EN','High',1);
Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_SMS_MW','SMS_BPMWALLET_FAIL_PRIORITY','EN','Medium',1);


COMMIT;



