drop table S_LIMIT_CUST_TOTAL_COUNT;

CREATE TABLE S_LIMIT_CUST_TOTAL_COUNT
(
  BUSINESS_ID VARCHAR2(10 BYTE) NOT NULL,
  SYSTEM_ID VARCHAR2(10 BYTE) NOT NULL,
  TXN_LIMIT_TYP VARCHAR2(20 BYTE) NOT NULL,
  CUST_ID VARCHAR2(40 BYTE) NOT NULL,
  TXN_DT TIMESTAMP(6),
  DAILY_TOTAL_AMT NUMBER(15, 3),
  TXN_COUNT NUMBER(10, 0)
, CONSTRAINT PK_S_LIMIT_CUST_TOTAL_COUNT PRIMARY KEY
  (
    BUSINESS_ID,
    SYSTEM_ID,
    TXN_LIMIT_TYP,
    CUST_ID
  )
)
PARTITION BY LIST(BUSINESS_ID)
(
  PARTITION P_GHBRB VALUES('GHBRB')
    TABLESPACE "GHBRB"
    LOGGING
    PCTFREE 10
    INITRANS 1
    MAXTRANS 255
    STORAGE
    (
      INITIAL 64K
      NEXT 64K
      MINEXTENTS 1
      MAXEXTENTS 2147483645
      PCTINCREASE 0
      BUFFER_POOL DEFAULT
    )
    NOCOMPRESS
, PARTITION P_BWBRB VALUES('BWBRB')
    TABLESPACE "BWBRB"
    LOGGING
    PCTFREE 10
    INITRANS 1
    MAXTRANS 255
    STORAGE
    (
      INITIAL 64K
      NEXT 64K
      MINEXTENTS 1
      MAXEXTENTS 2147483645
      PCTINCREASE 0
      BUFFER_POOL DEFAULT
    )
    NOCOMPRESS
, PARTITION P_MUBRB VALUES('MUBRB')
    TABLESPACE "BIRSSA"
    LOGGING
    PCTFREE 10
    INITRANS 1
    MAXTRANS 255
    STORAGE
    (
      INITIAL 64K
      NEXT 64K
      MINEXTENTS 1
      MAXEXTENTS 2147483645
      PCTINCREASE 0
      BUFFER_POOL DEFAULT
    )
    NOCOMPRESS
, PARTITION P_EGBRB VALUES('EGBRB')
    TABLESPACE "BIRSSA"
    LOGGING
    PCTFREE 10
    INITRANS 1
    MAXTRANS 255
    STORAGE
    (
      INITIAL 64K
      NEXT 64K
      MINEXTENTS 1
      MAXEXTENTS 2147483645
      PCTINCREASE 0
      BUFFER_POOL DEFAULT
    )
    NOCOMPRESS
, PARTITION P_MUBOB VALUES('MUBOB')
    TABLESPACE "BIRSSA"
    LOGGING
    PCTFREE 10
    INITRANS 1
    MAXTRANS 255
    STORAGE
    (
      INITIAL 64K
      NEXT 64K
      MINEXTENTS 1
      MAXEXTENTS 2147483645
      PCTINCREASE 0
      BUFFER_POOL DEFAULT
    )
    NOCOMPRESS
, PARTITION P_ZWBRB VALUES('ZWBRB')
    TABLESPACE "BIRSSA"
    LOGGING
    PCTFREE 10
    INITRANS 1
    MAXTRANS 255
    STORAGE
    (
      INITIAL 64K
      NEXT 64K
      MINEXTENTS 1
      MAXEXTENTS 2147483645
      PCTINCREASE 0
      BUFFER_POOL DEFAULT
    )
    NOCOMPRESS
, PARTITION P_ZMBRB VALUES('ZMBRB')
    TABLESPACE "BIRSSA"
    LOGGING
    PCTFREE 10
    INITRANS 1
    MAXTRANS 255
    STORAGE
    (
      INITIAL 64K
      NEXT 64K
      MINEXTENTS 1
      MAXEXTENTS 2147483645
      PCTINCREASE 0
      BUFFER_POOL DEFAULT
    )
    NOCOMPRESS
, PARTITION P_SCBRB VALUES('SCBRB')
    TABLESPACE "BIRSSA"
    LOGGING
    PCTFREE 10
    INITRANS 1
    MAXTRANS 255
    STORAGE
    (
      INITIAL 64K
      NEXT 64K
      MINEXTENTS 1
      MAXEXTENTS 2147483645
      PCTINCREASE 0
      BUFFER_POOL DEFAULT
    )
    NOCOMPRESS
, PARTITION P_TZBRB VALUES('TZBRB')
    TABLESPACE "BIRSSA"
    LOGGING
    PCTFREE 10
    INITRANS 1
    MAXTRANS 255
    STORAGE
    (
      INITIAL 64K
      NEXT 64K
      MINEXTENTS 1
      MAXEXTENTS 2147483645
      PCTINCREASE 0
      BUFFER_POOL DEFAULT
    )
    NOCOMPRESS
, PARTITION P_KEBRB VALUES('KEBRB')
    TABLESPACE "KEBRB"
    LOGGING
    PCTFREE 10
    INITRANS 1
    MAXTRANS 255
    STORAGE
    (
      INITIAL 64K
      MINEXTENTS 1
      MAXEXTENTS 2147483645
      BUFFER_POOL DEFAULT
    )
    NOCOMPRESS
, PARTITION P_AEBRB VALUES('AEBRB')
    TABLESPACE "AEBRB"
    LOGGING
    PCTFREE 10
    INITRANS 1
    MAXTRANS 255
    STORAGE
    (
      INITIAL 64K
      MINEXTENTS 1
      MAXEXTENTS 2147483645
      BUFFER_POOL DEFAULT
    )
    NOCOMPRESS
, PARTITION P_UGBRB VALUES('UGBRB')
    TABLESPACE "UGBRB"
    LOGGING
    PCTFREE 10
    INITRANS 1
    MAXTRANS 255
    STORAGE
    (
      INITIAL 64K
      MINEXTENTS 1
      MAXEXTENTS 2147483645
      BUFFER_POOL DEFAULT
    )
    NOCOMPRESS
, PARTITION P_MZBRB VALUES('MZBRB')
    TABLESPACE "MZBRB"
    LOGGING
    PCTFREE 10
    INITRANS 1
    MAXTRANS 255
    STORAGE
    (
      INITIAL 64K
      MINEXTENTS 1
      MAXEXTENTS 2147483645
      BUFFER_POOL DEFAULT
    )
    NOCOMPRESS
, PARTITION P_TZNBC VALUES('TZNBC')
    TABLESPACE "TZNBC"
    LOGGING
    PCTFREE 10
    INITRANS 1
    MAXTRANS 255
    STORAGE
    (
      INITIAL 64K
      MINEXTENTS 1
      MAXEXTENTS 2147483645
      BUFFER_POOL DEFAULT
    )
    NOCOMPRESS
)
;

COMMIT;