drop table S_DELIVER_TIME_RECORD_MB;

create table S_DELIVER_TIME_RECORD_MB
   ("TABLE_NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE,
	  "DELIVER_DTM" TIMESTAMP (6),
	  PRIMARY KEY ("TABLE_NAME")
   );

insert into S_DELIVER_TIME_RECORD_MB values('S_LIMIT_CUST_MST',sysdate);
insert into S_DELIVER_TIME_RECORD_MB values('C_LISTVALUE_MST',sysdate);

COMMIT;