----------TERMS_OF_USE -----------------

DROP TABLE  TERMS_OF_USE;

  CREATE TABLE TERMS_OF_USE
   (CUSTOMER_ID VARCHAR2(50 BYTE),
	SYSTEM_ID VARCHAR2(5 BYTE),
	BUSINESS_ID VARCHAR2(7 BYTE),
	ACCEPT_FLG VARCHAR2(2 BYTE),
	TOU_VERSION VARCHAR2(10 BYTE),
	ACCEPT_DATE DATE
   );

COMMIT;