-----------------------		URL INSERTION QUERY FOR MUBRB - SIT   --------------------------
DELETE FROM S_URL_BUSINESS_MAP_MST WHERE SYSTEM_ID='MB' AND BUSINESS_ID='MUBRB' AND URL_PATTERN='https://s04t.wload.global:26100/bmg';

INSERT INTO S_URL_BUSINESS_MAP_MST (SYSTEM_ID, BUSINESS_ID, URL_PATTERN, LANGUAGE_ID) VALUES ('MB','MUBRB','https://s04t.wload.global:26100/bmg','EN');
COMMIT;