UPDATE S_SYSPARAM_MST SET PARAM_VALUE = (SELECT PARAM_VALUE FROM S_SYSPARAM_MST WHERE SYSTEM_ID='IB'  AND PARAM_ID='BUSINESS_DATE' AND BUSINESS_ID='EGBRB')  WHERE SYSTEM_ID='MB'  AND PARAM_ID='BUSINESS_DATE' AND BUSINESS_ID='EGBRB';

UPDATE S_SYSPARAM_MST SET PARAM_VALUE = (SELECT PARAM_VALUE FROM S_SYSPARAM_MST WHERE SYSTEM_ID='IB'  AND PARAM_ID='BUSINESS_DATE' AND BUSINESS_ID='KEBRB')  WHERE SYSTEM_ID='MB'  AND PARAM_ID='BUSINESS_DATE' AND BUSINESS_ID='KEBRB';
