

-- DELETING from C_LISTVALUE_MST
delete from C_LISTVALUE_MST where SYSTEM_ID = 'MB' and BUSINESS_ID = 'MUBRB' and GROUP_ID = 'BP_FACADE_DEST' and LIST_VALUE_KEY = 'BCD';

-- DELETING from C_LISTVALUE_RES_MST
delete from C_LISTVALUE_RES_MST where SYSTEM_ID = 'MB' and BUSINESS_ID = 'MUBRB' and GROUP_ID = 'BP_FACADE_DEST' and LIST_VALUE_KEY = 'BCD';

-- INSERTING into C_LISTVALUE_RES_MST
Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('MB','MUBRB','BP_FACADE_DEST','BCD','EN','BarclaysCard',2);
-- INSERTING into C_LISTVALUE_MST
Insert into C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('MB','MUBRB','BP_FACADE_DEST','BCD',null,null,'N',null,null,null,null,null,null);

commit;