
-----------------------		URL INSERTION QUERY FOR ZMBRB - SIT   --------------------------

DELETE FROM S_URL_BUSINESS_MAP_MST WHERE SYSTEM_ID='MB' AND BUSINESS_ID='ZMBRB' AND URL_PATTERN='https://s04t.wload.global:31100/bmg';

INSERT INTO S_URL_BUSINESS_MAP_MST (SYSTEM_ID, BUSINESS_ID, URL_PATTERN, LANGUAGE_ID) VALUES ('MB','ZMBRB','https://s04t.wload.global:31100/bmg','EN');
COMMIT;
