
-----------------------		URL INSERTION QUERY FOR KEBRB - SIT   --------------------------
DELETE FROM S_URL_BUSINESS_MAP_MST WHERE SYSTEM_ID='MB' AND BUSINESS_ID='KEBRB' AND URL_PATTERN='https://widd.wload.global:52259/bmg';

INSERT INTO S_URL_BUSINESS_MAP_MST (SYSTEM_ID, BUSINESS_ID, URL_PATTERN, LANGUAGE_ID, SEGMENT_ID) VALUES ('MB','KEBRB','https://widd.wload.global:52259/bmg','EN','MASS');
COMMIT;