DELETE FROM C_LISTVALUE_MST where BUSINESS_ID='TZBRB' and SYSTEM_ID='UB' AND GROUP_ID='CURR_SUPPORT_OWN_ACC';
INSERT into C_LISTVALUE_MST (SYSTEM_ID, BUSINESS_ID, GROUP_ID, LIST_VALUE_KEY, FILTER_KEY_1, FILTER_KEY_2, DEFAULT_FLG, MODIFIED_BY, MODIFIED_DTM, AUTHORIZED_BY, AUTHORIZED_DTM, DELETE_FLG, EDITABLE_FLG) values ('UB', 'TZBRB', 'CURR_SUPPORT_OWN_ACC', 'FCY1FCY2', null, null, 'N', null, null, null, null, 'N', 'Y');
INSERT into C_LISTVALUE_MST (SYSTEM_ID, BUSINESS_ID, GROUP_ID, LIST_VALUE_KEY, FILTER_KEY_1, FILTER_KEY_2, DEFAULT_FLG, MODIFIED_BY, MODIFIED_DTM, AUTHORIZED_BY, AUTHORIZED_DTM, DELETE_FLG, EDITABLE_FLG) values ('UB', 'TZBRB', 'CURR_SUPPORT_OWN_ACC', 'FCYFCY', null, null, 'N', null, null, null, null, 'N', 'Y');
INSERT into C_LISTVALUE_MST (SYSTEM_ID, BUSINESS_ID, GROUP_ID, LIST_VALUE_KEY, FILTER_KEY_1, FILTER_KEY_2, DEFAULT_FLG, MODIFIED_BY, MODIFIED_DTM, AUTHORIZED_BY, AUTHORIZED_DTM, DELETE_FLG, EDITABLE_FLG) values ('UB', 'TZBRB', 'CURR_SUPPORT_OWN_ACC', 'FCYLCY', null, null, 'N', null, null, null, null, 'N', 'Y');
INSERT into C_LISTVALUE_MST (SYSTEM_ID, BUSINESS_ID, GROUP_ID, LIST_VALUE_KEY, FILTER_KEY_1, FILTER_KEY_2, DEFAULT_FLG, MODIFIED_BY, MODIFIED_DTM, AUTHORIZED_BY, AUTHORIZED_DTM, DELETE_FLG, EDITABLE_FLG) values ('UB', 'TZBRB', 'CURR_SUPPORT_OWN_ACC', 'LCYFCY', null, null, 'N', null, null, null, null, 'N', 'Y');
INSERT into C_LISTVALUE_MST (SYSTEM_ID, BUSINESS_ID, GROUP_ID, LIST_VALUE_KEY, FILTER_KEY_1, FILTER_KEY_2, DEFAULT_FLG, MODIFIED_BY, MODIFIED_DTM, AUTHORIZED_BY, AUTHORIZED_DTM, DELETE_FLG, EDITABLE_FLG) values ('UB', 'TZBRB', 'CURR_SUPPORT_OWN_ACC', 'LCYLCY', null, null, 'Y', null, null, null, null, 'N', 'Y');

DELETE FROM C_LISTVALUE_RES_MST where BUSINESS_ID='TZBRB' and SYSTEM_ID='UB' AND GROUP_ID='CURR_SUPPORT_OWN_ACC';
INSERT into C_LISTVALUE_RES_MST (SYSTEM_ID, BUSINESS_ID, GROUP_ID, LIST_VALUE_KEY, LANGUAGE_ID, VALUE, LIST_VALUE_ORDER) values ('UB', 'TZBRB', 'CURR_SUPPORT_OWN_ACC', 'FCY1FCY2', 'EN', 'N', 5);
INSERT into C_LISTVALUE_RES_MST (SYSTEM_ID, BUSINESS_ID, GROUP_ID, LIST_VALUE_KEY, LANGUAGE_ID, VALUE, LIST_VALUE_ORDER) values ('UB', 'TZBRB', 'CURR_SUPPORT_OWN_ACC', 'FCYFCY', 'EN', 'N', 2);
INSERT into C_LISTVALUE_RES_MST (SYSTEM_ID, BUSINESS_ID, GROUP_ID, LIST_VALUE_KEY, LANGUAGE_ID, VALUE, LIST_VALUE_ORDER) values ('UB', 'TZBRB', 'CURR_SUPPORT_OWN_ACC', 'FCYLCY', 'EN', 'N', 4);
INSERT into C_LISTVALUE_RES_MST (SYSTEM_ID, BUSINESS_ID, GROUP_ID, LIST_VALUE_KEY, LANGUAGE_ID, VALUE, LIST_VALUE_ORDER) values ('UB', 'TZBRB', 'CURR_SUPPORT_OWN_ACC', 'LCYFCY', 'EN', 'N', 3);
INSERT into C_LISTVALUE_RES_MST (SYSTEM_ID, BUSINESS_ID, GROUP_ID, LIST_VALUE_KEY, LANGUAGE_ID, VALUE, LIST_VALUE_ORDER) values ('UB', 'TZBRB', 'CURR_SUPPORT_OWN_ACC', 'LCYLCY', 'EN', 'Y', 1);



DELETE FROM C_LISTVALUE_MST where BUSINESS_ID='TZBRB' and SYSTEM_ID='UB' AND GROUP_ID='CURR_SUPPORT_INT_ACC';
INSERT into C_LISTVALUE_MST (SYSTEM_ID, BUSINESS_ID, GROUP_ID, LIST_VALUE_KEY, FILTER_KEY_1, FILTER_KEY_2, DEFAULT_FLG, MODIFIED_BY, MODIFIED_DTM, AUTHORIZED_BY, AUTHORIZED_DTM, DELETE_FLG, EDITABLE_FLG) values ('UB', 'TZBRB', 'CURR_SUPPORT_INT_ACC', 'FCY1FCY2', null, null, 'N', null, null, null, null, 'N', 'Y');
INSERT into C_LISTVALUE_MST (SYSTEM_ID, BUSINESS_ID, GROUP_ID, LIST_VALUE_KEY, FILTER_KEY_1, FILTER_KEY_2, DEFAULT_FLG, MODIFIED_BY, MODIFIED_DTM, AUTHORIZED_BY, AUTHORIZED_DTM, DELETE_FLG, EDITABLE_FLG) values ('UB', 'TZBRB', 'CURR_SUPPORT_INT_ACC', 'FCYFCY', null, null, 'N', null, null, null, null, 'N', 'Y');
INSERT into C_LISTVALUE_MST (SYSTEM_ID, BUSINESS_ID, GROUP_ID, LIST_VALUE_KEY, FILTER_KEY_1, FILTER_KEY_2, DEFAULT_FLG, MODIFIED_BY, MODIFIED_DTM, AUTHORIZED_BY, AUTHORIZED_DTM, DELETE_FLG, EDITABLE_FLG) values ('UB', 'TZBRB', 'CURR_SUPPORT_INT_ACC', 'FCYLCY', null, null, 'N', null, null, null, null, 'N', 'Y');
INSERT into C_LISTVALUE_MST (SYSTEM_ID, BUSINESS_ID, GROUP_ID, LIST_VALUE_KEY, FILTER_KEY_1, FILTER_KEY_2, DEFAULT_FLG, MODIFIED_BY, MODIFIED_DTM, AUTHORIZED_BY, AUTHORIZED_DTM, DELETE_FLG, EDITABLE_FLG) values ('UB', 'TZBRB', 'CURR_SUPPORT_INT_ACC', 'LCYFCY', null, null, 'N', null, null, null, null, 'N', 'Y');
INSERT into C_LISTVALUE_MST (SYSTEM_ID, BUSINESS_ID, GROUP_ID, LIST_VALUE_KEY, FILTER_KEY_1, FILTER_KEY_2, DEFAULT_FLG, MODIFIED_BY, MODIFIED_DTM, AUTHORIZED_BY, AUTHORIZED_DTM, DELETE_FLG, EDITABLE_FLG) values ('UB', 'TZBRB', 'CURR_SUPPORT_INT_ACC', 'LCYLCY', null, null, 'Y', null, null, null, null, 'N', 'Y');



DELETE FROM C_LISTVALUE_RES_MST where BUSINESS_ID='TZBRB' and SYSTEM_ID='UB' AND GROUP_ID='CURR_SUPPORT_INT_ACC';
INSERT into C_LISTVALUE_RES_MST (SYSTEM_ID, BUSINESS_ID, GROUP_ID, LIST_VALUE_KEY, LANGUAGE_ID, VALUE, LIST_VALUE_ORDER) values ('UB', 'TZBRB', 'CURR_SUPPORT_INT_ACC', 'FCY1FCY2', 'EN', 'N', 5);
INSERT into C_LISTVALUE_RES_MST (SYSTEM_ID, BUSINESS_ID, GROUP_ID, LIST_VALUE_KEY, LANGUAGE_ID, VALUE, LIST_VALUE_ORDER) values ('UB', 'TZBRB', 'CURR_SUPPORT_INT_ACC', 'FCYFCY', 'EN', 'N', 2);
INSERT into C_LISTVALUE_RES_MST (SYSTEM_ID, BUSINESS_ID, GROUP_ID, LIST_VALUE_KEY, LANGUAGE_ID, VALUE, LIST_VALUE_ORDER) values ('UB', 'TZBRB', 'CURR_SUPPORT_INT_ACC', 'FCYLCY', 'EN', 'N', 4);
INSERT into C_LISTVALUE_RES_MST (SYSTEM_ID, BUSINESS_ID, GROUP_ID, LIST_VALUE_KEY, LANGUAGE_ID, VALUE, LIST_VALUE_ORDER) values ('UB', 'TZBRB', 'CURR_SUPPORT_INT_ACC', 'LCYFCY', 'EN', 'N', 3);
INSERT into C_LISTVALUE_RES_MST (SYSTEM_ID, BUSINESS_ID, GROUP_ID, LIST_VALUE_KEY, LANGUAGE_ID, VALUE, LIST_VALUE_ORDER) values ('UB', 'TZBRB', 'CURR_SUPPORT_INT_ACC', 'LCYLCY', 'EN', 'Y', 1);


DELETE FROM C_LISTVALUE_MST where BUSINESS_ID='TZBRB' and SYSTEM_ID='UB' AND GROUP_ID='CURR_SUPPORT_EXT_ACC';
INSERT into C_LISTVALUE_MST (SYSTEM_ID, BUSINESS_ID, GROUP_ID, LIST_VALUE_KEY, FILTER_KEY_1, FILTER_KEY_2, DEFAULT_FLG, MODIFIED_BY, MODIFIED_DTM, AUTHORIZED_BY, AUTHORIZED_DTM, DELETE_FLG, EDITABLE_FLG) values ('UB', 'TZBRB', 'CURR_SUPPORT_EXT_ACC', 'FCY1FCY2', null, null, 'N', null, null, null, null, 'N', 'Y');
INSERT into C_LISTVALUE_MST (SYSTEM_ID, BUSINESS_ID, GROUP_ID, LIST_VALUE_KEY, FILTER_KEY_1, FILTER_KEY_2, DEFAULT_FLG, MODIFIED_BY, MODIFIED_DTM, AUTHORIZED_BY, AUTHORIZED_DTM, DELETE_FLG, EDITABLE_FLG) values ('UB', 'TZBRB', 'CURR_SUPPORT_EXT_ACC', 'FCYFCY', null, null, 'N', null, null, null, null, 'N', 'Y');
INSERT into C_LISTVALUE_MST (SYSTEM_ID, BUSINESS_ID, GROUP_ID, LIST_VALUE_KEY, FILTER_KEY_1, FILTER_KEY_2, DEFAULT_FLG, MODIFIED_BY, MODIFIED_DTM, AUTHORIZED_BY, AUTHORIZED_DTM, DELETE_FLG, EDITABLE_FLG) values ('UB', 'TZBRB', 'CURR_SUPPORT_EXT_ACC', 'FCYLCY', null, null, 'N', null, null, null, null, 'N', 'Y');
INSERT into C_LISTVALUE_MST (SYSTEM_ID, BUSINESS_ID, GROUP_ID, LIST_VALUE_KEY, FILTER_KEY_1, FILTER_KEY_2, DEFAULT_FLG, MODIFIED_BY, MODIFIED_DTM, AUTHORIZED_BY, AUTHORIZED_DTM, DELETE_FLG, EDITABLE_FLG) values ('UB', 'TZBRB', 'CURR_SUPPORT_EXT_ACC', 'LCYFCY', null, null, 'N', null, null, null, null, 'N', 'Y');
INSERT into C_LISTVALUE_MST (SYSTEM_ID, BUSINESS_ID, GROUP_ID, LIST_VALUE_KEY, FILTER_KEY_1, FILTER_KEY_2, DEFAULT_FLG, MODIFIED_BY, MODIFIED_DTM, AUTHORIZED_BY, AUTHORIZED_DTM, DELETE_FLG, EDITABLE_FLG) values ('UB', 'TZBRB', 'CURR_SUPPORT_EXT_ACC', 'LCYLCY', null, null, 'Y', null, null, null, null, 'N', 'Y');



DELETE FROM C_LISTVALUE_RES_MST where BUSINESS_ID='TZBRB' and SYSTEM_ID='UB' AND GROUP_ID='CURR_SUPPORT_EXT_ACC';
INSERT into C_LISTVALUE_RES_MST (SYSTEM_ID, BUSINESS_ID, GROUP_ID, LIST_VALUE_KEY, LANGUAGE_ID, VALUE, LIST_VALUE_ORDER) values ('UB', 'TZBRB', 'CURR_SUPPORT_EXT_ACC', 'FCY1FCY2', 'EN', 'N', 5);
INSERT into C_LISTVALUE_RES_MST (SYSTEM_ID, BUSINESS_ID, GROUP_ID, LIST_VALUE_KEY, LANGUAGE_ID, VALUE, LIST_VALUE_ORDER) values ('UB', 'TZBRB', 'CURR_SUPPORT_EXT_ACC', 'FCYFCY', 'EN', 'N', 2);
INSERT into C_LISTVALUE_RES_MST (SYSTEM_ID, BUSINESS_ID, GROUP_ID, LIST_VALUE_KEY, LANGUAGE_ID, VALUE, LIST_VALUE_ORDER) values ('UB', 'TZBRB', 'CURR_SUPPORT_EXT_ACC', 'FCYLCY', 'EN', 'N', 4);
INSERT into C_LISTVALUE_RES_MST (SYSTEM_ID, BUSINESS_ID, GROUP_ID, LIST_VALUE_KEY, LANGUAGE_ID, VALUE, LIST_VALUE_ORDER) values ('UB', 'TZBRB', 'CURR_SUPPORT_EXT_ACC', 'LCYFCY', 'EN', 'N', 3);
INSERT into C_LISTVALUE_RES_MST (SYSTEM_ID, BUSINESS_ID, GROUP_ID, LIST_VALUE_KEY, LANGUAGE_ID, VALUE, LIST_VALUE_ORDER) values ('UB', 'TZBRB', 'CURR_SUPPORT_EXT_ACC', 'LCYLCY', 'EN', 'Y', 1);


DELETE FROM C_LISTVALUE_MST where BUSINESS_ID='TZBRB' and SYSTEM_ID='UB' AND GROUP_ID='CURR_SUPPORT_INTL_ACC';
INSERT into C_LISTVALUE_MST (SYSTEM_ID, BUSINESS_ID, GROUP_ID, LIST_VALUE_KEY, FILTER_KEY_1, FILTER_KEY_2, DEFAULT_FLG, MODIFIED_BY, MODIFIED_DTM, AUTHORIZED_BY, AUTHORIZED_DTM, DELETE_FLG, EDITABLE_FLG) values ('UB', 'TZBRB', 'CURR_SUPPORT_INTL_ACC', 'FCY1FCY2', null, null, 'N', null, null, null, null, 'N', 'Y');
INSERT into C_LISTVALUE_MST (SYSTEM_ID, BUSINESS_ID, GROUP_ID, LIST_VALUE_KEY, FILTER_KEY_1, FILTER_KEY_2, DEFAULT_FLG, MODIFIED_BY, MODIFIED_DTM, AUTHORIZED_BY, AUTHORIZED_DTM, DELETE_FLG, EDITABLE_FLG) values ('UB', 'TZBRB', 'CURR_SUPPORT_INTL_ACC', 'FCYFCY', null, null, 'N', null, null, null, null, 'N', 'Y');
INSERT into C_LISTVALUE_MST (SYSTEM_ID, BUSINESS_ID, GROUP_ID, LIST_VALUE_KEY, FILTER_KEY_1, FILTER_KEY_2, DEFAULT_FLG, MODIFIED_BY, MODIFIED_DTM, AUTHORIZED_BY, AUTHORIZED_DTM, DELETE_FLG, EDITABLE_FLG) values ('UB', 'TZBRB', 'CURR_SUPPORT_INTL_ACC', 'FCYLCY', null, null, 'N', null, null, null, null, 'N', 'Y');
INSERT into C_LISTVALUE_MST (SYSTEM_ID, BUSINESS_ID, GROUP_ID, LIST_VALUE_KEY, FILTER_KEY_1, FILTER_KEY_2, DEFAULT_FLG, MODIFIED_BY, MODIFIED_DTM, AUTHORIZED_BY, AUTHORIZED_DTM, DELETE_FLG, EDITABLE_FLG) values ('UB', 'TZBRB', 'CURR_SUPPORT_INTL_ACC', 'LCYFCY', null, null, 'Y', null, null, null, null, 'N', 'Y');
INSERT into C_LISTVALUE_MST (SYSTEM_ID, BUSINESS_ID, GROUP_ID, LIST_VALUE_KEY, FILTER_KEY_1, FILTER_KEY_2, DEFAULT_FLG, MODIFIED_BY, MODIFIED_DTM, AUTHORIZED_BY, AUTHORIZED_DTM, DELETE_FLG, EDITABLE_FLG) values ('UB', 'TZBRB', 'CURR_SUPPORT_INTL_ACC', 'LCYLCY', null, null, 'N', null, null, null, null, 'N', 'Y');





DELETE FROM C_LISTVALUE_RES_MST where BUSINESS_ID='TZBRB' and SYSTEM_ID='UB' AND GROUP_ID='CURR_SUPPORT_INTL_ACC';

INSERT into C_LISTVALUE_RES_MST (SYSTEM_ID, BUSINESS_ID, GROUP_ID, LIST_VALUE_KEY, LANGUAGE_ID, VALUE, LIST_VALUE_ORDER) values ('UB', 'TZBRB', 'CURR_SUPPORT_INTL_ACC', 'FCY1FCY2', 'EN', 'N', 5);
INSERT into C_LISTVALUE_RES_MST (SYSTEM_ID, BUSINESS_ID, GROUP_ID, LIST_VALUE_KEY, LANGUAGE_ID, VALUE, LIST_VALUE_ORDER) values ('UB', 'TZBRB', 'CURR_SUPPORT_INTL_ACC', 'FCYFCY', 'EN', 'N', 2);
INSERT into C_LISTVALUE_RES_MST (SYSTEM_ID, BUSINESS_ID, GROUP_ID, LIST_VALUE_KEY, LANGUAGE_ID, VALUE, LIST_VALUE_ORDER) values ('UB', 'TZBRB', 'CURR_SUPPORT_INTL_ACC', 'FCYLCY', 'EN', 'N', 4);
INSERT into C_LISTVALUE_RES_MST (SYSTEM_ID, BUSINESS_ID, GROUP_ID, LIST_VALUE_KEY, LANGUAGE_ID, VALUE, LIST_VALUE_ORDER) values ('UB', 'TZBRB', 'CURR_SUPPORT_INTL_ACC', 'LCYFCY', 'EN', 'Y', 3);
INSERT into C_LISTVALUE_RES_MST (SYSTEM_ID, BUSINESS_ID, GROUP_ID, LIST_VALUE_KEY, LANGUAGE_ID, VALUE, LIST_VALUE_ORDER) values ('UB', 'TZBRB', 'CURR_SUPPORT_INTL_ACC', 'LCYLCY', 'EN', 'N', 1);


COMMIT;