---------------  C_BIZ_FUNC_MMAP  ------

	DELETE  FROM C_BIZ_FUNC_MMAP where BUSINESS_ID='KEBRB' and SYSTEM_ID='UB';

	INSERT INTO  C_BIZ_FUNC_MMAP (SELECT BUSINESS_ID, ACTIVITY_ID, 'UB', FROM_TIME,  TO_TIME, HOLIDAY_ALLOWED_FLG,  BLOCKED_FLG   FROM C_BIZ_FUNC_MMAP   WHERE SYSTEM_ID = 'MB' AND BUSINESS_ID = 'KEBRB');

	DELETE FROM C_BIZ_FUNC_MMAP where BUSINESS_ID='KEBRB' and SYSTEM_ID='UB' AND ACTIVITY_ID='PMT_FT_MRC_PAYEE';

	INSERT INTO C_BIZ_FUNC_MMAP (BUSINESS_ID,ACTIVITY_ID,SYSTEM_ID,FROM_TIME,TO_TIME,HOLIDAY_ALLOWED_FLG,BLOCKED_FLG) values ('KEBRB','PMT_FT_MRC_PAYEE','UB',null,null,'N','N');

	DELETE FROM C_BIZ_FUNC_MMAP where BUSINESS_ID='KEBRB' and SYSTEM_ID='UB' AND ACTIVITY_ID='PMT_FT_BKD_PAYEE';

	INSERT INTO C_BIZ_FUNC_MMAP (BUSINESS_ID,ACTIVITY_ID,SYSTEM_ID,FROM_TIME,TO_TIME,HOLIDAY_ALLOWED_FLG,BLOCKED_FLG) values ('KEBRB','PMT_FT_BKD_PAYEE','UB',null,null,'N','N');

---------------- C_LISTVALUE_MST ----------

	DELETE  FROM C_LISTVALUE_MST where BUSINESS_ID='KEBRB' and SYSTEM_ID='UB';

	INSERT INTO  C_LISTVALUE_MST (SELECT 'UB',BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG, EDITABLE_FLG  FROM C_LISTVALUE_MST  WHERE SYSTEM_ID = 'MB'  AND  BUSINESS_ID='KEBRB');

---------------- C_LISTVALUE_RES_MST ----------

	DELETE  FROM C_LISTVALUE_RES_MST where BUSINESS_ID='KEBRB' and SYSTEM_ID='UB';

	INSERT INTO  C_LISTVALUE_RES_MST (SELECT 'UB',BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER  FROM C_LISTVALUE_RES_MST  WHERE SYSTEM_ID = 'MB'  AND  BUSINESS_ID='KEBRB');

--------------- INSERTING into C_LISTVALUE_MST - for 'FT_DELIVERY_TYPE'
	DELETE FROM C_LISTVALUE_MST where SYSTEM_ID='UB' and GROUP_ID='FT_DELIVERY_TYPE'  AND BUSINESS_ID='KEBRB';

	INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('UB','KEBRB','FT_DELIVERY_TYPE','BEN',null,null,'N',null,null,null,null,'N','Y');
	INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('UB','KEBRB','FT_DELIVERY_TYPE','BRN',null,null,'N',null,null,null,null,'N','Y');
	INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('UB','KEBRB','FT_DELIVERY_TYPE','REM',null,null,'N',null,null,null,null,'N','Y');


-------------- INSERTING into C_LISTVALUE_RES_MST - for 'FT_DELIVERY_TYPE'
	DELETE FROM C_LISTVALUE_RES_MST where SYSTEM_ID='UB' and GROUP_ID='FT_DELIVERY_TYPE' AND BUSINESS_ID='KEBRB';

	INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','KEBRB','FT_DELIVERY_TYPE','REM','EN','Mail to Remitter',0);
	INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','KEBRB','FT_DELIVERY_TYPE','BEN','EN','Mail to Beneficiary',2);
	INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','KEBRB','FT_DELIVERY_TYPE','BRN','EN','Collect at Branch',4);

-------------- INSERTING into C_LISTVALUE_MST - for 'FT_DRAFT_TYPE'
	DELETE FROM C_LISTVALUE_MST where SYSTEM_ID='UB' and GROUP_ID='FT_DRAFT_TYPE'  AND BUSINESS_ID='KEBRB';

	INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('UB','KEBRB','FT_DRAFT_TYPE','BD',null,null,'N',null,null,null,null,'N','Y');
	INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('UB','KEBRB','FT_DRAFT_TYPE','MC',null,null,'N',null,null,null,null,'N','Y');

-------------- INSERTING into C_LISTVALUE_RES_MST - for 'FT_DRAFT_TYPE'
	DELETE FROM C_LISTVALUE_RES_MST where SYSTEM_ID='UB' and GROUP_ID='FT_DRAFT_TYPE'  AND BUSINESS_ID='KEBRB';

	INSERT INTO	C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','KEBRB','FT_DRAFT_TYPE','BD','EN','Bank Draft',1);
	INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','KEBRB','FT_DRAFT_TYPE','MC','EN','Manager''s Cheque',2);

------------- INSERTING into C_LISTVALUE_GROUP_MST
	DELETE FROM C_LISTVALUE_GROUP_MST where GROUP_ID='SYS_PARAM_CS';

	INSERT INTO C_LISTVALUE_GROUP_MST (GROUP_ID,DESCRIPTION,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,SOURCE_SYSTEM_ID,EDITABLE_FLG,CREATED_BY,CREATED_DTM) VALUES ('SYS_PARAM_CS','Cash Send System Params','E20042298',sysdate,'E20042298',sysdate,'N','MCFE','Y',null,null);

---------------  C_COMPONENT_MST ----------------

	DELETE  FROM C_COMPONENT_MST where business_id='KEBRB' and system_id='UB';

	INSERT INTO  C_COMPONENT_MST (SELECT SCREEN_ID,'UB',BUSINESS_ID,COMPONENT_KEY,RENDERED_FLG,REQUIRED_FLG,HAS_HELP_TEXT_FLG,FORMATTER_ID,LISTVALUE_GROUP_ID,DEFAULT_VALUE,DISP_ORDER,PARENT_COMPONENT_KEY,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,CONFIG_FLG,COMPONENT_TYPE,READONLY_FLG  FROM C_COMPONENT_MST  WHERE SYSTEM_ID = 'MB'  AND  BUSINESS_ID='KEBRB');

---------------  C_COMPONENT_RES_MST --------------

	DELETE  FROM C_COMPONENT_RES_MST where business_id='KEBRB' and system_id='UB';

	INSERT INTO  C_COMPONENT_RES_MST (SELECT LANGUAGE_ID,LABEL_VALUE,TOOL_TIP,HELP_TEXT,LENGTH,SCREEN_ID,'UB',BUSINESS_ID,COMPONENT_KEY  FROM C_COMPONENT_RES_MST  WHERE SYSTEM_ID = 'MB'  AND  BUSINESS_ID='KEBRB');

---------------- S_FUNCTION_CONFIG -----------------

	DELETE  FROM S_FUNCTION_CONFIG where business_id='KEBRB' and system_id='UB';

	INSERT INTO  S_FUNCTION_CONFIG(SELECT BUSINESS_ID,'UB',ACTIVITY_ID,TXN_LIMIT_TYP,FEATURE_BLKOUT_FLG,ADV_TXT_FLG,ADV_IMG_TOP_FLG,ADV_IMG_RIGHTNAV_FLG,MODIFIED_DTM,MODIFIED_BY  FROM S_FUNCTION_CONFIG  WHERE SYSTEM_ID = 'MB'  AND  BUSINESS_ID='KEBRB');


------------ C_FUNCTION_MST --------

	DELETE  FROM C_FUNCTION_MST  WHERE SYSTEM_ID='UB';

	INSERT INTO C_FUNCTION_MST (SELECT ACTIVITY_ID, 'UB',FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC  FROM C_FUNCTION_MST  WHERE SYSTEM_ID = 'MB');


-- INSERTING into C_FUNCTION_MST

DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='ACT_ACCOUNTSERVICE_ACCOUNTSUMMARY' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='ACT_ACCOUNTSERVICE_ESAVER' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='CRD_PIN' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='CRD_REPLACE_CARD' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='CRD_REPORTLOST' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='CRD_SETUP_DD' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='CRD_VIEW_DD' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='CREATE_ACC_NICK_NAME' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='CREDITCARD_APP' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='CREDIT_CARD_DETAIL' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='CREDIT_SUMMARY' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='CUS_ACTIVITY_LOG' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='CUS_ALERT_ALERTMANAGEMENT' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='CUS_CHK_APPLN_STATUS' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='CUS_EMESSAGE' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='CUS_EMESSAGE_CASA' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='CUS_EMESSAGE_CREDITCARD' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='CUS_EMESSAGE_FUNDTRANSFER' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='CUS_EMESSAGE_INTRATE' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='CUS_EMESSAGE_LOAN' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='CUS_EMESSAGE_TD' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='CUS_ESTMT' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='CUS_FXRATES' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='CUS_FX_RATES' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='CUS_FX_RATES_CUS' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='CUS_FX_RATES_FUNDTRANSFER' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='CUS_FX_RATES_TD' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='CUS_INT_RATES' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='CUS_INT_RATES_CASA' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='CUS_INT_RATES_CUS' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='CUS_INT_RATES_TD' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='CUS_LINK_ACCOUNT' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='CUS_MANAGE_ALERTS' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='CUS_ORDER_PAPER_STMT' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='CUS_ORDER_PAPER_STMT_CASA' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='CUS_PROFILE_PREFERENCE' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='CUS_PROFILE_UPD_CONTACT_INFO' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='CUS_REQ_BRANCH_LETTER' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='CUS_REQ_LIABILITY_LETTER' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='CUS_SITEMAP' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='ESPECIALLY_FOR_YOU_OFFER' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='ESPECIALLY_FOR_YOU_WIDGET' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_FT_BKD_ONETIME' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_FT_BKD_PAYEE' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_FT_CARD_PAYMENT_ONETIME' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_FT_CARD_PAYMENT_PAYEE' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_FT_CARD_PAYMENT_SI_ONETIME' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_FT_CARD_PAYMENT_SI_PAYEE' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_FT_EFT_ONETIME' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_FT_EFT_PAYEE' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_FT_EXTERNAL_ONETIME' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_FT_EXTERNAL_PAYEE' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_FT_FACADE' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_FT_FACADE_CASA' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_FT_FACADE_CREDITCARD' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_FT_INTERNAL_ONETIME' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_FT_INTERNAL_PAYEE' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_FT_INTL_DT_ONETIME' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_FT_INTL_DT_PAYEE' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_FT_INTL_ONETIME' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_FT_INTL_PAYEE' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_FT_LOAN' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_FT_LOAN_INPUT_ONETIME' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_FT_LOAN_PAYMENT' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_FT_LOAN_REPAYMENT' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_FT_MRC_FACADE' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_FT_MRC_ONETIME' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_FT_MRC_PAYEE' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_FT_OWN' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_FT_RTGS_ONETIME' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_FT_RTGS_PAYEE' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_FT_SI_EXTERNAL_ONETIME' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_FT_SI_EXTERNAL_PAYEE' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_FT_SI_INTERNAL_ONETIME' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_FT_SI_INTERNAL_PAYEE' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_FT_SI_INTL_DT_ONETIME' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_FT_SI_INTL_DT_PAYEE' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_FT_SI_INTL_ONETIME' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_FT_SI_INTL_PAYEE' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_FT_SI_OWN' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_FT_SWIFT_LOOKUP' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_FX_RATE' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_PAYEE_ACTIVATE_BCD' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_PAYEE_ACTIVATE_BKD' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_PAYEE_ACTIVATE_BP' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_PAYEE_ACTIVATE_EFT' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_PAYEE_ACTIVATE_EXTERNAL' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_PAYEE_ACTIVATE_INTERNAL' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_PAYEE_ACTIVATE_INTL' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_PAYEE_ACTIVATE_INTL_DT' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_PAYEE_ACTIVATE_LN' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_PAYEE_ACTIVATE_MRC' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_PAYEE_ACTIVATE_MTP' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_PAYEE_ACTIVATE_RTGS' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_PAYEE_ADD' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_PAYEE_ADD_BCD' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_PAYEE_ADD_BKD' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_PAYEE_ADD_BP' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_PAYEE_ADD_EFT' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_PAYEE_ADD_EXTERNAL' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_PAYEE_ADD_INTERNAL' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_PAYEE_ADD_INTL' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_PAYEE_ADD_INTL_DT' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_PAYEE_ADD_LN' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_PAYEE_ADD_MRC' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_PAYEE_ADD_MTP' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_PAYEE_ADD_RTGS' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_PAYEE_DELETE_BCD' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_PAYEE_DELETE_BKD' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_PAYEE_DELETE_BP' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_PAYEE_DELETE_EFT' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_PAYEE_DELETE_EXTERNAL' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_PAYEE_DELETE_INTERNAL' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_PAYEE_DELETE_INTL' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_PAYEE_DELETE_INTL_DT' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_PAYEE_DELETE_LN' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_PAYEE_DELETE_MRC' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_PAYEE_DELETE_MTP' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_PAYEE_DELETE_RTGS' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_PAYEE_LIST' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_SI_CANCEL' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_SI_DETAIL' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_SI_LIST' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_SI_UPDATE' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='POT_SITEMAP' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='REWARDS_INQUIRY' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='REWARDS_REDEM_HISTORY' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='SEC_CHG_PWD' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='SEC_CHG_SQA' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='SEC_COMMON' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='SEC_FORGOT_PWD' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='SEC_FORGOT_SQA' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='SEC_FORGOT_UNAME' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='SEC_LOGIN' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='SEC_LOGOUT' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='SEC_ONLN_REG' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='SEC_PREONLN_REG' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='TD_DETAIL' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='TD_SUMMARY' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='TXN_HISTORY' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='UNBILLED_TXN' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='UNIFY_COMMUNICATION' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='UPDATE_LANGUAGE_PREF' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='VIEW_BULLETIN' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='GET_ACC_NICK_NAME' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='LOAN_DETAIL' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='LOAN_REPAYMENT' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='LOAN_SUMMARY' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='MAKE_APPOINTMENT' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='MOBILE_TOPUP_FACADE' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='MOBILE_TOPUP_FACADE_CASA' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='MOBILE_TOPUP_FACADE_CREDITCARD' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PAYMENT_OFFER' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_BP_BCD_ONETIME' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_BP_BCD_PAYEE' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_BP_BILLPAY' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_BP_BILLPAY_ONETIME' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_BP_BILLPAY_PAYEE' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_BP_FACADE' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_BP_MOBILE_TOPUP_ONETIME' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_BP_MOBILE_TOPUP_PAYEE' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_BP_MOBILE_TOPUP_SI_ONETIME' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_BP_MOBILE_TOPUP_SI_PAYEE' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_BP_MOBILE_WALLET_ONETIME' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_BP_SI_BCD_ONETIME' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_BP_SI_BCD_PAYEE' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_BP_SI_BILLPAY_ONETIME' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_BP_SI_BILLPAY_PAYEE' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_BULK_BILLPAY' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_FINANCIAL_SURVEY' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_FTH' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_FT_BANK_LOOKUP' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_FT_BKD_FACADE' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='CASA_APPLICATION' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='CHG_USR_NAME' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='COMMON' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='COM_COMPOSE_MESSAGE' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='CRD_ACTIVATE' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='CRD_ADD_SUP_CARD' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='CRD_CANCEL_DD' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='CRD_DISPUTE' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='CRD_INSURANCE_ENQUIRY' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='CRD_LIMIT' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='CRD_PAYMENT_HISTORY' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='ACT_ACCOUNT_CASA_ACTIVITY' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='ACT_ACCOUNT_DETAIL_CASA_DETAIL' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='ACT_ACCOUNT_DETAIL_CREDIT_DETAIL' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='ACT_ACCOUNT_DETAIL_INSUR_DETAIL' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='ACT_ACCOUNT_DETAIL_INVEST_DETAIL' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='ACT_ACCOUNT_DETAIL_LOAN_DETAIL' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='ACT_ACCOUNT_DETAIL_TD_DETAIL' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='ACT_BLOCK_CREDIT_CARD' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='ACT_BLOCK_DEBIT_CARD' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='ACT_CHANGE_TD' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='ACT_CHK_BOOK_REQUEST' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='ACT_CHK_BOOK_REQUEST_CASA' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='ACT_CHK_BOOK_REQUEST_STATUS' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='ACT_CHK_STATUS_INQUIRY' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='ACT_CHK_STATUS_INQUIRY_BOOKREQUEST' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='ACT_CHK_STATUS_INQUIRY_CASA' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='ACT_CHK_STOP_REQUEST' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='ACT_DEBIT_CARD_ACTIVATION' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='ACT_INVEST_BONDS' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='ACT_INVEST_MUTUALFUNDS' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='ACT_INVEST_STRUCTUREDNOTES' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='ACT_LOAN_AMORTIZATION' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='ACT_LOAN_APPLICATION' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='ACT_OPEN_TD' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='ACT_PINGIT_REG_BIRCUST' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='ActivityInquiry' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='BALANCE_TRANSFER' AND SYSTEM_ID='UB';

INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('ACT_ACCOUNT_DETAIL_CREDIT_DETAIL','UB','NO_GRP','-','EX','Credit Card Detail','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('ACT_ACCOUNT_DETAIL_INSUR_DETAIL','UB','NO_GRP','-','EX','Insurance Detail','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('ACT_ACCOUNT_DETAIL_INVEST_DETAIL','UB','NO_GRP','-','EX','Investment Detail','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('ACT_ACCOUNT_DETAIL_LOAN_DETAIL','UB','NO_GRP','-','EX','Loan Detail','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('ACT_ACCOUNT_DETAIL_TD_DETAIL','UB','NO_GRP','-','EX','Td Detail','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('ACT_ACCOUNTSERVICE_ACCOUNTSUMMARY','UB','NO_GRP','-','EX','At A Glance','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('ACT_ACCOUNTSERVICE_ESAVER','UB','ACT','-','EX','Open E-Saver','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('ACT_BLOCK_CREDIT_CARD','UB','ACT','-','EX','Add Dom Non-Barclays ACCs Payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('ACT_BLOCK_DEBIT_CARD','UB','ACT','-','EX','Add Dom Non-Barclays ACCs Payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('ACT_CHANGE_TD','UB','NO_GRP','-','EX','Change TD','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('ACT_CHK_BOOK_REQUEST_CASA','UB','NO_GRP','-','EX','Cheque Book Request CASA','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('ACT_CHK_BOOK_REQUEST_STATUS','UB','NO_GRP','-','EX','Cheque Book Request Status','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('ACT_CHK_STATUS_INQUIRY','UB','ACT','-','EX','Cheque Status Enquiry','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('ACT_CHK_STATUS_INQUIRY_BOOKREQUEST','UB','NO_GRP','-','EX','Cheque Book Request Inquiry','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('ACT_CHK_STATUS_INQUIRY_CASA','UB','NO_GRP','-','EX','Cheque Book Request Inquiry CASA','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('ACT_CHK_STOP_REQUEST','UB','ACT','-','EX','Stop Cheque Request','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('ACT_DEBIT_CARD_ACTIVATION','UB','ACT','-','EX','Add Dom Non-Barclays ACCs Payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('ACT_INVEST_BONDS','UB','ACT','-','EX','Bonds Details','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('ACT_INVEST_MUTUALFUNDS','UB','ACT','-','EX','Mutual Funds Details','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('ACT_INVEST_STRUCTUREDNOTES','UB','ACT','-','EX','Structured Notes Details','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('ACT_LOAN_AMORTIZATION','UB','ACT','-','EX','Loan Amortization','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('ActivityInquiry','UB','ACT','-','EX','Activity Inquiry','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('BALANCE_TRANSFER','UB','ACT','-','EX','Balance Transfer','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('CASA_APPLICATION','UB','ACT','-','EX','CASA Application','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('CHG_USR_NAME','UB','ACT','-','EX','Change Username','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('COM_COMPOSE_MESSAGE','UB','NO_GRP','-','EX','Compose Message','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('COMMON','UB','ACT',null,'EX','Common','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('CRD_ACTIVATE','UB','CRD','-','EX','Card Activation','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('CRD_ADD_SUP_CARD','UB','NO_GRP','-','EX','Add-on Supplementary Card','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('CRD_CANCEL_DD','UB','DD','-','EX','Cancel Direct Debit','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('CRD_DISPUTE','UB','NO_GRP',null,'EX','Initiate Dispute','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('CRD_INSURANCE_ENQUIRY','UB','CRD','-','EX','Credit Card Insurance Enrollment','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('CRD_LIMIT','UB','CRD','-','EX','Credit Line Maintenance','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('CRD_PAYMENT_HISTORY','UB','PMT_HIS','-','EX','Credit Card Payment History','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('CRD_PIN','UB','CRD',null,'EX','Credit Card Cash Advance PIN Request','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('CRD_REPLACE_CARD','UB','CRD',null,'EX','Credit Card Replacement','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('CRD_REPORTLOST','UB','NO_GRP','-','EX','Report Lost/Stolen Credit Card','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('CRD_SETUP_DD','UB','DD','-','EX','Setup Direct Debit','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('CRD_VIEW_DD','UB','DD','-','EX','View Direct debit','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_PAYEE_ACTIVATE_MRC','UB','NO_GRP','-','EX','Managers Cheque Payee Activation','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('CREATE_ACC_NICK_NAME','UB','NO_GRP','-','EX','Create ACC NickName','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('CREDIT_CARD_DETAIL','UB','NO_GRP','-','EX','Credit Card Detail','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('CREDIT_SUMMARY','UB','NO_GRP','-','EX','Credit Card Summary','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('CREDITCARD_APP','UB','NO_GRP','-','EX','Credit Card Application','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('CUS_ACTIVITY_LOG','UB','CUS','-','EX','Customer Activity Log','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('CUS_ALERT_ALERTMANAGEMENT','UB','NO_GRP','-','EX','Alert Enrollment','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('CUS_EMESSAGE','UB','CUS','-','EX','Message Centre','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('CUS_EMESSAGE_CASA','UB','CUS','-','EX','Customer Message CASA','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('CUS_EMESSAGE_CREDITCARD','UB','CUS','-','EX','Customer Message Credit Card','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('CUS_EMESSAGE_FUNDTRANSFER','UB','CUS','-','EX','Customer Message FT','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('CUS_EMESSAGE_INTRATE','UB','CUS','-','EX','Customer Message Interest Rate','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('CUS_EMESSAGE_LOAN','UB','CUS','-','EX','Customer Message Loan','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('CUS_EMESSAGE_TD','UB','CUS','-','EX','Customer Message Term Deposit','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('CUS_ESTMT','UB','CUS','-','EX','eStatement Enrollment','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('CUS_FX_RATES','UB','CUS','-','EX','Foreign Exchange Rate','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('CUS_FX_RATES_CUS','UB','CUS','-','EX','Customer FX Rate','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('CUS_FX_RATES_FUNDTRANSFER','UB','CUS','-','EX','Customer FX Rate FT','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('CUS_FX_RATES_TD','UB','CUS','-','EX','Customer FX Rate Term Deposit','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('CUS_FXRATES','UB','CUS','-','EX','Customer FX Rate','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('CUS_INT_RATES','UB','CUS','-','EX','Customer Interest Rates','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('CUS_INT_RATES_CASA','UB','CUS','-','EX','Interest Rate for CASA','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('CUS_INT_RATES_CUS','UB','CUS','-','EX','Customer Interest Rates','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('CUS_LINK_ACCOUNT','UB','CUS','-','EX','Link My ACCs','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('CUS_MANAGE_ALERTS','UB','CUS','-','EX','Customer Manage Alerts','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('CUS_ORDER_PAPER_STMT_CASA','UB','CUS','-','EX','Customer Order Paper Statement CASA','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('CUS_PROFILE_PREFERENCE','UB','NO_GRP','-','EX','My Preference','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('CUS_PROFILE_UPD_CONTACT_INFO','UB','NO_GRP','-','EX','Change Contact Info','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('CUS_REQ_BRANCH_LETTER','UB','CUS','-','EX','Search Branch Bank','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('CUS_REQ_LIABILITY_LETTER','UB','CUS','-','EX','Request Liability Letter','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('CUS_SITEMAP','UB','CUS','-','EX','Customer Site Map','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('ESPECIALLY_FOR_YOU_OFFER','UB','NO_GRP','-','EX','Especially For You Offer','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('ESPECIALLY_FOR_YOU_WIDGET','UB','NO_GRP','-','EX','Especially For You Widget','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('GET_ACC_NICK_NAME','UB','ACT','-','EX','Get ACC Nick Name','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('LOAN_DETAIL','UB','NO_GRP','-','EX','Loan Detail','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('LOAN_REPAYMENT','UB','NO_GRP','-','EX','Loan Repayment','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('LOAN_SUMMARY','UB','NO_GRP','-','EX','Loan Summary','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('MAKE_APPOINTMENT','UB','NO_GRP','-','EX','Schedule Appointment','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('MOBILE_TOPUP_FACADE','UB','BP','-','EX','Mobile Topup Facade','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('MOBILE_TOPUP_FACADE_CASA','UB','NO_GRP','-','EX','Mobile Topup CASA','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('MOBILE_TOPUP_FACADE_CREDITCARD','UB','NO_GRP','-','EX','Mobile Topup Credit Card','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PAYMENT_OFFER','UB','NO_GRP','-','EX','Payment Offer','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_BP_BCD_ONETIME','UB','BP','-','EX','Card Payment 3rd Party without Payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_BP_BCD_PAYEE','UB','BP','-','EX','Card Payment 3rd Party with Payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_BP_BILLPAY','UB','BP','-','EX','Bill payment check source ACC','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_BP_FACADE','UB','BP','-','EX','Bill Payment Facade','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_BP_MOBILE_TOPUP_PAYEE','UB','BP','-','EX','Mobile Topup with Payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_BP_MOBILE_TOPUP_SI_ONETIME','UB','BP','-','EX','Mobile Topup without Payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_BP_MOBILE_TOPUP_SI_PAYEE','UB','BP','-','EX','Mobile Topup with Payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_BP_SI_BCD_ONETIME','UB','BP','-','EX','Card Payment SI 3rd Party without Payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_BP_SI_BCD_PAYEE','UB','BP','-','EX','Third party Barclaycard with Payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_BP_SI_BILLPAY_ONETIME','UB','BP','-','EX','Bill Payment without Payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_BP_SI_BILLPAY_PAYEE','UB','BP','-','EX','Bill Payment with Payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('ACT_LOAN_APPLICATION','UB','ACT','-','EX','Loan Application','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_BULK_BILLPAY','UB','ACT','-','EX','Bulk bill payment','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_FT_SI_EXTERNAL_ONETIME','UB','FT','-','EX','Setup SI Dom Non Barclays ACC without Payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_FT_SI_EXTERNAL_PAYEE','UB','FT','-','EX','Setup SI Dom Non Barclays ACC with Payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_FT_SI_INTERNAL_ONETIME','UB','FT','-','EX','Setup SI Dom Barclays ACCs without Payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_FT_SI_INTERNAL_PAYEE','UB','FT','-','EX','Setup SI Dom Barclays ACCs with Payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_FT_SI_INTL_DT_ONETIME','UB','FT','-','EX','Setup SI for Int''l Dom FT without Payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_FT_SI_INTL_DT_PAYEE','UB','FT','-','EX','Setup SI for Int''l Dom FT with Payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_FT_SI_INTL_ONETIME','UB','FT','-','EX','Setup SI for Int''l FT without Payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_FT_SI_INTL_PAYEE','UB','FT','-','EX','Setup SI for Int''l FT with Payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_FT_SI_OWN','UB','FT','-','EX','Setup SI for FT between my ACCs','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_FT_SWIFT_LOOKUP','UB','NO_GRP','-','EX','Swift code Lookup','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_FTH','UB','FTH','-','EX','FT  and Payment History','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_PAYEE_ACTIVATE_BCD','UB','PAYEE','-','EX','Activate Barclaycard Payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_PAYEE_ACTIVATE_BKD','UB','PAYEE','-','EX','Activate Bank Draft Payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_PAYEE_ACTIVATE_BP','UB','PAYEE','-','EX','Activate Bill Payment Payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_PAYEE_ACTIVATE_EXTERNAL','UB','PAYEE','-','EX','Activate Dom Non Barclays ACC Payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_PAYEE_ACTIVATE_INTERNAL','UB','PAYEE','-','EX','Activate Dom Barclays ACC Payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_PAYEE_ACTIVATE_INTL','UB','PAYEE','-','EX','Activate Int''l FT Payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_PAYEE_ACTIVATE_INTL_DT','UB','PAYEE','-','EX','Activate Int''l Dom FT Payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_PAYEE_ACTIVATE_LN','UB','NO_GRP','-','EX','Loan Payee Activation','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_PAYEE_ACTIVATE_MTP','UB','PAYEE','-','EX','Activate Mobile Top-up Payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_PAYEE_ADD','UB','PAYEE','-','EX','Add Input Screen Payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_PAYEE_ADD_BCD','UB','PAYEE','-','EX','Add Barclay Card Payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_PAYEE_ADD_BKD','UB','PAYEE','-','EX','Add Bank Draft Payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_PAYEE_ADD_INTL','UB','PAYEE','-','EX','Add Int''l FT Payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_PAYEE_ADD_INTL_DT','UB','PAYEE',null,'EX','Add Int''l Dom FT Payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_PAYEE_ADD_LN','UB','NO_GRP','-','EX','Loan Add Payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_PAYEE_ADD_MRC','UB','PAYEE','-','EX','Add Bank Draft Payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_PAYEE_ADD_MTP','UB','PAYEE','-','EX','Add Mobile Top-up Payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_PAYEE_DELETE_BCD','UB','PAYEE',null,'EX','Delete Barclaycard Payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_PAYEE_DELETE_BKD','UB','PAYEE','-','EX','Delete Bank Draft Payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_PAYEE_DELETE_INTL','UB','PAYEE','-','EX','Delete Int''l FT Payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_PAYEE_DELETE_INTL_DT','UB','PAYEE','-','EX','Delete Int''l Dom FT Payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_PAYEE_DELETE_LN','UB','NO_GRP','-','EX','Loan Delete Payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_PAYEE_DELETE_MRC','UB','NO_GRP','-','EX','Managers Cheque Delete Payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_PAYEE_DELETE_MTP','UB','PAYEE','-','EX','Delete Mobile Top-up Payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_SI_CANCEL','UB','NO_GRP','-','EX','Cancel SI','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_SI_DETAIL','UB','NO_GRP','-','EX','View SI Detail','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_SI_LIST','UB','NO_GRP','-','EX','View SI List','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_SI_UPDATE','UB','NO_GRP','-','EX','Update SI','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('POT_SITEMAP','UB','NO_GRP','-','EX','Site Map','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('REWARDS_INQUIRY','UB','NO_GRP','-','EX','Rewards Inquiry','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_FX_RATE','UB','CUS','-','EX','View Forex Rates','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('REWARDS_REDEM_HISTORY','UB','NO_GRP','-','EX','Rewards Redem History','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('SEC_CHG_SQA','UB','SEC_POST','-','EX','Change Secret Question','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('SEC_COMMON','UB','SEC','-','EX','Security Common','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('SEC_FORGOT_PWD','UB','SEC_PRE','-','EX','Forgot Password','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('SEC_FORGOT_SQA','UB','SEC_PRE','-','EX','Forgot Secret Question Answer','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_FINANCIAL_SURVEY','UB','NO_GRP','-','EX','Financial Survey','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_FT_BANK_LOOKUP','UB','NO_GRP','-','EX','Bank Lookup','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_FT_BKD_ONETIME','UB','NO_GRP','-','EX','Purchase Bank Draft without Payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_FT_BKD_PAYEE','UB','NO_GRP','-','EX','Purchase Bank Draft with Payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_FT_CARD_PAYMENT_ONETIME','UB','FT','-','EX','Credit card payment without payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_FT_CARD_PAYMENT_PAYEE','UB','FT','-','EX','Credit card payment with payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_FT_CARD_PAYMENT_SI_ONETIME','UB','FT','-','EX','FT  without Payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_FT_CARD_PAYMENT_SI_PAYEE','UB','FT','-','EX','FT  with Payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_FT_EXTERNAL_ONETIME','UB','FT','-','EX','FT Dom Non Barclays ACC without Payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_FT_FACADE','UB','FT','-','EX','FT  Facade','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_FT_FACADE_CASA','UB','NO_GRP','-','EX','FT  Facade CASA','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_FT_FACADE_CREDITCARD','UB','NO_GRP','-','EX','FT  Facade Credit Card','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_FT_INTL_DT_ONETIME','UB','FT','-','EX','FT Int''l Dom without Payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_FT_INTL_DT_PAYEE','UB','FT','-','EX','FT Int''l Dom with payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_FT_INTL_ONETIME','UB','FT','-','EX','FT Int''l without Payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_FT_INTL_PAYEE','UB','FT','-','EX','FT Int''l with payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_FT_LOAN','UB','NO_GRP','-','EX','Loan Payment','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_FT_LOAN_INPUT_ONETIME','UB','NO_GRP','-','EX','FT  Loan Onetime','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_FT_LOAN_PAYMENT','UB','NO_GRP','-','EX','Payment','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_FT_LOAN_REPAYMENT','UB','FT','-','EX','Loan payment','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_FT_MRC_FACADE','UB','FT','-','EX','Managers Cheque Facade','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_FT_MRC_ONETIME','UB','NO_GRP',null,'EX','Purchase Managers Cheque without Payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_FT_MRC_PAYEE','UB','NO_GRP','-','EX','Purchase Managers Cheque with Payee','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('SEC_PREONLN_REG','UB','SEC_PRE','-','EX','Pre-registered customer fulfillment','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('SEC_FORGOT_UNAME','UB','SEC_PRE','-','EX','Forgot User Name','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('TD_DETAIL','UB','NO_GRP','-','EX','Term Deposit Detail','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('TD_SUMMARY','UB','NO_GRP','-','EX','Term Deposit Summary','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('SEC_LOGOUT','UB','SEC_POST','-','EX','Logout and Session Summary','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('UNBILLED_TXN','UB','NO_GRP','-','EX','Unbilled Transactions','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('UNIFY_COMMUNICATION','UB','NO_GRP','-','EX','Unified Communications','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('UPDATE_LANGUAGE_PREF','UB','NO_GRP','-','EX','Update Language Preference','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('VIEW_BULLETIN','UB','NO_GRP','-','EX','View Bulletin','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('ACT_PINGIT_REG_BIRCUST','UB','PAYEE','-','EX','Pingit Registration - BIR Customer','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('ACT_ACCOUNT_DETAIL_CASA_DETAIL','UB','NO_GRP','-','EX','Balance Enquiry','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('ACT_ACCOUNT_CASA_ACTIVITY','UB','NO_GRP','-','EX','Mini Statement','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('ACT_CHK_BOOK_REQUEST','UB','ACT','-','EX','Cheque Book Request','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('ACT_OPEN_TD','UB','NO_GRP','-','EX','Apply TD','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('CUS_INT_RATES_TD','UB','CUS','-','EX','View FD Rates','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('CUS_ORDER_PAPER_STMT','UB','CUS','-','EX','Statement Request','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_BP_BILLPAY_ONETIME','UB','BP','-','EX','Pay Bill UnRegistered','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_BP_BILLPAY_PAYEE','UB','BP','-','EX','Pay Bill Registered','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_BP_MOBILE_TOPUP_ONETIME','UB','BP','-','EX','Airtime Top Up','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_BP_MOBILE_WALLET_ONETIME','UB','NO_GRP','-','EX','Mobile Wallet','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_FT_EXTERNAL_PAYEE','UB','FT','-','EX','Fund Transfer DFT Registered','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_FT_INTERNAL_ONETIME','UB','FT','-','EX','Fund Transfer OTH UnRegistered','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_FT_INTERNAL_PAYEE','UB','FT','-','EX','Fund Transfer OTH Registered','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_FT_OWN','UB','FT','-','EX','Fund Transfer OWN','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_PAYEE_ADD_BP','UB','PAYEE','-','EX','Register Biller','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_PAYEE_ADD_EXTERNAL','UB','PAYEE','-','EX','Register Beneficiary DFT','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_PAYEE_ADD_INTERNAL','UB','PAYEE','-','EX','Register Beneficiary OTH','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_PAYEE_DELETE_BP','UB','PAYEE','-','EX','Delete Biller','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_PAYEE_DELETE_EXTERNAL','UB','PAYEE','-','EX','Delete Beneficiary DFT','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_PAYEE_DELETE_INTERNAL','UB','PAYEE','-','EX','Delete Beneficiary OTH','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_PAYEE_LIST','UB','PAYEE','-','EX','View My Billers','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('SEC_CHG_PWD','UB','SEC_POST','-','EX','Change PIN','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('SEC_LOGIN','UB','SEC_PRE','-','EX','User Authentication','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('SEC_ONLN_REG','UB','SEC_PRE','-','EX','Self Registration','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('TXN_HISTORY','UB','NO_GRP','-','EX','View Last Paid Bills','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('CUS_CHK_APPLN_STATUS','UB','CUS','-','EX','Check Application Status','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_FT_BKD_FACADE','UB','FT','-','EX','Bank Draft Facade','Execute','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_FT_EFT_ONETIME','UB','PAYEE','-','EX','ONE TIME DOMESTIC FT REQ-EFT','EXECUTE','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_FT_EFT_PAYEE','UB','PAYEE','-','EX','DOM FT REQ-EFT','EXECUTE','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_FT_RTGS_ONETIME','UB','PAYEE','-','EX','ONE TIME DOM FT REQ-RTGS','EXECUTE','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_FT_RTGS_PAYEE','UB','PAYEE','-','EX','DOM FT REQ - RTGS','EXECUTE','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_PAYEE_ACTIVATE_EFT','UB','PAYEE','-','EX','ACTIVATE EFT PAYEE','EXECUTE','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_PAYEE_ACTIVATE_RTGS','UB','PAYEE','-','EX','ACTIVATE RTGS PAYEE','EXECUTE','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_PAYEE_ADD_EFT','UB','PAYEE','-','EX','ADD EFT PAYEE','EXECUTE','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_PAYEE_ADD_RTGS','UB','PAYEE','-','EX','ADD RTGS PAYEE','EXECUTE','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_PAYEE_DELETE_EFT','UB','PAYEE','-','EX','DELETE EFT PAYEE','EXECUTE','N','N');
INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) VALUES ('PMT_PAYEE_DELETE_RTGS','UB','PAYEE','-','EX','DELETE RTGS PAYEE','EXECUTE','N','N');

COMMIT;
