----- INCIDENT - INC0004331343 ------

UPDATE C_LISTVALUE_MST SET list_value_key='ZMW' WHERE group_id='CURRENCY'  AND  system_id='MB'  AND list_value_key='ZMK' AND BUSINESS_ID='ZMBRB';

UPDATE C_LISTVALUE_RES_MST set list_value_key='ZMW', value='ZMW' where group_id='CURRENCY' and  system_id='MB' and list_value_key='ZMK' AND BUSINESS_ID = 'ZMBRB';


UPDATE S_SYSPARAM_MST SET PARAM_VALUE = 'ZMW'  WHERE (BUSINESS_ID = 'ZMBRB' AND SYSTEM_ID = 'MB' AND PARAM_ID = 'PMT_FT_SUPPORT_CURRENCY' AND ACTIVITY_ID = 'PMT_FT_EXTERNAL_ONETIME');

UPDATE S_SYSPARAM_MST SET PARAM_VALUE = 'ZMW'  WHERE (BUSINESS_ID = 'ZMBRB' AND SYSTEM_ID = 'MB' AND PARAM_ID = 'PMT_FT_SUPPORT_CURRENCY' AND ACTIVITY_ID = 'PMT_FT_EXTERNAL_PAYEE');

UPDATE S_SYSPARAM_MST SET PARAM_VALUE = 'ZMW,USD,CAD,GBP,CHF,ZAR,JPY,DKK,BWP,KES,NOK,SEK,EUR'  WHERE (BUSINESS_ID = 'ZMBRB' AND SYSTEM_ID = 'MB' AND PARAM_ID = 'PMT_FT_SUPPORT_CURRENCY' AND ACTIVITY_ID = 'PMT_FT_SI_INTERNAL_ONETIME');

UPDATE S_SYSPARAM_MST SET PARAM_VALUE = 'ZMW,USD,CAD,GBP,CHF,ZAR,JPY,DKK,BWP,KES,NOK,SEK,EUR'  WHERE (BUSINESS_ID = 'ZMBRB' AND SYSTEM_ID = 'MB' AND PARAM_ID = 'PMT_FT_SUPPORT_CURRENCY' AND ACTIVITY_ID = 'PMT_FT_INTERNAL_ONETIME');

UPDATE S_SYSPARAM_MST SET PARAM_VALUE = 'ZMW,USD,CAD,GBP,CHF,ZAR,JPY,DKK,BWP,KES,NOK,SEK,EUR'  WHERE (BUSINESS_ID = 'ZMBRB' AND SYSTEM_ID = 'MB' AND PARAM_ID = 'PMT_FT_SUPPORT_CURRENCY' AND ACTIVITY_ID = 'PMT_FT_INTERNAL_PAYEE');

UPDATE S_SYSPARAM_MST SET PARAM_VALUE = 'ZMW,USD'  WHERE (BUSINESS_ID = 'ZMBRB' AND SYSTEM_ID = 'MB' AND PARAM_ID = 'PMT_FT_BKD_SUPPORT_CURRENCY' AND ACTIVITY_ID = 'PMT_FT_MRC_ONETIME');

UPDATE S_SYSPARAM_MST SET PARAM_VALUE = 'ZMW'  WHERE (BUSINESS_ID = 'ZMBRB' AND SYSTEM_ID = 'MB' AND PARAM_ID = 'SUPPORT_CCY_LST' AND ACTIVITY_ID = 'PMT_FT_BKD_FACADE');

update C_MESSAGE_MST set message_key = 'ZMW' where message_key = 'ZMK' and system_id = 'MB' AND BUSINESS_ID = 'ZMBRB';

update C_MESSAGE_RES_MST set message_key = 'ZMW' where message_key = 'ZMK'  and system_id = 'MB' AND BUSINESS_ID = 'ZMBRB';

COMMIT;