DELETE  FROM C_BIZ_FUNC_MMAP WHERE  SYSTEM_ID='MB' AND BUSINESS_ID='KEBRB';

DELETE  FROM C_FORMATTER_MST WHERE  SYSTEM_ID='MB' AND BUSINESS_ID='KEBRB';

DELETE  FROM C_FUNCTION_SCREEN_MMAP WHERE  SYSTEM_ID='MB' AND BUSINESS_ID='KEBRB';

DELETE  FROM C_MESSAGE_MST WHERE  SYSTEM_ID='MB' AND BUSINESS_ID='KEBRB';

DELETE  FROM C_MESSAGE_RES_MST WHERE  SYSTEM_ID='MB' AND BUSINESS_ID='KEBRB';

DELETE  FROM C_SCRIPT_MST WHERE  SYSTEM_ID='MB' AND BUSINESS_ID='KEBRB';

DELETE  FROM C_SCRIPT_RES_MST WHERE  SYSTEM_ID='MB' AND BUSINESS_ID='KEBRB';

DELETE  FROM S_SES_SUMMARY_HST WHERE  SYSTEM_ID='MB' AND BUSINESS_ID='KEBRB';

DELETE  FROM S_SYSPARAM_MST WHERE  SYSTEM_ID='MB' AND BUSINESS_ID='KEBRB';

DELETE  FROM C_COMPONENT_MST WHERE  SYSTEM_ID='MB' AND BUSINESS_ID='KEBRB';

DELETE  FROM C_COMPONENT_RES_MST WHERE  SYSTEM_ID='MB' AND BUSINESS_ID='KEBRB';

DELETE  FROM S_FUNCTION_CONFIG WHERE  SYSTEM_ID='MB' AND BUSINESS_ID='KEBRB';


COMMIT;


