
DELETE FROM C_ENHANCED_ENTITLEMENT_MST WHERE SYSTEM_ID ='MB' AND BUSINESS_ID='KEBRB';

DELETE  FROM C_BIZ_FUNC_MMAP WHERE  SYSTEM_ID='MB' AND BUSINESS_ID='KEBRB';

DELETE  FROM C_LISTVALUE_MST WHERE  SYSTEM_ID='MB' AND BUSINESS_ID='KEBRB';

DELETE  FROM C_LISTVALUE_RES_MST WHERE  SYSTEM_ID='MB' AND BUSINESS_ID='KEBRB';

DELETE  FROM C_COMPONENT_MST WHERE  SYSTEM_ID='MB' AND BUSINESS_ID='KEBRB';

DELETE  FROM C_COMPONENT_RES_MST WHERE  SYSTEM_ID='MB' AND BUSINESS_ID='KEBRB';

DELETE  FROM S_FUNCTION_CONFIG WHERE  SYSTEM_ID='MB' AND BUSINESS_ID='KEBRB';

DELETE FROM  S_LIMIT_GLOBAL_MST   WHERE SYSTEM_ID = 'MB'  AND BUSINESS_ID='KEBRB';

DELETE FROM  S_LIMIT_CUST_MST   WHERE SYSTEM_ID = 'MB'  AND BUSINESS_ID='KEBRB';


COMMIT;