
-----------------------		URL INSERTION QUERY FOR ZWBRB - PRODUCTION   --------------------------
DELETE FROM S_URL_BUSINESS_MAP_MST WHERE SYSTEM_ID='MB' AND BUSINESS_ID='ZWBRB' AND URL_PATTERN='https://www.zw.secure.barclays.com/bmg';

INSERT INTO S_URL_BUSINESS_MAP_MST (SYSTEM_ID, BUSINESS_ID, URL_PATTERN, LANGUAGE_ID) VALUES ('MB','ZWBRB','https://www.zw.secure.barclays.com/bmg','EN');

DELETE FROM S_URL_BUSINESS_MAP_MST WHERE SYSTEM_ID='MB' AND BUSINESS_ID='ZWBRB' AND URL_PATTERN='https://zwc2bir-dr.barclays.intranet/bmg';

DELETE FROM S_URL_BUSINESS_MAP_MST WHERE SYSTEM_ID='MB' AND BUSINESS_ID='ZWBRB' AND URL_PATTERN='https://zwc2bir-live.barclays.intranet/bmg';

INSERT INTO S_URL_BUSINESS_MAP_MST (SYSTEM_ID, BUSINESS_ID, URL_PATTERN, LANGUAGE_ID) VALUES ('MB','ZWBRB','https://zwc2bir-live.barclays.intranet/bmg','EN');

COMMIT;
