DELETE FROM C_PRODUCT_MST WHERE BUSINESS_ID='KEBRB';
INSERT INTO C_PRODUCT_MST(PRODUCT_CD, BUSINESS_ID, PRODUCT_DESC,DELETE_FLG,CURRENCY_CD) VALUES ('250', 'KEBRB', 'Fixed Term Deposit', 'N','KES');
COMMIT;