-- INSERTING INTO C_FUNCTION_MST

DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='ACT_ACCOUNT_DETAIL_CASA_DETAIL' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='ACT_ACCOUNT_CASA_ACTIVITY' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='ACT_CHK_BOOK_REQUEST' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='ACT_OPEN_TD' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='CUS_INT_RATES_TD' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='CUS_ORDER_PAPER_STMT' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_BP_BILLPAY_ONETIME' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_BP_BILLPAY_PAYEE' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_BP_MOBILE_TOPUP_ONETIME' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_BP_MOBILE_WALLET_ONETIME' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_FT_EXTERNAL_PAYEE' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_FT_INTERNAL_ONETIME' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_FT_INTERNAL_PAYEE' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_FT_OWN' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_PAYEE_ADD_BP' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_PAYEE_ADD_EXTERNAL' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_PAYEE_ADD_INTERNAL' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_PAYEE_DELETE_BP' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_PAYEE_DELETE_EXTERNAL' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_PAYEE_DELETE_INTERNAL' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_PAYEE_LIST' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='SEC_CHG_PWD' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='SEC_LOGIN' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='SEC_ONLN_REG' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='TXN_HISTORY' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_FX_RATE' AND SYSTEM_ID='UB';
--Edit Beneficiary
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_PAYEE_UPD_EXTERNAL' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_PAYEE_UPD_INTERNAL' AND SYSTEM_ID='UB';
--Credit Card
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='ACT_CCD_UNBILLED_TRANS' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='ACT_CCD_STATEMENT_TRANS' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='ACT_CREDIT_CARD_DETAIL' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_FT_CARD_PAYMENT_ONETIME' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_FT_CARD_PAYMENT_OWN' AND SYSTEM_ID='UB';
--Cash send
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_CS' AND SYSTEM_ID='UB';

Commit;