--delete records
DELETE FROM C_LISTVALUE_MST WHERE SYSTEM_ID='UB' AND BUSINESS_ID='UGBRB' AND GROUP_ID='SYS_PARAM_CS' AND LIST_VALUE_KEY='CS_MULTIPLE_AMT';
DELETE FROM C_LISTVALUE_MST WHERE SYSTEM_ID='UB' AND BUSINESS_ID='UGBRB' AND GROUP_ID='SYS_PARAM_CS' AND LIST_VALUE_KEY='CS_MIN_AMT';
DELETE FROM C_LISTVALUE_MST WHERE SYSTEM_ID='UB' AND BUSINESS_ID='UGBRB' AND GROUP_ID='SYS_PARAM_CS' AND LIST_VALUE_KEY='CS_MAX_AMT';
DELETE FROM C_LISTVALUE_MST WHERE SYSTEM_ID='UB' AND BUSINESS_ID='UGBRB' AND GROUP_ID='SYS_PARAM_CS' AND LIST_VALUE_KEY='CS_MAX_DAYAMT';
DELETE FROM C_LISTVALUE_MST WHERE SYSTEM_ID='UB' AND BUSINESS_ID='UGBRB' AND GROUP_ID='SYS_PARAM_CS' AND LIST_VALUE_KEY='CS_MAX_TXS';

-- Insert script for Cash Send table C_LISTVALUE_MST
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) VALUES ('UB','UGBRB','SYS_PARAM_CS','CS_MIN_AMT',null,null,'N',null,sysdate,null,sysdate,'N',null);

INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) VALUES ('UB','UGBRB','SYS_PARAM_CS','CS_MAX_AMT',null,null,'N',null,sysdate,null,sysdate,'N',null);

INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) VALUES ('UB','UGBRB','SYS_PARAM_CS','CS_MAX_DAYAMT',null,null,'N',null,sysdate,null,sysdate,'N',null);

INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) VALUES ('UB','UGBRB','SYS_PARAM_CS','CS_MAX_TXS',null,null,'N',null,sysdate,null,sysdate,'N',null);

INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) VALUES ('UB','UGBRB','SYS_PARAM_CS','CS_MULTIPLE_AMT',null,null,'N',null,sysdate,null,sysdate,'N',null);


COMMIT;

