 DELETE FROM C_BANKROUTING_MST WHERE BUSINESS_ID = 'GHBRB';
 DELETE FROM C_BILLER_MST WHERE BUSINESS_ID = 'GHBRB';
 DELETE FROM C_BUSINESS_MST WHERE BUSINESS_ID = 'GHBRB';
 DELETE FROM C_FORMATTER_MST WHERE SYSTEM_ID = 'UB' and BUSINESS_ID = 'GHBRB';
 DELETE FROM C_LISTVALUE_MST WHERE SYSTEM_ID = 'UB' and BUSINESS_ID = 'GHBRB';
 DELETE FROM C_LISTVALUE_RES_MST WHERE SYSTEM_ID = 'UB' and BUSINESS_ID = 'GHBRB';
 DELETE FROM C_MESSAGE_MST WHERE SYSTEM_ID = 'UB' and BUSINESS_ID = 'GHBRB';
 DELETE FROM C_MESSAGE_RES_MST WHERE SYSTEM_ID = 'UB' and BUSINESS_ID = 'GHBRB';
 DELETE FROM S_FUNCTION_CONFIG WHERE SYSTEM_ID = 'UB' and BUSINESS_ID = 'GHBRB';
 DELETE FROM S_SYSPARAM_MST WHERE SYSTEM_ID = 'UB' and BUSINESS_ID = 'GHBRB';
 
 Commit;
