
SET DEFINE OFF;
SET ECHO ON;

spool ssashmu_exe.log;
show user;
@@ DML/INSERT_C_BANKROUTING_MST.sql
@@ DML/INSERT_C_BILLER_MST.sql
@@ DML/INSERT_C_BUSINESS_MST.sql
@@ DML/INSERT_S_FUNCTION_CONFIG.sql
COMMIT;
@@ DML/INSERT_C_FORMATTER_MST.sql
@@ DML/INSERT_S_SYSPARAM_MST.sql
COMMIT;
@@ DML/INSERT_C_LISTVALUE_MST.sql
@@ DML/INSERT_C_LISTVALUE_RES_MST.sql
@@ DML/INSERT_C_MESSAGE_MST.sql
@@ DML/INSERT_C_MESSAGE_RES_MST.sql
COMMIT;
spool off;
