BEGIN
   OTH_ERRMSG_PROC_SSA('UGBRB');
END;
/

DELETE FROM C_MESSAGE_MST WHERE SYSTEM_ID='MB' AND BUSINESS_ID='UGBRB' AND MESSAGE_KEY = 'BMB99999';
Insert into C_MESSAGE_MST (SYSTEM_ID,BUSINESS_ID,CATEGORY,MESSAGE_KEY,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,SOURCE_SYSTEM_ID) values ('MB','UGBRB','FATAL','BMB99999',null,null,null,null,null,'UNKNOWN');

DELETE FROM C_MESSAGE_RES_MST WHERE SYSTEM_ID='MB' AND BUSINESS_ID='UGBRB' AND MESSAGE_KEY = 'BMB99999';
Insert into C_MESSAGE_RES_MST (LANGUAGE_ID,MESSAGE_VALUE,SYSTEM_ID,BUSINESS_ID,MESSAGE_KEY) values ('EN','Please contact our Contact Centre on +254 20 3900000/ +254 722 130120, +254 733 130120 for assistance.','MB','UGBRB','BMB99999');

DELETE FROM C_MESSAGE_MST WHERE SYSTEM_ID='MB' AND BUSINESS_ID='UGBRB' AND MESSAGE_KEY = 'BMB90004';
Insert into C_MESSAGE_MST (SYSTEM_ID,BUSINESS_ID,CATEGORY,MESSAGE_KEY,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,SOURCE_SYSTEM_ID) values ('MB','UGBRB','FATAL','BMB90004',null,null,null,null,null,NULL);

DELETE FROM C_MESSAGE_RES_MST WHERE SYSTEM_ID='MB' AND BUSINESS_ID='UGBRB' AND MESSAGE_KEY = 'BMB90004';
Insert into C_MESSAGE_RES_MST (LANGUAGE_ID,MESSAGE_VALUE,SYSTEM_ID,BUSINESS_ID,MESSAGE_KEY) values ('EN','Please contact our Contact Centre on +254 20 3900000/ +254 722 130120, +254 733 130120 for assistance.','MB','UGBRB','BMB90004');

DELETE FROM C_MESSAGE_MST WHERE SYSTEM_ID='MB' AND BUSINESS_ID='UGBRB' AND MESSAGE_KEY = 'BMB90005';
Insert into C_MESSAGE_MST (SYSTEM_ID,BUSINESS_ID,CATEGORY,MESSAGE_KEY,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,SOURCE_SYSTEM_ID) values ('MB','UGBRB','FATAL','BMB90005',null,null,null,null,null,NULL);

DELETE FROM C_MESSAGE_RES_MST WHERE SYSTEM_ID='MB' AND BUSINESS_ID='UGBRB' AND MESSAGE_KEY = 'BMB90005';
Insert into C_MESSAGE_RES_MST (LANGUAGE_ID,MESSAGE_VALUE,SYSTEM_ID,BUSINESS_ID,MESSAGE_KEY) values ('EN','Transaction is currently not available due to maintenance. Please retry after sometimes','MB','UGBRB','BMB90005');


COMMIT;