BEGIN
  C_PROD_ELIG_Procedure('GHBRB');
END;
/



---- Fund Transfer between My Accounts - PMT_FT_OWN --------
DELETE FROM C_PRODUCT_ELIGIBILITY WHERE ACTIVITY_ID='PMT_FT_OWN' AND BUSINESS_ID='GHBRB' AND SYSTEM_ID='MB';

INSERT INTO C_PRODUCT_ELIGIBILITY (SERIAL_NUMBER,BUSINESS_ID,ACTIVITY_ID,ROLE_CATEGORY_CD,PRD_CRDR_IND,PRD_CODE,PRD_CATEGORY,INC_OR_EXC,ACCOUNT_STATUS,ACCOUNT_BLOCK_CODE1,ACCOUNT_BLOCK_CODE2,CARD_TYPE,CARD_STATUS,CARD_BLOCK_CODE,SYSTEM_ID,EXCEPTION) values (c_product_eligibility_SEQUENCE.NEXTVAL,'GHBRB','PMT_FT_OWN','MB','DR',null,'CASA','INC','CASA-0',null,null,null,null,null,'MB',null);
INSERT INTO C_PRODUCT_ELIGIBILITY (SERIAL_NUMBER,BUSINESS_ID,ACTIVITY_ID,ROLE_CATEGORY_CD,PRD_CRDR_IND,PRD_CODE,PRD_CATEGORY,INC_OR_EXC,ACCOUNT_STATUS,ACCOUNT_BLOCK_CODE1,ACCOUNT_BLOCK_CODE2,CARD_TYPE,CARD_STATUS,CARD_BLOCK_CODE,SYSTEM_ID,EXCEPTION) values (c_product_eligibility_SEQUENCE.NEXTVAL,'GHBRB','PMT_FT_OWN','MB','CR',null,'CASA','INC','CASA-0',null,null,null,null,null,'MB',null);

---- Fund Transfer To Domestic Barclays accounts with payee - PMT_FT_INTERNAL_PAYEE --------
DELETE FROM C_PRODUCT_ELIGIBILITY WHERE ACTIVITY_ID='PMT_FT_INTERNAL_PAYEE' AND BUSINESS_ID='GHBRB' AND SYSTEM_ID='MB';
INSERT INTO C_PRODUCT_ELIGIBILITY (SERIAL_NUMBER,BUSINESS_ID,ACTIVITY_ID,ROLE_CATEGORY_CD,PRD_CRDR_IND,PRD_CODE,PRD_CATEGORY,INC_OR_EXC,ACCOUNT_STATUS,ACCOUNT_BLOCK_CODE1,ACCOUNT_BLOCK_CODE2,CARD_TYPE,CARD_STATUS,CARD_BLOCK_CODE,SYSTEM_ID,EXCEPTION) values (c_product_eligibility_SEQUENCE.NEXTVAL,'GHBRB','PMT_FT_INTERNAL_PAYEE','MB','DR',null,'CASA','INC','CASA-0',null,null,null,null,null,'MB',null);

---- Fund Transfer To Domestic Non Barclays accounts with payee - PMT_FT_EXTERNAL_PAYEE --------
DELETE FROM C_PRODUCT_ELIGIBILITY WHERE ACTIVITY_ID='PMT_FT_EXTERNAL_PAYEE' AND BUSINESS_ID='GHBRB' AND SYSTEM_ID='MB';
INSERT INTO C_PRODUCT_ELIGIBILITY (SERIAL_NUMBER,BUSINESS_ID,ACTIVITY_ID,ROLE_CATEGORY_CD,PRD_CRDR_IND,PRD_CODE,PRD_CATEGORY,INC_OR_EXC,ACCOUNT_STATUS,ACCOUNT_BLOCK_CODE1,ACCOUNT_BLOCK_CODE2,CARD_TYPE,CARD_STATUS,CARD_BLOCK_CODE,SYSTEM_ID,EXCEPTION) values (c_product_eligibility_SEQUENCE.NEXTVAL,'GHBRB','PMT_FT_EXTERNAL_PAYEE','MB','DR',null,'CASA','INC','CASA-0',null,null,null,null,null,'MB',null);

---- Fund Transfer - international with payee - PMT_FT_INTL_PAYEE --------
DELETE FROM C_PRODUCT_ELIGIBILITY WHERE ACTIVITY_ID='PMT_FT_INTL_PAYEE' AND BUSINESS_ID='GHBRB' AND SYSTEM_ID='MB';
INSERT INTO C_PRODUCT_ELIGIBILITY (SERIAL_NUMBER,BUSINESS_ID,ACTIVITY_ID,ROLE_CATEGORY_CD,PRD_CRDR_IND,PRD_CODE,PRD_CATEGORY,INC_OR_EXC,ACCOUNT_STATUS,ACCOUNT_BLOCK_CODE1,ACCOUNT_BLOCK_CODE2,CARD_TYPE,CARD_STATUS,CARD_BLOCK_CODE,SYSTEM_ID,EXCEPTION) values (c_product_eligibility_SEQUENCE.NEXTVAL,'GHBRB','PMT_FT_INTL_PAYEE','MB','DR',null,'CASA','INC','CASA-0',null,null,null,null,null,'MB',null);

---- Bill Payment with payee - PMT_BP_BILLPAY_PAYEE --------
DELETE FROM C_PRODUCT_ELIGIBILITY WHERE ACTIVITY_ID='PMT_BP_BILLPAY_PAYEE' AND BUSINESS_ID='GHBRB' AND SYSTEM_ID='MB';
INSERT INTO C_PRODUCT_ELIGIBILITY (SERIAL_NUMBER,BUSINESS_ID,ACTIVITY_ID,ROLE_CATEGORY_CD,PRD_CRDR_IND,PRD_CODE,PRD_CATEGORY,INC_OR_EXC,ACCOUNT_STATUS,ACCOUNT_BLOCK_CODE1,ACCOUNT_BLOCK_CODE2,CARD_TYPE,CARD_STATUS,CARD_BLOCK_CODE,SYSTEM_ID,EXCEPTION) values (c_product_eligibility_SEQUENCE.NEXTVAL,'GHBRB','PMT_BP_BILLPAY_PAYEE','MB','DR',null,'CASA','INC','CASA-0',null,null,null,null,null,'MB',null);

---- Purchase Bank Draft with payee - PMT_FT_BKD_PAYEE --------
DELETE FROM C_PRODUCT_ELIGIBILITY WHERE ACTIVITY_ID='PMT_FT_BKD_PAYEE' AND BUSINESS_ID='GHBRB' AND SYSTEM_ID='MB';
INSERT INTO C_PRODUCT_ELIGIBILITY (SERIAL_NUMBER,BUSINESS_ID,ACTIVITY_ID,ROLE_CATEGORY_CD,PRD_CRDR_IND,PRD_CODE,PRD_CATEGORY,INC_OR_EXC,ACCOUNT_STATUS,ACCOUNT_BLOCK_CODE1,ACCOUNT_BLOCK_CODE2,CARD_TYPE,CARD_STATUS,CARD_BLOCK_CODE,SYSTEM_ID,EXCEPTION) values (c_product_eligibility_SEQUENCE.NEXTVAL,'GHBRB','PMT_FT_BKD_PAYEE','MB','DR',null,'CASA','INC','CASA-0',null,null,null,null,null,'MB',null);

---- Purchase Manager Cheque with payee - PMT_FT_MRC_PAYEE --------
DELETE FROM C_PRODUCT_ELIGIBILITY WHERE ACTIVITY_ID='PMT_FT_MRC_PAYEE' AND BUSINESS_ID='GHBRB' AND SYSTEM_ID='MB';
INSERT INTO C_PRODUCT_ELIGIBILITY (SERIAL_NUMBER,BUSINESS_ID,ACTIVITY_ID,ROLE_CATEGORY_CD,PRD_CRDR_IND,PRD_CODE,PRD_CATEGORY,INC_OR_EXC,ACCOUNT_STATUS,ACCOUNT_BLOCK_CODE1,ACCOUNT_BLOCK_CODE2,CARD_TYPE,CARD_STATUS,CARD_BLOCK_CODE,SYSTEM_ID,EXCEPTION) values (c_product_eligibility_SEQUENCE.NEXTVAL,'GHBRB','PMT_FT_MRC_PAYEE','MB','DR',null,'CASA','INC','CASA-0',null,null,null,null,null,'MB',null);

---- Cheque Book Request - ACT_CHK_BOOK_REQUEST --------
DELETE FROM C_PRODUCT_ELIGIBILITY WHERE ACTIVITY_ID='ACT_CHK_BOOK_REQUEST' AND BUSINESS_ID='GHBRB' AND SYSTEM_ID='MB';
INSERT INTO C_PRODUCT_ELIGIBILITY (SERIAL_NUMBER,BUSINESS_ID,ACTIVITY_ID,ROLE_CATEGORY_CD,PRD_CRDR_IND,PRD_CODE,PRD_CATEGORY,INC_OR_EXC,ACCOUNT_STATUS,ACCOUNT_BLOCK_CODE1,ACCOUNT_BLOCK_CODE2,CARD_TYPE,CARD_STATUS,CARD_BLOCK_CODE,SYSTEM_ID,EXCEPTION) values (c_product_eligibility_SEQUENCE.NEXTVAL,'GHBRB','ACT_CHK_BOOK_REQUEST','MB','DR',null,'CASA','INC','CASA-0',null,null,null,null,null,'MB',null);


COMMIT;


