
-- Need to execute in SSASHMA schema

CREATE OR REPLACE SYNONYM C_BANKROUTING_MST FOR SSASHMA.C_BANKROUTING_MST;

CREATE OR REPLACE SYNONYM C_BILLER_MST FOR SSASHMA.C_BILLER_MST;

CREATE OR REPLACE SYNONYM C_BUSINESS_MST FOR SSASHMA.C_BUSINESS_MST;

CREATE OR REPLACE SYNONYM C_COMPONENT_MST FOR SSASHMA.C_COMPONENT_MST;

CREATE OR REPLACE SYNONYM C_COMPONENT_RES_MST FOR SSASHMA.C_COMPONENT_RES_MST;

CREATE OR REPLACE SYNONYM C_FORMATTER_MST FOR SSASHMA.C_FORMATTER_MST;

CREATE OR REPLACE SYNONYM C_INTEREST_RATE_MST FOR SSASHMA.C_INTEREST_RATE_MST;

CREATE OR REPLACE SYNONYM C_LISTVALUE_MST FOR SSASHMA.C_LISTVALUE_MST;

CREATE OR REPLACE SYNONYM C_LISTVALUE_RES_MST FOR SSASHMA.C_LISTVALUE_RES_MST;

CREATE OR REPLACE SYNONYM C_MESSAGE_MST FOR SSASHMA.C_MESSAGE_MST;

CREATE OR REPLACE SYNONYM C_MESSAGE_RES_MST FOR SSASHMA.C_MESSAGE_RES_MST;

CREATE OR REPLACE SYNONYM C_PRODUCT_MST FOR SSASHMA.C_PRODUCT_MST;

CREATE OR REPLACE SYNONYM S_FUNCTION_CONFIG FOR SSASHMA.S_FUNCTION_CONFIG;

CREATE OR REPLACE SYNONYM S_LIMIT_CUST_TOTAL FOR SSASHMA.S_LIMIT_CUST_TOTAL;

CREATE OR REPLACE SYNONYM S_SES_SUMMARY_HST FOR SSASHMA.S_SES_SUMMARY_HST;

CREATE OR REPLACE SYNONYM S_SYSPARAM_MST FOR SSASHMA.S_SYSPARAM_MST;

CREATE OR REPLACE SYNONYM S_TXN_CUT_OFF_MST FOR SSASHMA.S_TXN_CUT_OFF_MST;

CREATE OR REPLACE SYNONYM S_URL_BUSINESS_MAP_MST FOR SSASHMA.S_URL_BUSINESS_MAP_MST;