


Delete FROM C_LISTVALUE_MST WHERE GROUP_ID='CURR_SUPPORT_INT_ACC' and SYSTEM_ID='MB' and BUSINESS_ID = 'KEBRB';


Insert into C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('MB','KEBRB','CURR_SUPPORT_INT_ACC','FCY1FCY2',null,null,'N',null,null,null,null,'N','Y');
Insert into C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('MB','KEBRB','CURR_SUPPORT_INT_ACC','FCYFCY',null,null,'N',null,null,null,null,'N','Y');
Insert into C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('MB','KEBRB','CURR_SUPPORT_INT_ACC','FCYLCY',null,null,'N',null,null,null,null,'N','Y');
Insert into C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('MB','KEBRB','CURR_SUPPORT_INT_ACC','LCYFCY',null,null,'N',null,null,null,null,'N','Y');
Insert into C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('MB','KEBRB','CURR_SUPPORT_INT_ACC','LCYLCY',null,null,'N',null,null,null,null,'N','Y');


Delete FROM C_LISTVALUE_RES_MST WHERE GROUP_ID='CURR_SUPPORT_INT_ACC' and SYSTEM_ID='MB' and BUSINESS_ID = 'KEBRB';

Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,LIST_VALUE_KEY,GROUP_ID,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('MB','KEBRB','LCYLCY','CURR_SUPPORT_INT_ACC','EN','Y',1);
Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,LIST_VALUE_KEY,GROUP_ID,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('MB','KEBRB','FCYFCY','CURR_SUPPORT_INT_ACC','EN','Y',2);
Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,LIST_VALUE_KEY,GROUP_ID,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('MB','KEBRB','LCYFCY','CURR_SUPPORT_INT_ACC','EN','Y',3);
Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,LIST_VALUE_KEY,GROUP_ID,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('MB','KEBRB','FCYLCY','CURR_SUPPORT_INT_ACC','EN','Y',4);
Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,LIST_VALUE_KEY,GROUP_ID,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('MB','KEBRB','FCY1FCY2','CURR_SUPPORT_INT_ACC','EN','N',5);


Commit;
