
-----------------------		URL INSERTION QUERY FOR BWBRB - SIT   --------------------------
DELETE FROM S_URL_BUSINESS_MAP_MST WHERE SYSTEM_ID='MB' AND BUSINESS_ID='BWBRB' AND URL_PATTERN='https://s04t.wload.global:24100/bmg';

INSERT INTO S_URL_BUSINESS_MAP_MST (SYSTEM_ID, BUSINESS_ID, URL_PATTERN, LANGUAGE_ID, SEGMENT_ID) VALUES ('MB','BWBRB','https://s04t.wload.global:24100/bmg','EN','MASS');
COMMIT;