BEGIN
  BIR_Procedure_SSA('MUBOB');
END;
/



BEGIN
   ACCT_ERRMSG_PROC_SSA('MUBOB');
END;
/



BEGIN
   AUTH_ERRMSG_PROC_SSA('MUBOB');
END;
/


INSERT INTO	C_MESSAGE_MST (SYSTEM_ID,BUSINESS_ID,CATEGORY,MESSAGE_KEY,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,SOURCE_SYSTEM_ID) values ('MB','MUBOB','FATAL','ATH00119',null,null,null,null,null,'AUTH');
INSERT INTO	C_MESSAGE_RES_MST (LANGUAGE_ID,MESSAGE_VALUE,SYSTEM_ID,BUSINESS_ID,MESSAGE_KEY) values ('EN','Your Mobile banking access has been blocked. Please contact our Customer Service Centre at 402 1000 within Mauritius or +230 402 1000 from outside Mauritius for assistance.','MB','MUBOB','ATH00119');
INSERT INTO	C_MESSAGE_MST (SYSTEM_ID,BUSINESS_ID,CATEGORY,MESSAGE_KEY,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,SOURCE_SYSTEM_ID) values ('MB','MUBOB','FATAL','ATH00121',null,null,null,null,null,'AUTH');
INSERT INTO	C_MESSAGE_RES_MST (LANGUAGE_ID,MESSAGE_VALUE,SYSTEM_ID,BUSINESS_ID,MESSAGE_KEY) values ('EN','Your account has not been activated. Please contact our Customer Service Centre at 402 1000 within Mauritius or +230 402 1000 from outside Mauritius for assistance.','MB','MUBOB','ATH00121');

COMMIT;


BEGIN
   BP_ERRMSG_PROC_SSA('MUBOB');
END;
/


BEGIN
   FTR_ERRMSG_PROC_SSA('MUBOB');
END;
/

INSERT INTO	C_MESSAGE_MST (SYSTEM_ID,BUSINESS_ID,CATEGORY,MESSAGE_KEY,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,SOURCE_SYSTEM_ID) values ('MB','MUBOB','FATAL','FTR00507',null,null,null,null,null,null);
INSERT INTO	C_MESSAGE_RES_MST (LANGUAGE_ID,MESSAGE_VALUE,SYSTEM_ID,BUSINESS_ID,MESSAGE_KEY) values ('EN','The account selected cannot be used for the transaction. Please contact our Customer Service Centre at 402 1000 within Mauritius or +230 402 1000 from outside Mauritius for assistance.','MB','MUBOB','FTR00507');

COMMIT;


BEGIN
   OTH_ERRMSG_PROC_SSA('MUBOB');
END;
/


INSERT INTO	C_MESSAGE_RES_MST (LANGUAGE_ID,MESSAGE_VALUE,SYSTEM_ID,BUSINESS_ID,MESSAGE_KEY) values ('EN','Temporary out of service. Please contact our Customer Service Centre at 402 1000 within Mauritius or +230 402 1000 from outside Mauritius for assistance.','MB','MUBOB','BMB99999');
INSERT INTO	C_MESSAGE_MST (SYSTEM_ID,BUSINESS_ID,CATEGORY,MESSAGE_KEY,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,SOURCE_SYSTEM_ID) values ('MB','MUBOB','FATAL','BMB99999',null,null,null,null,null,'UNKNOWN');
INSERT INTO	C_MESSAGE_RES_MST (LANGUAGE_ID,MESSAGE_VALUE,SYSTEM_ID,BUSINESS_ID,MESSAGE_KEY) values ('EN','Please contact our Customer Service Centre at 402 1000 within Mauritius or +230 402 1000 from outside Mauritius for assistance.','MB','MUBOB','BMB90004');
INSERT INTO	C_MESSAGE_MST (SYSTEM_ID,BUSINESS_ID,CATEGORY,MESSAGE_KEY,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,SOURCE_SYSTEM_ID) values ('MB','MUBOB','FATAL','BMB90004',null,null,null,null,null,NULL);

COMMIT;
