-- Unable to Render DDL with DBMS_METADATA using internal generator.
CREATE TABLE C_COMPONENT_MST
(
  SCREEN_ID VARCHAR2(30 BYTE) NOT NULL,
  SYSTEM_ID VARCHAR2(10 BYTE) NOT NULL,
  BUSINESS_ID VARCHAR2(10 BYTE) NOT NULL,
  COMPONENT_KEY VARCHAR2(40 BYTE) NOT NULL,
  RENDERED_FLG CHAR(1 BYTE),
  REQUIRED_FLG CHAR(1 BYTE),
  HAS_HELP_TEXT_FLG CHAR(1 BYTE),
  FORMATTER_ID NUMBER(10, 0),
  LISTVALUE_GROUP_ID VARCHAR2(30 BYTE),
  DEFAULT_VALUE VARCHAR2(20 BYTE),
  DISP_ORDER NUMBER(3, 0),
  PARENT_COMPONENT_KEY VARCHAR2(25 BYTE),
  MODIFIED_BY VARCHAR2(20 BYTE),
  MODIFIED_DTM TIMESTAMP(6),
  AUTHORIZED_BY VARCHAR2(20 BYTE),
  AUTHORIZED_DTM TIMESTAMP(6),
  DELETE_FLG CHAR(1 BYTE),
  CONFIG_FLG VARCHAR2(10 BYTE),
  COMPONENT_TYPE VARCHAR2(8 BYTE),
  READONLY_FLG CHAR(1 BYTE) DEFAULT NULL
, PRIMARY KEY
  (
    SCREEN_ID,
    SYSTEM_ID,
    BUSINESS_ID,
    COMPONENT_KEY
  )
)
PARTITION BY LIST(BUSINESS_ID)
(
 PARTITION P_TZBRB VALUES('TZBRB')
    TABLESPACE "TZBRB"
    LOGGING 
    PCTFREE 10
    INITRANS 1
    MAXTRANS 255
    STORAGE
    (
      INITIAL 64K
      NEXT 64K
      MINEXTENTS 1
      MAXEXTENTS 2147483645
      PCTINCREASE 0
      BUFFER_POOL DEFAULT
    )
    NOCOMPRESS
, PARTITION P_UGBRB VALUES('UGBRB')
    TABLESPACE "UGBRB"
    LOGGING 
    PCTFREE 10
    INITRANS 1
    MAXTRANS 255
    STORAGE
    (
      INITIAL 64K
      MINEXTENTS 1
      MAXEXTENTS 2147483645
      BUFFER_POOL DEFAULT
    )
    NOCOMPRESS
)
;

