-- Unable to Render DDL with DBMS_METADATA using internal generator.
CREATE TABLE C_FORMATTER_MST
(
  FORMATTER_ID NUMBER(10, 0) NOT NULL,
  FORMATTER_STRING VARCHAR2(120 BYTE),
  SYSTEM_ID VARCHAR2(10 BYTE) NOT NULL,
  BUSINESS_ID VARCHAR2(10 BYTE) NOT NULL,
  MAKER_ID VARCHAR2(16 BYTE),
  CHECKER_ID VARCHAR2(16 BYTE),
  STATUS VARCHAR2(5 BYTE),
  LAST_MODIFIED TIMESTAMP(6),
  LAST_AUTHORIZED TIMESTAMP(6),
  ACTION VARCHAR2(10 BYTE),
  DELETED_FLAG VARCHAR2(1 BYTE),
  AUTHORIZED_INDICATOR VARCHAR2(1 BYTE),
  MESSAGE_KEY VARCHAR2(40 BYTE)
, PRIMARY KEY
  (
    FORMATTER_ID,
    SYSTEM_ID,
    BUSINESS_ID
  )
)
PARTITION BY LIST(BUSINESS_ID)
(
 PARTITION P_TZBRB VALUES('TZBRB')
    TABLESPACE "TZBRB"
    LOGGING 
    PCTFREE 10
    INITRANS 1
    MAXTRANS 255
    STORAGE
    (
      INITIAL 64K
      NEXT 64K
      MINEXTENTS 1
      MAXEXTENTS 2147483645
      PCTINCREASE 0
      BUFFER_POOL DEFAULT
    )
    NOCOMPRESS
, PARTITION P_UGBRB VALUES('UGBRB')
    TABLESPACE "UGBRB"
    LOGGING 
    PCTFREE 10
    INITRANS 1
    MAXTRANS 255
    STORAGE
    (
      INITIAL 64K
      MINEXTENTS 1
      MAXEXTENTS 2147483645
      BUFFER_POOL DEFAULT
    )
    NOCOMPRESS
)
;

