-- Unable to Render DDL with DBMS_METADATA using internal generator.

CREATE TABLE C_INTEREST_RATE_MST
(
  BUSINESS_ID VARCHAR2(20 BYTE) NOT NULL,
  PRODUCT_CD VARCHAR2(20 BYTE) NOT NULL,
  EFFECTIVE_DTM TIMESTAMP(6) NOT NULL,
  CCY VARCHAR2(5 BYTE) NOT NULL,
  CHANNEL VARCHAR2(20 BYTE) NOT NULL,
  CUSTOMER_SEGMENT VARCHAR2(20 BYTE) NOT NULL,
  TENURE_MONTH NUMBER(10, 0) NOT NULL,
  TENURE_DAY NUMBER(10, 0) NOT NULL,
  AMT_SLAB_FROM NUMBER(30, 3) NOT NULL,
  AMT_SLAB_TO NUMBER(30, 3) NOT NULL,
  INTEREST_RATE NUMBER(10, 7),
  INTEREST_VARIANCE NUMBER(3, 7),
  PENALTY_RATE NUMBER(3, 7),
  PENALTY_VARIANCE NUMBER(3, 7),
  TENURE_TYPE VARCHAR2(10 BYTE)
, PRIMARY KEY
  (
    BUSINESS_ID,
    PRODUCT_CD,
    EFFECTIVE_DTM,
    CCY,
    CHANNEL,
    CUSTOMER_SEGMENT,
    TENURE_MONTH,
    TENURE_DAY,
    AMT_SLAB_FROM,
    AMT_SLAB_TO
  )
)
PARTITION BY LIST(BUSINESS_ID)
(
 PARTITION P_TZBRB VALUES('TZBRB')
  TABLESPACE "TZBRB"
  LOGGING 
  PCTFREE 10
  INITRANS 1
  MAXTRANS 255
  STORAGE
    (
      INITIAL 64K
      NEXT 64K
      MINEXTENTS 1
      MAXEXTENTS 2147483645
      PCTINCREASE 0
      BUFFER_POOL DEFAULT
    )
    NOCOMPRESS
, PARTITION P_UGBRB VALUES('UGBRB')
  TABLESPACE "UGBRB"
  LOGGING 
  PCTFREE 10
  INITRANS 1
  MAXTRANS 255
  STORAGE
    (
      INITIAL 64K
      MINEXTENTS 1
      MAXEXTENTS 2147483645
      BUFFER_POOL DEFAULT
    )
    NOCOMPRESS
)
;

