-- Unable to Render DDL with DBMS_METADATA using internal generator.
CREATE TABLE C_MESSAGE_RES_MST
(
  LANGUAGE_ID VARCHAR2(5 BYTE) NOT NULL,
  MESSAGE_VALUE VARCHAR2(500 BYTE),
  SYSTEM_ID VARCHAR2(10 BYTE) NOT NULL,
  BUSINESS_ID VARCHAR2(10 BYTE) NOT NULL,
  MESSAGE_KEY VARCHAR2(40 BYTE) NOT NULL
, PRIMARY KEY
  (
    LANGUAGE_ID,
    SYSTEM_ID,
    BUSINESS_ID,
    MESSAGE_KEY
  )
)
PARTITION BY LIST(BUSINESS_ID)
(
 PARTITION P_TZBRB VALUES('TZBRB')
    TABLESPACE "TZBRB"
    LOGGING 
    PCTFREE 10
    INITRANS 1
    MAXTRANS 255
    STORAGE
    (
      INITIAL 64K
      NEXT 64K
      MINEXTENTS 1
      MAXEXTENTS 2147483645
      PCTINCREASE 0
      BUFFER_POOL DEFAULT
    )
    NOCOMPRESS
, PARTITION P_UGBRB VALUES('UGBRB')
    TABLESPACE "UGBRB"
    LOGGING 
    PCTFREE 10
    INITRANS 1
    MAXTRANS 255
    STORAGE
    (
      INITIAL 64K
      MINEXTENTS 1
      MAXEXTENTS 2147483645
      BUFFER_POOL DEFAULT
    )
    NOCOMPRESS
)
;

