-- Unable to Render DDL with DBMS_METADATA using internal generator.
CREATE TABLE C_PRODUCT_MST
(
  PRODUCT_CD VARCHAR2(20 BYTE) NOT NULL,
  BUSINESS_ID VARCHAR2(20 BYTE) NOT NULL,
  PRODUCT_DESC VARCHAR2(100 BYTE),
  PRODUCT_GROUP VARCHAR2(20 BYTE),
  PRODUCT_SUBGROUP VARCHAR2(10 BYTE),
  SOURCE_SYSTEM_ID VARCHAR2(10 BYTE),
  MODIFIED_BY VARCHAR2(20 BYTE),
  MODIFIED_DTM TIMESTAMP(6),
  AUTHORIZED_BY VARCHAR2(20 BYTE),
  AUTHORIZED_DTM TIMESTAMP(6),
  DELETE_FLG CHAR(1 BYTE),
  CURRENCY_CD VARCHAR2(3 BYTE) NOT NULL,
  TENURE_TYP VARCHAR2(30 BYTE),
  MIN_AMOUNT NUMBER(19, 3),
  MAX_AMOUNT NUMBER(19, 3),
  ESAVER_IND VARCHAR2(1 BYTE),
  INTERNET_ENABLED VARCHAR2(1 BYTE),
  INT_PAYOUT_FRQ VARCHAR2(20 BYTE),
  INT_COMPD_FRQ VARCHAR2(20 BYTE),
  SUPPORT_CHEQUE CHAR(1 BYTE)
, CONSTRAINT C_PRODUCT_MST_PK PRIMARY KEY
  (
    PRODUCT_CD,
    BUSINESS_ID,
    CURRENCY_CD
  )
)
PARTITION BY LIST(BUSINESS_ID)
(
 PARTITION P_TZBRB VALUES('TZBRB')
    TABLESPACE "TZBRB"
    LOGGING 
    PCTFREE 10
    INITRANS 1
    MAXTRANS 255
    STORAGE
    (
      INITIAL 64K
      NEXT 64K
      MINEXTENTS 1
      MAXEXTENTS 2147483645
      PCTINCREASE 0
      BUFFER_POOL DEFAULT
    )
    NOCOMPRESS
, PARTITION P_UGBRB VALUES('UGBRB')
    TABLESPACE "UGBRB"
    LOGGING 
    PCTFREE 10
    INITRANS 1
    MAXTRANS 255
    STORAGE
    (
      INITIAL 64K
      MINEXTENTS 1
      MAXEXTENTS 2147483645
      BUFFER_POOL DEFAULT
    )
    NOCOMPRESS
)
;

