-- Unable to Render DDL with DBMS_METADATA using internal generator.
CREATE TABLE S_FUNCTION_CONFIG
(
  BUSINESS_ID VARCHAR2(10 BYTE) NOT NULL,
  SYSTEM_ID VARCHAR2(10 BYTE) NOT NULL,
  ACTIVITY_ID VARCHAR2(40 BYTE) NOT NULL,
  TXN_LIMIT_TYP VARCHAR2(20 BYTE),
  FEATURE_BLKOUT_FLG CHAR(1 BYTE),
  ADV_TXT_FLG CHAR(1 BYTE),
  ADV_IMG_TOP_FLG CHAR(1 BYTE),
  ADV_IMG_RIGHTNAV_FLG CHAR(1 BYTE),
  MODIFIED_DTM TIMESTAMP(6),
  MODIFIED_BY VARCHAR2(20 BYTE)
, PRIMARY KEY
  (
    BUSINESS_ID,
    SYSTEM_ID,
    ACTIVITY_ID
  )
)
PARTITION BY LIST(BUSINESS_ID)
(
PARTITION P_TZBRB VALUES('TZBRB')
    TABLESPACE "TZBRB"
    LOGGING 
    PCTFREE 10
    INITRANS 1
    MAXTRANS 255
    STORAGE
    (
      INITIAL 64K
      NEXT 64K
      MINEXTENTS 1
      MAXEXTENTS 2147483645
      PCTINCREASE 0
      BUFFER_POOL DEFAULT
    )
    NOCOMPRESS
, PARTITION P_UGBRB VALUES('UGBRB')
    TABLESPACE "UGBRB"
    LOGGING 
    PCTFREE 10
    INITRANS 1
    MAXTRANS 255
    STORAGE
    (
      INITIAL 64K
      MINEXTENTS 1
      MAXEXTENTS 2147483645
      BUFFER_POOL DEFAULT
    )
    NOCOMPRESS
)
;

