-- Unable to Render DDL with DBMS_METADATA using internal generator.
CREATE TABLE S_SES_SUMMARY_HST
(
  BUSINESS_ID VARCHAR2(10 BYTE) NOT NULL,
  SYSTEM_ID VARCHAR2(10 BYTE) NOT NULL,
  USER_ID VARCHAR2(20 BYTE) NOT NULL,
  SESS_ID VARCHAR2(40 BYTE) NOT NULL,
  TXN_TYP VARCHAR2(20 BYTE) NOT NULL,
  TXN_TIME TIMESTAMP(6) NOT NULL,
  ACCT_FROM VARCHAR2(40 BYTE),
  ACCT_TO VARCHAR2(40 BYTE),
  AMOUNT NUMBER(19, 3),
  STATUS VARCHAR2(20 BYTE),
  REF_NO VARCHAR2(40 BYTE),
  DETAILS VARCHAR2(1000 CHAR)
)
PARTITION BY LIST(BUSINESS_ID)
(
 PARTITION P_TZBRB VALUES('TZBRB')
    TABLESPACE "TZBRB"
    LOGGING 
    PCTFREE 10
    INITRANS 1
    MAXTRANS 255
    STORAGE
    (
      INITIAL 64K
      NEXT 64K
      MINEXTENTS 1
      MAXEXTENTS 2147483645
      PCTINCREASE 0
      BUFFER_POOL DEFAULT
    )
    NOCOMPRESS
, PARTITION P_UGBRB VALUES('UGBRB')
    TABLESPACE "UGBRB"
    LOGGING 
    PCTFREE 10
    INITRANS 1
    MAXTRANS 255
    STORAGE
    (
      INITIAL 64K
      MINEXTENTS 1
      MAXEXTENTS 2147483645
      BUFFER_POOL DEFAULT
    )
    NOCOMPRESS
)
;

