-- Unable to Render DDL with DBMS_METADATA using internal generator.
CREATE TABLE S_SYSPARAM_MST
(
  BUSINESS_ID VARCHAR2(10 BYTE) NOT NULL,
  SYSTEM_ID VARCHAR2(10 BYTE) NOT NULL,
  PARAM_ID VARCHAR2(50 BYTE) NOT NULL,
  PARAM_VALUE VARCHAR2(200 BYTE) NOT NULL,
  PARAM_COMPONENT_KEY VARCHAR2(25 BYTE),
  ACTIVITY_ID VARCHAR2(40 BYTE) NOT NULL,
  SYSTEM_MAINTAIN CHAR(1 BYTE),
  DISP_TYPE VARCHAR2(10 BYTE),
  MODIFIED_DTM TIMESTAMP(6),
  MODIFIED_BY VARCHAR2(20 BYTE),
  AUTHORISED_BY VARCHAR2(20 BYTE),
  AUTHORISED_DTM TIMESTAMP(6),
  DELETE_FLG CHAR(1 BYTE),
  PARAM_DESC VARCHAR2(200 BYTE),
  CREATED_BY VARCHAR2(20 BYTE),
  CREATED_DTM TIMESTAMP(6)
, CONSTRAINT PK_S_SYSPARAM_MST PRIMARY KEY
  (
    BUSINESS_ID,
    SYSTEM_ID,
    PARAM_ID,
    ACTIVITY_ID
  )
)
PARTITION BY LIST(BUSINESS_ID)
(
 PARTITION P_TZBRB VALUES('TZBRB')
    TABLESPACE "TZBRB"
    LOGGING 
    PCTFREE 10
    INITRANS 1
    MAXTRANS 255
    STORAGE
    (
      INITIAL 64K
      NEXT 64K
      MINEXTENTS 1
      MAXEXTENTS 2147483645
      PCTINCREASE 0
      BUFFER_POOL DEFAULT
    )
    NOCOMPRESS
, PARTITION P_UGBRB VALUES('UGBRB')
    TABLESPACE "UGBRB"
    LOGGING 
    PCTFREE 10
    INITRANS 1
    MAXTRANS 255
    STORAGE
    (
      INITIAL 64K
      MINEXTENTS 1
      MAXEXTENTS 2147483645
      BUFFER_POOL DEFAULT
    )
    NOCOMPRESS
)
;

