-- Unable to Render DDL with DBMS_METADATA using internal generator.
CREATE TABLE S_URL_BUSINESS_MAP_MST
(
  BUSINESS_ID VARCHAR2(10 BYTE) NOT NULL,
  SYSTEM_ID VARCHAR2(10 BYTE) NOT NULL,
  URL_PATTERN VARCHAR2(400 BYTE) NOT NULL,
  LANGUAGE_ID VARCHAR2(18 BYTE) NOT NULL,
  SEGMENT_ID VARCHAR2(10 BYTE)
, CONSTRAINT PK_S_URL_BUSINESS_MAP_MST PRIMARY KEY
  (
    BUSINESS_ID,
    SYSTEM_ID,
    URL_PATTERN
  )
)
PARTITION BY LIST(BUSINESS_ID)
(
 PARTITION P_TZBRB VALUES('TZBRB')
    TABLESPACE "TZBRB"
    LOGGING 
    PCTFREE 10
    INITRANS 1
    MAXTRANS 255
    STORAGE
    (
      INITIAL 64K
      NEXT 64K
      MINEXTENTS 1
      MAXEXTENTS 2147483645
      PCTINCREASE 0
      BUFFER_POOL DEFAULT
    )
    NOCOMPRESS
, PARTITION P_UGBRB VALUES('UGBRB')
    TABLESPACE "UGBRB"
    LOGGING 
    PCTFREE 10
    INITRANS 1
    MAXTRANS 255
    STORAGE
    (
      INITIAL 64K
      MINEXTENTS 1
      MAXEXTENTS 2147483645
      BUFFER_POOL DEFAULT
    )
    NOCOMPRESS
)
;

