
Insert into C_MESSAGE_RES_MST (LANGUAGE_ID,MESSAGE_VALUE,SYSTEM_ID,BUSINESS_ID,MESSAGE_KEY) values ('EN','InternalError','UB','TZBRB','BEM08766');

Insert into C_MESSAGE_MST (SYSTEM_ID,BUSINESS_ID,CATEGORY,MESSAGE_KEY,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,SOURCE_SYSTEM_ID) values ('UB','TZBRB','FATAL','BEM08766',null,null,null,null,null,null);

Insert into C_MESSAGE_RES_MST (LANGUAGE_ID,MESSAGE_VALUE,SYSTEM_ID,BUSINESS_ID,MESSAGE_KEY)
values ('EN','BadTokenType','UB','TZBRB','BEM08767');
Insert into C_MESSAGE_MST (SYSTEM_ID,BUSINESS_ID,CATEGORY,MESSAGE_KEY,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG
,SOURCE_SYSTEM_ID) values ('UB','TZBRB','FATAL','BEM08767',null,null,null,null,null,null);

Insert into C_MESSAGE_RES_MST (LANGUAGE_ID,MESSAGE_VALUE,SYSTEM_ID,BUSINESS_ID,MESSAGE_KEY)
values ('EN','UnknownTokenID','UB','TZBRB','BEM08768');
Insert into C_MESSAGE_MST (SYSTEM_ID,BUSINESS_ID,CATEGORY,MESSAGE_KEY,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG
,SOURCE_SYSTEM_ID) values ('UB','TZBRB','FATAL','BEM08768',null,null,null,null,null,null);


Insert into C_MESSAGE_RES_MST (LANGUAGE_ID,MESSAGE_VALUE,SYSTEM_ID,BUSINESS_ID,MESSAGE_KEY)
values ('EN','BadDate','UB','TZBRB','BEM08769');
Insert into C_MESSAGE_MST (SYSTEM_ID,BUSINESS_ID,CATEGORY,MESSAGE_KEY,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG
,SOURCE_SYSTEM_ID) values ('UB','TZBRB','FATAL','BEM08769',null,null,null,null,null,null);


Insert into C_MESSAGE_RES_MST (LANGUAGE_ID,MESSAGE_VALUE,SYSTEM_ID,BUSINESS_ID,MESSAGE_KEY)
values ('EN','TokenAlreadyAssigned','UB','TZBRB','BEM08770');
Insert into C_MESSAGE_MST (SYSTEM_ID,BUSINESS_ID,CATEGORY,MESSAGE_KEY,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG
,SOURCE_SYSTEM_ID) values ('UB','TZBRB','FATAL','BEM08770',null,null,null,null,null,null);

Insert into C_MESSAGE_RES_MST (LANGUAGE_ID,MESSAGE_VALUE,SYSTEM_ID,BUSINESS_ID,MESSAGE_KEY)
values ('EN','UnknownSubject','UB','TZBRB','BEM08771');
Insert into C_MESSAGE_MST (SYSTEM_ID,BUSINESS_ID,CATEGORY,MESSAGE_KEY,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG
,SOURCE_SYSTEM_ID) values ('UB','TZBRB','FATAL','BEM08771',null,null,null,null,null,null);

Insert into C_MESSAGE_RES_MST (LANGUAGE_ID,MESSAGE_VALUE,SYSTEM_ID,BUSINESS_ID,MESSAGE_KEY)
values ('EN','SubjectInUse','UB','TZBRB','BEM08772');
Insert into C_MESSAGE_MST (SYSTEM_ID,BUSINESS_ID,CATEGORY,MESSAGE_KEY,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG
,SOURCE_SYSTEM_ID) values ('UB','TZBRB','FATAL','BEM08772',null,null,null,null,null,null);

Insert into C_MESSAGE_RES_MST (LANGUAGE_ID,MESSAGE_VALUE,SYSTEM_ID,BUSINESS_ID,MESSAGE_KEY)
values ('EN','UnknownAlias','UB','TZBRB','BEM08773');
Insert into C_MESSAGE_MST (SYSTEM_ID,BUSINESS_ID,CATEGORY,MESSAGE_KEY,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG
,SOURCE_SYSTEM_ID) values ('UB','TZBRB','FATAL','BEM08773',null,null,null,null,null,null);

Insert into C_MESSAGE_RES_MST (LANGUAGE_ID,MESSAGE_VALUE,SYSTEM_ID,BUSINESS_ID,MESSAGE_KEY)
values ('EN','TokenExists','UB','TZBRB','BEM08774');
Insert into C_MESSAGE_MST (SYSTEM_ID,BUSINESS_ID,CATEGORY,MESSAGE_KEY,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG
,SOURCE_SYSTEM_ID) values ('UB','TZBRB','FATAL','BEM08774',null,null,null,null,null,null);

Insert into C_MESSAGE_RES_MST (LANGUAGE_ID,MESSAGE_VALUE,SYSTEM_ID,BUSINESS_ID,MESSAGE_KEY)
values ('EN','InvalidAlias','UB','TZBRB','BEM08775');
Insert into C_MESSAGE_MST (SYSTEM_ID,BUSINESS_ID,CATEGORY,MESSAGE_KEY,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG
,SOURCE_SYSTEM_ID) values ('UB','TZBRB','FATAL','BEM08775',null,null,null,null,null,null);



Insert into C_MESSAGE_RES_MST (LANGUAGE_ID,MESSAGE_VALUE,SYSTEM_ID,BUSINESS_ID,MESSAGE_KEY)
values ('EN','InvalidChallengeId','UB','TZBRB','BEM08776');
Insert into C_MESSAGE_MST (SYSTEM_ID,BUSINESS_ID,CATEGORY,MESSAGE_KEY,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG
,SOURCE_SYSTEM_ID) values ('UB','TZBRB','FATAL','BEM08776',null,null,null,null,null,null);


Insert into C_MESSAGE_RES_MST (LANGUAGE_ID,MESSAGE_VALUE,SYSTEM_ID,BUSINESS_ID,MESSAGE_KEY)
values ('EN','InvalidNewPin','UB','TZBRB','BEM08777');
Insert into C_MESSAGE_MST (SYSTEM_ID,BUSINESS_ID,CATEGORY,MESSAGE_KEY,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG
,SOURCE_SYSTEM_ID) values ('UB','TZBRB','FATAL','BEM08777',null,null,null,null,null,null);


Insert into C_MESSAGE_RES_MST (LANGUAGE_ID,MESSAGE_VALUE,SYSTEM_ID,BUSINESS_ID,MESSAGE_KEY)
values ('EN','InvalidQuestionId','UB','TZBRB','BEM08778');
Insert into C_MESSAGE_MST (SYSTEM_ID,BUSINESS_ID,CATEGORY,MESSAGE_KEY,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG
,SOURCE_SYSTEM_ID) values ('UB','TZBRB','FATAL','BEM08778',null,null,null,null,null,null);


Insert into C_MESSAGE_RES_MST (LANGUAGE_ID,MESSAGE_VALUE,SYSTEM_ID,BUSINESS_ID,MESSAGE_KEY)
values ('EN','InvalidOldPin','UB','TZBRB','BEM08779');
Insert into C_MESSAGE_MST (SYSTEM_ID,BUSINESS_ID,CATEGORY,MESSAGE_KEY,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG
,SOURCE_SYSTEM_ID) values ('UB','TZBRB','FATAL','BEM08779',null,null,null,null,null,null);


Insert into C_MESSAGE_RES_MST (LANGUAGE_ID,MESSAGE_VALUE,SYSTEM_ID,BUSINESS_ID,MESSAGE_KEY)
values ('EN','InvalidResponse','UB','TZBRB','BEM08780');
Insert into C_MESSAGE_MST (SYSTEM_ID,BUSINESS_ID,CATEGORY,MESSAGE_KEY,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG
,SOURCE_SYSTEM_ID) values ('UB','TZBRB','FATAL','BEM08780',null,null,null,null,null,null);


Insert into C_MESSAGE_RES_MST (LANGUAGE_ID,MESSAGE_VALUE,SYSTEM_ID,BUSINESS_ID,MESSAGE_KEY)
values ('EN','InvalidPinLifetime','UB','TZBRB','BEM08781');
Insert into C_MESSAGE_MST (SYSTEM_ID,BUSINESS_ID,CATEGORY,MESSAGE_KEY,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG
,SOURCE_SYSTEM_ID) values ('UB','TZBRB','FATAL','BEM08781',null,null,null,null,null,null);

Insert into C_MESSAGE_RES_MST (LANGUAGE_ID,MESSAGE_VALUE,SYSTEM_ID,BUSINESS_ID,MESSAGE_KEY)
values ('EN','ChallengeNotFound','UB','TZBRB','BEM08782');
Insert into C_MESSAGE_MST (SYSTEM_ID,BUSINESS_ID,CATEGORY,MESSAGE_KEY,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG
,SOURCE_SYSTEM_ID) values ('UB','TZBRB','FATAL','BEM08782',null,null,null,null,null,null);

Insert into C_MESSAGE_RES_MST (LANGUAGE_ID,MESSAGE_VALUE,SYSTEM_ID,BUSINESS_ID,MESSAGE_KEY)
values ('EN','QuestionNotFound','UB','TZBRB','BEM08783');
Insert into C_MESSAGE_MST (SYSTEM_ID,BUSINESS_ID,CATEGORY,MESSAGE_KEY,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG
,SOURCE_SYSTEM_ID) values ('UB','TZBRB','FATAL','BEM08783',null,null,null,null,null,null);

Insert into C_MESSAGE_RES_MST (LANGUAGE_ID,MESSAGE_VALUE,SYSTEM_ID,BUSINESS_ID,MESSAGE_KEY)
values ('EN','Unknown','UB','TZBRB','BEM08784');
Insert into C_MESSAGE_MST (SYSTEM_ID,BUSINESS_ID,CATEGORY,MESSAGE_KEY,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG
,SOURCE_SYSTEM_ID) values ('UB','TZBRB','FATAL','BEM08784',null,null,null,null,null,null);

Insert into C_MESSAGE_RES_MST (LANGUAGE_ID,MESSAGE_VALUE,SYSTEM_ID,BUSINESS_ID,MESSAGE_KEY)
values ('EN','UserAliasNotActive','UB','TZBRB','BEM08788');
Insert into C_MESSAGE_MST (SYSTEM_ID,BUSINESS_ID,CATEGORY,MESSAGE_KEY,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG
,SOURCE_SYSTEM_ID) values ('UB','TZBRB','FATAL','BEM08788',null,null,null,null,null,null);

Insert into C_MESSAGE_RES_MST (LANGUAGE_ID,MESSAGE_VALUE,SYSTEM_ID,BUSINESS_ID,MESSAGE_KEY)
values ('EN','UserAliasNotRegisterAtMCE','UB','TZBRB','BEM08789');
Insert into C_MESSAGE_MST (SYSTEM_ID,BUSINESS_ID,CATEGORY,MESSAGE_KEY,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG
,SOURCE_SYSTEM_ID) values ('UB','TZBRB','FATAL','BEM08789',null,null,null,null,null,null);

Insert into C_MESSAGE_RES_MST (LANGUAGE_ID,MESSAGE_VALUE,SYSTEM_ID,BUSINESS_ID,MESSAGE_KEY)
values ('EN','Mobile number length in configuration table must be a integer digit','UB','TZBRB','BEM08790');
Insert into C_MESSAGE_MST (SYSTEM_ID,BUSINESS_ID,CATEGORY,MESSAGE_KEY,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG
,SOURCE_SYSTEM_ID) values ('UB','TZBRB','FATAL','BEM08790',null,null,null,null,null,null);

Insert into C_MESSAGE_RES_MST (LANGUAGE_ID,MESSAGE_VALUE,SYSTEM_ID,BUSINESS_ID,MESSAGE_KEY)
values ('EN','Mobile number length can not less than {0}','UB','TZBRB','BEM08791');
Insert into C_MESSAGE_MST (SYSTEM_ID,BUSINESS_ID,CATEGORY,MESSAGE_KEY,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG
,SOURCE_SYSTEM_ID) values ('UB','TZBRB','FATAL','BEM08791',null,null,null,null,null,null);

Insert into C_MESSAGE_RES_MST (LANGUAGE_ID,MESSAGE_VALUE,SYSTEM_ID,BUSINESS_ID,MESSAGE_KEY)
values ('EN','Customer mobile number has already registered','UB','TZBRB','BEM08792');
Insert into C_MESSAGE_MST (SYSTEM_ID,BUSINESS_ID,CATEGORY,MESSAGE_KEY,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG
,SOURCE_SYSTEM_ID) values ('UB','TZBRB','FATAL','BEM08792',null,null,null,null,null,null);


Insert into C_MESSAGE_RES_MST (LANGUAGE_ID,MESSAGE_VALUE,SYSTEM_ID,BUSINESS_ID,MESSAGE_KEY)
values ('EN','Invalid phone number or unsupported mobile network','UB','TZBRB','BEM08793');
Insert into C_MESSAGE_MST (SYSTEM_ID,BUSINESS_ID,CATEGORY,MESSAGE_KEY,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG
,SOURCE_SYSTEM_ID) values ('UB','TZBRB','FATAL','BEM08793',null,null,null,null,null,null);

commit;
