
-----------------------		URL INSERTION QUERY FOR ZWBRB - SIT   --------------------------
DELETE FROM S_URL_BUSINESS_MAP_MST WHERE SYSTEM_ID='MB' AND BUSINESS_ID='ZWBRB' AND URL_PATTERN='https://s04t.wload.global:29100/bmg';

INSERT INTO S_URL_BUSINESS_MAP_MST (SYSTEM_ID, BUSINESS_ID, URL_PATTERN, LANGUAGE_ID) VALUES ('MB','ZWBRB','https://s04t.wload.global:29100/bmg','EN');
COMMIT;
