-- Unable to Render DDL with DBMS_METADATA using internal generator.


CREATE TABLE C_BILLER_MST
(
  BUSINESS_ID VARCHAR2(10 BYTE) NOT NULL,
  BILLER_ID VARCHAR2(40 BYTE) NOT NULL,
  BILLER_NM VARCHAR2(80 BYTE),
  BILLER_CATEGORY_ID VARCHAR2(40 BYTE),
  BILLER_CATEGORY_NM VARCHAR2(80 BYTE),
  PRESENTMENT_FLG CHAR(1 BYTE),
  REF_NO_TEXT_1 VARCHAR2(80 BYTE),
  REF_NO_TEXT_2 VARCHAR2(80 BYTE),
  TRANSACTION_FEE NUMBER(19, 3),
  BILL_AGGREGATOR_ID VARCHAR2(40 BYTE),
  CURRENCY VARCHAR2(3 BYTE),
  SUPPORT_CREDITCARD_FLG CHAR(1 BYTE),
  ONLINE_BILLER_FLG CHAR(1 BYTE),
  PAYEE_REF_FIELDS VARCHAR2(20 BYTE),
  MOBILE_DENOMINATION VARCHAR2(200 BYTE),
  SERVICE_TYPE VARCHAR2(50 BYTE),
  EXTERNAL_BILLER_ID VARCHAR2(40 BYTE),
  MIN_PAYMENT_AMOUNT NUMBER(12, 2),
  BRANCH_CODE VARCHAR2(10 BYTE),
  BILLER_ACCOUNT_NUMBER VARCHAR2(30 BYTE),
  REF_NO_KEY_1 VARCHAR2(40 BYTE),
  REF_NO_KEY_2 VARCHAR2(40 BYTE),
  MAX_PAYMENT_AMOUNT NUMBER(12, 2),
  BILLHOLDER_REQUIRED VARCHAR2(1 BYTE),
  PAYEE_SUPPORT VARCHAR2(1 BYTE)
, PRIMARY KEY
  (
    BUSINESS_ID,
    BILLER_ID
  )
)
PARTITION BY LIST(BUSINESS_ID)
(
 PARTITION P_TZBRB VALUES('TZBRB')
 TABLESPACE "TZBRB"
 LOGGING 
 PCTFREE 10
 INITRANS 1
 MAXTRANS 255
 STORAGE
    (
      INITIAL 64K
      NEXT 64K
      MINEXTENTS 1
      MAXEXTENTS 2147483645
      PCTINCREASE 0
      BUFFER_POOL DEFAULT
    )
    NOCOMPRESS
, PARTITION P_UGBRB VALUES('UGBRB')
  TABLESPACE "UGBRB"
  LOGGING 
  PCTFREE 10
  INITRANS 1
  MAXTRANS 255
  STORAGE
    (
      INITIAL 64K
      MINEXTENTS 1
      MAXEXTENTS 2147483645
      BUFFER_POOL DEFAULT
    )
    NOCOMPRESS
)
;

