-- Unable to Render DDL with DBMS_METADATA using internal generator.

DROP TABLE S_LIMIT_CUST_TOTAL;

CREATE TABLE S_LIMIT_CUST_TOTAL
(
  BUSINESS_ID VARCHAR2(10 BYTE) NOT NULL,
  SYSTEM_ID VARCHAR2(10 BYTE) NOT NULL,
  TXN_LIMIT_TYP VARCHAR2(20 BYTE) NOT NULL,
  CUST_ID VARCHAR2(40 BYTE) NOT NULL,
  TXN_DT TIMESTAMP(6),
  DAILY_TOTAL_AMT NUMBER(15, 3),
  TXN_COUNT NUMBER(10, 0)
, CONSTRAINT PK_S_LIMIT_CUST_TOTAL PRIMARY KEY
  (
    BUSINESS_ID,
    SYSTEM_ID,
    TXN_LIMIT_TYP,
    CUST_ID
  )
)
PARTITION BY LIST(BUSINESS_ID)
(
 PARTITION P_TZBRB VALUES('TZBRB')
    TABLESPACE "TZBRB"
    LOGGING 
    PCTFREE 10
    INITRANS 1
    MAXTRANS 255
    STORAGE
    (
      INITIAL 64K
      NEXT 64K
      MINEXTENTS 1
      MAXEXTENTS 2147483645
      PCTINCREASE 0
      BUFFER_POOL DEFAULT
    )
    NOCOMPRESS
, PARTITION P_UGBRB VALUES('UGBRB')
    TABLESPACE "UGBRB"
    LOGGING 
    PCTFREE 10
    INITRANS 1
    MAXTRANS 255
    STORAGE
    (
      INITIAL 64K
      MINEXTENTS 1
      MAXEXTENTS 2147483645
      BUFFER_POOL DEFAULT
    )
    NOCOMPRESS
)
;

