DROP TABLE C_BANKROUTING_MST;
DROP TABLE C_BILLER_MST;
DROP TABLE C_BUSINESS_MST;
DROP TABLE C_COMPONENT_RES_MST;
DROP TABLE C_COMPONENT_MST;
DROP TABLE C_FORMATTER_MST;
DROP TABLE C_INTEREST_RATE_MST;
DROP TABLE C_LISTVALUE_RES_MST;
DROP TABLE C_LISTVALUE_MST;
DROP TABLE C_MESSAGE_RES_MST;
DROP TABLE C_MESSAGE_MST;
DROP TABLE C_PRODUCT_MST;
DROP TABLE S_FUNCTION_CONFIG;
DROP TABLE S_LIMIT_CUST_TOTAL;
DROP TABLE S_SES_SUMMARY_HST;
DROP TABLE S_SYSPARAM_MST;
DROP TABLE S_TXN_CUT_OFF_MST;
DROP TABLE S_URL_BUSINESS_MAP_MST;


BEGIN
DBMS_SCHEDULER.DROP_JOB ('data_transfer_job_UB');
END;
/

DROP PACKAGE DELIVER_DATA_UB;

DROP SYNONYM C_INTEREST_RATE_MST_ADMDB;
DROP SYNONYM C_COMPONENT_MST_ADMDB;
DROP SYNONYM C_COMPONENT_RES_MST_ADMDB;
DROP SYNONYM C_FORMATTER_MST_ADMDB;
DROP SYNONYM C_BUSINESS_MST_ADMDB;
DROP SYNONYM C_PRODUCT_MST_ADMDB;
DROP SYNONYM C_LISTVALUE_MST_ADMDB;
DROP SYNONYM C_LISTVALUE_RES_MST_ADMDB;
DROP SYNONYM C_MESSAGE_MST_ADMDB;
DROP SYNONYM C_MESSAGE_RES_MST_ADMDB;

DROP DATABASE LINK "SHM_BOC_LINK";

COMMIT;
