------------- BEM ENDPOINTS - PROD  ------------------------
UPDATE S_SYSPARAM_MST SET PARAM_VALUE = 'https://22.126.64.153:443/tcvm'
WHERE PARAM_ID = 'DR_FinancialTransactionProcessing_EndPoint'
AND SYSTEM_ID = 'UB'
AND BUSINESS_ID = 'KEBRB';

UPDATE S_SYSPARAM_MST SET PARAM_VALUE = 'https://22.126.64.153:443/tcvm'
WHERE PARAM_ID = 'DR_IndividualCustomerManagement_EndPoint'
AND SYSTEM_ID = 'UB'
AND BUSINESS_ID = 'KEBRB';

UPDATE S_SYSPARAM_MST SET PARAM_VALUE = 'https://22.126.64.153:443/tcvm'
WHERE PARAM_ID = 'DR_ProblemManagement_EndPoint'
AND SYSTEM_ID = 'UB'
AND BUSINESS_ID = 'KEBRB';

UPDATE S_SYSPARAM_MST SET PARAM_VALUE = 'https://22.126.64.153:443/tcvm'
WHERE PARAM_ID = 'DR_PinManagement_EndPoint'
AND SYSTEM_ID = 'UB'
AND BUSINESS_ID = 'KEBRB';

UPDATE S_SYSPARAM_MST SET PARAM_VALUE = 'https://22.126.64.153:443/tcvm'
WHERE PARAM_ID = 'DR_HelloMoneyCustomerManagement_EndPoint'
AND SYSTEM_ID = 'UB'
AND BUSINESS_ID = 'KEBRB';

UPDATE S_SYSPARAM_MST SET PARAM_VALUE = 'https://22.126.64.153:443/tcvm'
WHERE PARAM_ID = 'DR_AccountManagement_EndPoint'
AND SYSTEM_ID = 'UB'
AND BUSINESS_ID = 'KEBRB';

UPDATE S_SYSPARAM_MST SET PARAM_VALUE = 'https://22.126.64.153:443/tcvm'
WHERE PARAM_ID = 'DR_AccountMandateManagement_EndPoint'
AND SYSTEM_ID = 'UB'
AND BUSINESS_ID = 'KEBRB';

UPDATE S_SYSPARAM_MST SET PARAM_VALUE = 'https://22.126.64.153:443/tcvm'
WHERE PARAM_ID = 'DR_AccountReporting_EndPoint'
AND SYSTEM_ID = 'UB'
AND BUSINESS_ID = 'KEBRB';

UPDATE S_SYSPARAM_MST SET PARAM_VALUE = 'https://22.126.64.153:443/tcvm'
WHERE PARAM_ID = 'DR_BeneficiaryManagement_EndPoint'
AND SYSTEM_ID = 'UB'
AND BUSINESS_ID = 'KEBRB';

UPDATE S_SYSPARAM_MST SET PARAM_VALUE = 'https://22.126.64.153:443/tcvm'
WHERE PARAM_ID = 'DR_CheckBookManagement_EndPoint'
AND SYSTEM_ID = 'UB'
AND BUSINESS_ID = 'KEBRB';

UPDATE S_SYSPARAM_MST SET PARAM_VALUE = 'https://22.126.64.153:443/tcvm'
WHERE PARAM_ID = 'DR_NotificationService_EndPoint'
AND SYSTEM_ID = 'UB'
AND BUSINESS_ID = 'KEBRB';

commit;