
-----------------------		URL INSERTION QUERY FOR BWBRB - UAT   --------------------------
DELETE FROM S_URL_BUSINESS_MAP_MST WHERE SYSTEM_ID='MB' AND BUSINESS_ID='BWBRB' AND URL_PATTERN='https://cs1t.wload.barclays.co.uk:22601/bmg';

INSERT INTO S_URL_BUSINESS_MAP_MST (SYSTEM_ID, BUSINESS_ID, URL_PATTERN, LANGUAGE_ID, SEGMENT_ID) VALUES ('MB','BWBRB','https://cs1t.wload.barclays.co.uk:22601/bmg','EN','MASS');
COMMIT;