
-----------------------		URL INSERTION QUERY FOR TZBRB - PRODUCTION   --------------------------
DELETE FROM S_URL_BUSINESS_MAP_MST  WHERE SYSTEM_ID='MB' AND BUSINESS_ID='TZBRB' AND URL_PATTERN='https://www.tz.secure.barclays.com/bmg';

INSERT INTO S_URL_BUSINESS_MAP_MST (SYSTEM_ID, BUSINESS_ID, URL_PATTERN, LANGUAGE_ID) VALUES ('MB','TZBRB','https://www.tz.secure.barclays.com/bmg','EN');

DELETE FROM S_URL_BUSINESS_MAP_MST  WHERE SYSTEM_ID='MB' AND BUSINESS_ID='TZBRB' AND URL_PATTERN='https://tzc2bir-dr.barclays.intranet/bmg';

DELETE FROM S_URL_BUSINESS_MAP_MST  WHERE SYSTEM_ID='MB' AND BUSINESS_ID='TZBRB' AND URL_PATTERN='https://tzc2bir-live.barclays.intranet/bmg';

INSERT INTO S_URL_BUSINESS_MAP_MST (SYSTEM_ID, BUSINESS_ID, URL_PATTERN, LANGUAGE_ID) VALUES ('MB','TZBRB','https://tzc2bir-live.barclays.intranet/bmg','EN');

COMMIT;
