---------- Delete Records start ------

DELETE FROM C_LISTVALUE_MST WHERE BUSINESS_ID='GHBRB' and SYSTEM_ID='UB';

DELETE FROM C_LISTVALUE_RES_MST WHERE BUSINESS_ID='GHBRB' and SYSTEM_ID='UB';

---------- Insert Records Start -------


---------------  C_BIZ_FUNC_MMAP  ------

	DELETE  FROM C_BIZ_FUNC_MMAP where BUSINESS_ID='GHBRB' and SYSTEM_ID='UB';

	INSERT INTO  C_BIZ_FUNC_MMAP (SELECT BUSINESS_ID, ACTIVITY_ID, 'UB', FROM_TIME,  TO_TIME, HOLIDAY_ALLOWED_FLG,  BLOCKED_FLG   FROM C_BIZ_FUNC_MMAP   WHERE SYSTEM_ID = 'MB' AND BUSINESS_ID = 'GHBRB');

	DELETE FROM C_BIZ_FUNC_MMAP where BUSINESS_ID='GHBRB' and SYSTEM_ID='UB' AND ACTIVITY_ID='PMT_FT_MRC_PAYEE';

	INSERT INTO C_BIZ_FUNC_MMAP (BUSINESS_ID,ACTIVITY_ID,SYSTEM_ID,FROM_TIME,TO_TIME,HOLIDAY_ALLOWED_FLG,BLOCKED_FLG) values ('GHBRB','PMT_FT_MRC_PAYEE','UB',null,null,'N','N');

	DELETE FROM C_BIZ_FUNC_MMAP where BUSINESS_ID='GHBRB' and SYSTEM_ID='UB' AND ACTIVITY_ID='PMT_FT_BKD_PAYEE';

	INSERT INTO C_BIZ_FUNC_MMAP (BUSINESS_ID,ACTIVITY_ID,SYSTEM_ID,FROM_TIME,TO_TIME,HOLIDAY_ALLOWED_FLG,BLOCKED_FLG) values ('GHBRB','PMT_FT_BKD_PAYEE','UB',null,null,'N','N');
	
-----------C_LISTVALUE_MST-----------

INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) VALUES ('UB','GHBRB','SYS_PARAM_BNF','VIEW_MAX_BILLER_SIZE',null,null,'N',null,null,null,SYSDATE,'N','Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) VALUES ('UB','GHBRB','SYS_PARAM_BNF','PAYEE_NICK_LENGTHMAX',null,null,'N',null,null,null,SYSDATE,'N','Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) VALUES ('UB','GHBRB','SYS_PARAM_BNF','VIEW_MAX_BENFCR',null,null,'N',null,null,null,SYSDATE,'N','Y');

INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) VALUES ('UB','GHBRB','SYS_PARAM_BP','BILLPAY_MAX_AMT',null,null,'N',null,null,null,SYSDATE,'N','Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) VALUES ('UB','GHBRB','SYS_PARAM_BP','BILLPAY_MIN_AMT',null,null,'N',null,null,null,SYSDATE,'N','Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) VALUES ('UB','GHBRB','SYS_PARAM_BP','BILLPAY_MAX_DAYAMT',null,null,'N',null,null,null,SYSDATE,'N','Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) VALUES ('UB','GHBRB','SYS_PARAM_BP','BILLPAY_MAX_TXS',null,null,'N',null,null,null,SYSDATE,'N','Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) VALUES ('UB','GHBRB','SYS_PARAM_BP','POOL_AC_BILL_PAY',null,null,'N',null,null,null,null,'N','Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) VALUES ('UB','GHBRB','SYS_PARAM_BP','LAST_PAID_BILL_LIST',null,null,'N',null,null,null,SYSDATE,'N','Y');

INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) VALUES ('UB','GHBRB','SYS_PARAM_CS','CS_MIN_AMT',null,null,'N',null,SYSDATE,null,SYSDATE,'N','Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) VALUES ('UB','GHBRB','SYS_PARAM_CS','CS_MAX_AMT',null,null,'N',null,SYSDATE,null,SYSDATE,'N','Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) VALUES ('UB','GHBRB','SYS_PARAM_CS','CS_MAX_DAYAMT',null,null,'N',null,SYSDATE,null,SYSDATE,'N','Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) VALUES ('UB','GHBRB','SYS_PARAM_CS','CS_MAX_TXS',null,null,'N',null,SYSDATE,null,SYSDATE,'N','Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) VALUES ('UB','GHBRB','SYS_PARAM_CS','CS_MULTIPLE_AMT',null,null,'N',null,SYSDATE,null,SYSDATE,'N','Y');

INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) VALUES ('UB','GHBRB','SYS_PARAM_DFT','FTDFT_MAX_AMT',null,null,'N',null,null,null,SYSDATE,'N','Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) VALUES ('UB','GHBRB','SYS_PARAM_DFT','FTDFT_MAX_TXS',null,null,'N',null,null,null,SYSDATE,'N','Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) VALUES ('UB','GHBRB','SYS_PARAM_DFT','FTDFT_MIN_AMT',null,null,'N',null,null,null,SYSDATE,'N','Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) VALUES ('UB','GHBRB','SYS_PARAM_DFT','FTDFT_MAX_DAYAMT',null,null,'N',null,null,null,SYSDATE,'N','Y');

INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) VALUES ('UB','GHBRB','SYS_PARAM_FTOTH','FTOTH_MAX_AMT',null,null,'N',null,SYSDATE,null,SYSDATE,'N','Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) VALUES ('UB','GHBRB','SYS_PARAM_FTOTH','FTOTH_MAX_DAYAMT',null,null,'N',null,SYSDATE,null,SYSDATE,'N','Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) VALUES ('UB','GHBRB','SYS_PARAM_FTOTH','FTOTH_MAX_TXS',null,null,'N',null,SYSDATE,null,SYSDATE,'N','Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) VALUES ('UB','GHBRB','SYS_PARAM_FTOTH','FTOTH_MIN_AMT',null,null,'N',null,SYSDATE,null,SYSDATE,'N','Y');

INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) VALUES ('UB','GHBRB','SYS_PARAM_FTOWN','FTOWN_MAX_AMT',null,null,'N',null,null,null,SYSDATE,'N','Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) VALUES ('UB','GHBRB','SYS_PARAM_FTOWN','FTOWN_MIN_AMT',null,null,'N',null,null,null,SYSDATE,'N','Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) VALUES ('UB','GHBRB','SYS_PARAM_FTOWN','FTOWN_MAX_DAYAMT',null,null,'N',null,null,null,SYSDATE,'N','Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) VALUES ('UB','GHBRB','SYS_PARAM_FTOWN','FTOWN_MAX_TXS',null,null,'N',null,null,null,SYSDATE,'N','Y');

INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) VALUES ('UB','GHBRB','SYS_PARAM_MWALLET','MWALLET_MAX_AMT',null,null,'N',null,null,null,SYSDATE,'N','Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) VALUES ('UB','GHBRB','SYS_PARAM_MWALLET','MWALLET_MIN_AMT',null,null,'N',null,null,null,SYSDATE,'N','Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) VALUES ('UB','GHBRB','SYS_PARAM_MWALLET','MWALLET_MAX_DAYAMT',null,null,'N',null,null,null,SYSDATE,'N','Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) VALUES ('UB','GHBRB','SYS_PARAM_MWALLET','MWALLET_MAX_TXS',null,null,'N',null,null,null,SYSDATE,'N','Y');

INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) VALUES ('UB','GHBRB','SYS_PARAM_TOPUP','MIN_TOPUP_AMT',null,null,'N',null,null,null,SYSDATE,'N','Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) VALUES ('UB','GHBRB','SYS_PARAM_TOPUP','MAX_TOPUP_AMT',null,null,'N',null,null,null,SYSDATE,'N','Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) VALUES ('UB','GHBRB','SYS_PARAM_TOPUP','TOPUP_MAX_DAYAMT',null,null,'N',null,null,null,SYSDATE,'N','Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) VALUES ('UB','GHBRB','SYS_PARAM_TOPUP','TOPUP_MAX_TXS',null,null,'N',null,null,null,SYSDATE,'N','Y');

INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) VALUES ('UB','GHBRB','SYS_PARAM_CURRENT','PRODUCT_CODES',null,null,'N',null,null,null,null,'N','Y');

INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) VALUES ('UB','GHBRB','FT_DELIVERY_TYPE','BEN',null,null,'N',null,null,null,null,'N','Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) VALUES ('UB','GHBRB','FT_DELIVERY_TYPE','BRN',null,null,'N',null,null,null,null,'N','Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) VALUES ('UB','GHBRB','FT_DELIVERY_TYPE','REM',null,null,'N',null,null,null,null,'N','Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) VALUES ('UB','GHBRB','FT_DRAFT_TYPE','BD',null,null,'N',null,null,null,null,'N','Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) VALUES ('UB','GHBRB','FT_DRAFT_TYPE','MC',null,null,'N',null,null,null,null,'N','Y');

INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) VALUES ('UB','GHBRB','CMN_CHANNEL','UB','30',null,'Y',null,null,null,null,'N','Y');
INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) VALUES ('UB','GHBRB','CMN_SYSTEM','UB',null,null,'N',null,null,null,null,'N','Y');


-----------C_LISTVALUE_RES_MST-----------

INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) VALUES ('UB','GHBRB','SYS_PARAM_BNF','VIEW_MAX_BILLER_SIZE','EN','5',2);
INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) VALUES ('UB','GHBRB','SYS_PARAM_BNF','PAYEE_NICK_LENGTHMAX','EN','20',1);
INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) VALUES ('UB','GHBRB','SYS_PARAM_BNF','VIEW_MAX_BENFCR','EN','5',1);

INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) VALUES ('UB','GHBRB','SYS_PARAM_BP','POOL_AC_BILL_PAY','EN','5',5);
INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) VALUES ('UB','GHBRB','SYS_PARAM_BP','LAST_PAID_BILL_LIST','EN','5',6);
INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) VALUES ('UB','GHBRB','SYS_PARAM_BP','BILLPAY_MAX_AMT','EN','15000',1);
INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) VALUES ('UB','GHBRB','SYS_PARAM_BP','BILLPAY_MIN_AMT','EN','1',2);
INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) VALUES ('UB','GHBRB','SYS_PARAM_BP','BILLPAY_MAX_DAYAMT','EN','15000',3);
INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) VALUES ('UB','GHBRB','SYS_PARAM_BP','BILLPAY_MAX_TXS','EN','5',4);

INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) VALUES ('UB','GHBRB','SYS_PARAM_CS','CS_MAX_AMT','EN','400',1);
INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) VALUES ('UB','GHBRB','SYS_PARAM_CS','CS_MAX_DAYAMT','EN','1500',3);
INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) VALUES ('UB','GHBRB','SYS_PARAM_CS','CS_MAX_TXS','EN','3',4);
INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) VALUES ('UB','GHBRB','SYS_PARAM_CS','CS_MULTIPLE_AMT','EN','10',5);
INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) VALUES ('UB','GHBRB','SYS_PARAM_CS','CS_MIN_AMT','EN','10',2);


INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) VALUES ('UB','GHBRB','SYS_PARAM_DFT','FTDFT_MAX_AMT','EN','1500',1);
INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) VALUES ('UB','GHBRB','SYS_PARAM_DFT','FTDFT_MAX_TXS','EN','5',2);
INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) VALUES ('UB','GHBRB','SYS_PARAM_DFT','FTDFT_MIN_AMT','EN','10',3);
INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) VALUES ('UB','GHBRB','SYS_PARAM_DFT','FTDFT_MAX_DAYAMT','EN','1500',3);

INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) VALUES ('UB','GHBRB','SYS_PARAM_FTOTH','FTOTH_MAX_AMT','EN','1500',3);
INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) VALUES ('UB','GHBRB','SYS_PARAM_FTOTH','FTOTH_MAX_DAYAMT','EN','1500',3);
INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) VALUES ('UB','GHBRB','SYS_PARAM_FTOTH','FTOTH_MAX_TXS','EN','5',1);
INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) VALUES ('UB','GHBRB','SYS_PARAM_FTOTH','FTOTH_MIN_AMT','EN','1',2);

INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) VALUES ('UB','GHBRB','SYS_PARAM_FTOWN','FTOWN_MAX_AMT','EN','5000',1);
INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) VALUES ('UB','GHBRB','SYS_PARAM_FTOWN','FTOWN_MIN_AMT','EN','1',2);
INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) VALUES ('UB','GHBRB','SYS_PARAM_FTOWN','FTOWN_MAX_DAYAMT','EN','15000',3);
INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) VALUES ('UB','GHBRB','SYS_PARAM_FTOWN','FTOWN_MAX_TXS','EN','3',4);

INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) VALUES ('UB','GHBRB','SYS_PARAM_MWALLET','MWALLET_MAX_AMT','EN','1000',1);
INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) VALUES ('UB','GHBRB','SYS_PARAM_MWALLET','MWALLET_MIN_AMT','EN','1',2);
INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) VALUES ('UB','GHBRB','SYS_PARAM_MWALLET','MWALLET_MAX_DAYAMT','EN','1500',3);
INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) VALUES ('UB','GHBRB','SYS_PARAM_MWALLET','MWALLET_MAX_TXS','EN','5',4);

INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) VALUES ('UB','GHBRB','SYS_PARAM_TOPUP','MIN_TOPUP_AMT','EN','1',1);
INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) VALUES ('UB','GHBRB','SYS_PARAM_TOPUP','MAX_TOPUP_AMT','EN','300',2);
INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) VALUES ('UB','GHBRB','SYS_PARAM_TOPUP','TOPUP_MAX_DAYAMT','EN','1500',5);
INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) VALUES ('UB','GHBRB','SYS_PARAM_TOPUP','TOPUP_MAX_TXS','EN','5',6);

INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) VALUES ('UB','GHBRB','SYS_PARAM_CURRENT','PRODUCT_CODES','EN','500,501,502,528,529,530,531,532,600,614,616,617,634,635,636,638,642,644,646,647,649,652,654,656,658,673,674,682,683,685,686,688,689,696,697,698,699',1);
INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) VALUES ('UB','GHBRB','SYS_PARAM_CURRENT','PRODUCT_CODES','SW','500,501,502,528,529,530,531,532,600,614,616,617,634,635,636,638,642,644,646,647,649,652,654,656,658,673,674,682,683,685,686,688,689,696,697,698,699',1);

INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) VALUES ('UB','GHBRB','FT_DELIVERY_TYPE','REM','EN','Mail to Remitter',0);
INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) VALUES ('UB','GHBRB','FT_DELIVERY_TYPE','BEN','EN','Mail to Beneficiary',2);
INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) VALUES ('UB','GHBRB','FT_DELIVERY_TYPE','BRN','EN','Collect at Branch',4);
INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) VALUES ('UB','GHBRB','FT_DRAFT_TYPE','BD','EN','Bank Draft',1);
INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) VALUES ('UB','GHBRB','FT_DRAFT_TYPE','MC','EN','Manager''s Cheque',2);


INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) VALUES ('UB','GHBRB','CMN_CHANNEL','UB','EN','Hello Money',10);
INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) VALUES ('UB','GHBRB','CMN_SYSTEM','UB','EN','Hello Money',4);




