---------------------------------------------------- C_ENHANCED_ENTITLEMENT_MST -----------------------------------------------------

DELETE FROM C_ENHANCED_ENTITLEMENT_MST WHERE SYSTEM_ID ='MB';

INSERT INTO  C_ENHANCED_ENTITLEMENT_MST (SELECT ACTIVITY_ID,'MB',CUSTOMER_IN_CONTEXT,ACCOUNT_IN_CONTEXT,RELN_TYPE_NOTALLOWED,SELF_CHECK,STAFF_CHECK,BUSINESS_ID,CARD_HOLDER_TYPE,CALLER_TYPE,'MB',MIN_AUTH_REQUIRED,CUSTOMER_TYPE_ALLOWED  FROM C_ENHANCED_ENTITLEMENT_MST  WHERE SYSTEM_ID = 'IB' AND ROLE_CATEGORY_CD='IB');

COMMIT;