------------ C_FUNCTION_MST - BOC DB --------

	DELETE  FROM C_FUNCTION_MST  WHERE SYSTEM_ID='MB';

	INSERT INTO C_FUNCTION_MST (SELECT ACTIVITY_ID, 'MB',FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC  FROM C_FUNCTION_MST  WHERE SYSTEM_ID = 'IB');

	DELETE  FROM C_FUNCTION_MST  WHERE SYSTEM_ID='MB' AND ACTIVITY_ID='PMT_FT_MRC_PAYEE';


	INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) values ('PMT_FT_MRC_PAYEE','MB','NO_GRP','-','EX','Purchase Managers Cheque with Payee','Execute','N','N');

	DELETE  FROM C_FUNCTION_MST  WHERE SYSTEM_ID='MB' AND ACTIVITY_ID='PMT_FT_BKD_PAYEE';

	INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) values ('PMT_FT_BKD_PAYEE','MB','NO_GRP','-','EX','Purchase Managers Cheque with Payee','Execute','N','N');

	DELETE  FROM C_FUNCTION_MST  WHERE SYSTEM_ID='MB' AND ACTIVITY_ID='PMT_FT_INTL_DT_PAYEE';

	INSERT INTO C_FUNCTION_MST (ACTIVITY_ID,SYSTEM_ID,FUNCTION_ID,FUNCTION_SUB_ID,ACTION_ID,FUNCTION_DESC,ACTION_DESC,INQUIRY_FLG,IBOC) values ('PMT_FT_INTL_DT_PAYEE','MB','NO_GRP','-','EX','Fund Transfer To Domestic Non Barclays Account with Payee','Execute','N','N');


	COMMIT;
