
DELETE FROM  C_LISTVALUE_MST WHERE SYSTEM_ID='UB' AND BUSINESS_ID='TZBRB' AND GROUP_ID='SYS_PARAM_BP';
COMMIT;

Insert into C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('UB','TZBRB','SYS_PARAM_BP','BILLPAY_MAX_AMT',null,null,'N',null,null,null,null,null,'Y');

Insert into C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('UB','TZBRB','SYS_PARAM_BP','BILLPAY_MIN_AMT',null,null,'N',null,null,null,null,'N','Y');

Insert into C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('UB','TZBRB','SYS_PARAM_BP','BILLPAY_MAX_DAYAMT',null,null,'N',null,null,null,null,'N','Y');

Insert into C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('UB','TZBRB','SYS_PARAM_BP','BILLPAY_MAX_TXS',null,null,'N',null,null,null,null,'N','Y');

Insert into C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('UB','TZBRB','SYS_PARAM_BP','POOL_AC_BILL_PAY',null,null,'N',null,null,null,null,'N','Y');

Insert into C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('UB','TZBRB','SYS_PARAM_BP','LAST_PAID_BILL_LIST',null,null,'N',null,null,null,null,'N','Y');


COMMIT;
-----------------------------------------------

DELETE FROM C_LISTVALUE_RES_MST  WHERE SYSTEM_ID='UB' AND BUSINESS_ID='TZBRB' AND GROUP_ID='SYS_PARAM_BP';
COMMIT;


Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_BP','BILLPAY_MAX_AMT','EN','50000',1);

Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_BP','BILLPAY_MIN_AMT','EN','10',2);

Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_BP','BILLPAY_MAX_DAYAMT','EN','100000',3);

Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_BP','BILLPAY_MAX_TXS','EN','100',4);

Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_BP','POOL_AC_BILL_PAY','EN','5',5);

Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('UB','TZBRB','SYS_PARAM_BP','LAST_PAID_BILL_LIST','EN','10',6);

COMMIT;