
-- insert script for Cash Send table S_SYSPARAM_MST
INSERT INTO S_SYSPARAM_MST (BUSINESS_ID,SYSTEM_ID,PARAM_ID,PARAM_VALUE,PARAM_COMPONENT_KEY,ACTIVITY_ID,SYSTEM_MAINTAIN,DISP_TYPE,MODIFIED_DTM,MODIFIED_BY,AUTHORISED_BY,AUTHORISED_DTM,DELETE_FLG,PARAM_DESC,CREATED_BY,CREATED_DTM) VALUES ('UGBRB','UB','CASHSENDUSERKEY','cdfcdb630043f4058954825b1761ad1b39117c4741f11adb95bd26bd670f870d','CS_UG_PWD','COMMON','Y','INPUT_TEXT',null,null,null,null,null,'BCAG Servers end point',null,sysdate);

INSERT INTO S_SYSPARAM_MST (BUSINESS_ID,SYSTEM_ID,PARAM_ID,PARAM_VALUE,PARAM_COMPONENT_KEY,ACTIVITY_ID,SYSTEM_MAINTAIN,DISP_TYPE,MODIFIED_DTM,MODIFIED_BY,AUTHORISED_BY,AUTHORISED_DTM,DELETE_FLG,PARAM_DESC,CREATED_BY,CREATED_DTM) VALUES ('UGBRB','UB','CASHSEND_BCAG_EndPoint','35.117.48.164:5000,35.117.48.165:5000,35.117.48.166:5000,35.117.48.167:5000','THM_BCAG_EP','COMMON','Y','INPUT_TEXT',null,null,null,null,null,'BCAG Servers end point',null,sysdate);

INSERT INTO S_SYSPARAM_MST (BUSINESS_ID,SYSTEM_ID,PARAM_ID,PARAM_VALUE,PARAM_COMPONENT_KEY,ACTIVITY_ID,SYSTEM_MAINTAIN,DISP_TYPE,MODIFIED_DTM,MODIFIED_BY,AUTHORISED_BY,AUTHORISED_DTM,DELETE_FLG,PARAM_DESC,CREATED_BY,CREATED_DTM) VALUES ('UGBRB','UB','CASHSENDKEYSTORE','/sslstore.jks','BCAGFILE_NAME','COMMON','Y','INPUT_TEXT',null,null,null,null,null,'BCAG Servers end point',null,sysdate);

INSERT INTO S_SYSPARAM_MST (BUSINESS_ID,SYSTEM_ID,PARAM_ID,PARAM_VALUE,PARAM_COMPONENT_KEY,ACTIVITY_ID,SYSTEM_MAINTAIN,DISP_TYPE,MODIFIED_DTM,MODIFIED_BY,AUTHORISED_BY,AUTHORISED_DTM,DELETE_FLG,PARAM_DESC,CREATED_BY,CREATED_DTM) VALUES ('UGBRB','UB','CASHSENDKEYSTOREKEY','123456','CS_KEYSTORE_KEY','COMMON','Y','INPUT_TEXT',null,null,null,null,null,'BCAG Servers end point',null,sysdate);

INSERT INTO S_SYSPARAM_MST (BUSINESS_ID,SYSTEM_ID,PARAM_ID,PARAM_VALUE,PARAM_COMPONENT_KEY,ACTIVITY_ID,SYSTEM_MAINTAIN,DISP_TYPE,MODIFIED_DTM,MODIFIED_BY,AUTHORISED_BY,AUTHORISED_DTM,DELETE_FLG,PARAM_DESC,CREATED_BY,CREATED_DTM) VALUES ('UGBRB','UB','CASHSENDUSERNAME','5b8929589827e7d242765f36971f630d03f8122aba85ad27cf4c82f0d54ae42e','CS_UG_UN','COMMON','Y','INPUT_TEXT',null,null,null,null,null,'BCAG Servers end point',null,sysdate);

INSERT INTO S_SYSPARAM_MST (BUSINESS_ID,SYSTEM_ID,PARAM_ID,PARAM_VALUE,PARAM_COMPONENT_KEY,ACTIVITY_ID,SYSTEM_MAINTAIN,DISP_TYPE,MODIFIED_DTM,MODIFIED_BY,AUTHORISED_BY,AUTHORISED_DTM,DELETE_FLG,PARAM_DESC,CREATED_BY,CREATED_DTM) VALUES ('UGBRB','UB','CASHSENDENCRYPTLOGIC','UG_Encrypt','CS_ENCRYPTLOGIC','COMMON','Y','INPUT_TEXT',null,null,null,null,null,'BCAG Servers end point',null,sysdate);

INSERT INTO S_SYSPARAM_MST (BUSINESS_ID,SYSTEM_ID,PARAM_ID,PARAM_VALUE,PARAM_COMPONENT_KEY,ACTIVITY_ID,SYSTEM_MAINTAIN,DISP_TYPE,MODIFIED_DTM,MODIFIED_BY,AUTHORISED_BY,AUTHORISED_DTM,DELETE_FLG,PARAM_DESC,CREATED_BY,CREATED_DTM) VALUES ('UGBRB','UB','DR_CASHSEND_BCAG_EndPoint','22.124.64.46:5000,22.124.64.47:5000,22.124.64.48:5000,22.124.64.49:5000','DR_THM_BCAG_EP','COMMON','Y','INPUT_TEXT',null,null,null,null,null,'BCAG Servers end point',null,sysdate);

INSERT INTO S_SYSPARAM_MST (BUSINESS_ID,SYSTEM_ID,PARAM_ID,PARAM_VALUE,PARAM_COMPONENT_KEY,ACTIVITY_ID,SYSTEM_MAINTAIN,DISP_TYPE,MODIFIED_DTM,MODIFIED_BY,AUTHORISED_BY,AUTHORISED_DTM,DELETE_FLG,PARAM_DESC,CREATED_BY,CREATED_DTM) VALUES ('UGBRB','UB','CS_MULTIPLE_AMT','10000','CS_MULTIPLE_AMT','COMMON','N','AccType',null,null,null,null,null,null,null,null);


--Insert Script for CR35 Limited Access Feature UGBRB
INSERT INTO S_SYSPARAM_MST (BUSINESS_ID,SYSTEM_ID,PARAM_ID,PARAM_VALUE,PARAM_COMPONENT_KEY,ACTIVITY_ID,SYSTEM_MAINTAIN,DISP_TYPE,MODIFIED_DTM,MODIFIED_BY,AUTHORISED_BY,AUTHORISED_DTM,DELETE_FLG,PARAM_DESC,CREATED_BY,CREATED_DTM) VALUES ('UGBRB','UB','SRV_BillPay','N',null,'SHM_USSD_SERVICE_ENABLER','N',null,null,null,null,null,null,'Enable or disable service',null,null);

INSERT INTO S_SYSPARAM_MST (BUSINESS_ID,SYSTEM_ID,PARAM_ID,PARAM_VALUE,PARAM_COMPONENT_KEY,ACTIVITY_ID,SYSTEM_MAINTAIN,DISP_TYPE,MODIFIED_DTM,MODIFIED_BY,AUTHORISED_BY,AUTHORISED_DTM,DELETE_FLG,PARAM_DESC,CREATED_BY,CREATED_DTM) VALUES ('UGBRB','UB','SRV_OtherBarclaysAcctFundTxReg','N',null,'SHM_USSD_SERVICE_ENABLER','N',null,null,null,null,null,null,'Enable or disable service',null,null);

INSERT INTO S_SYSPARAM_MST (BUSINESS_ID,SYSTEM_ID,PARAM_ID,PARAM_VALUE,PARAM_COMPONENT_KEY,ACTIVITY_ID,SYSTEM_MAINTAIN,DISP_TYPE,MODIFIED_DTM,MODIFIED_BY,AUTHORISED_BY,AUTHORISED_DTM,DELETE_FLG,PARAM_DESC,CREATED_BY,CREATED_DTM) VALUES ('UGBRB','UB','SRV_ExtBankAcctFundTx','N',null,'SHM_USSD_SERVICE_ENABLER','N',null,null,null,null,null,null,'Enable or disable service',null,null);

INSERT INTO S_SYSPARAM_MST (BUSINESS_ID,SYSTEM_ID,PARAM_ID,PARAM_VALUE,PARAM_COMPONENT_KEY,ACTIVITY_ID,SYSTEM_MAINTAIN,DISP_TYPE,MODIFIED_DTM,MODIFIED_BY,AUTHORISED_BY,AUTHORISED_DTM,DELETE_FLG,PARAM_DESC,CREATED_BY,CREATED_DTM) VALUES ('UGBRB','UB','SRV_OtherBarcAcctDelBenef','N',null,'SHM_USSD_SERVICE_ENABLER','N',null,null,null,null,null,null,'Enable or disable service',null,null);

INSERT INTO S_SYSPARAM_MST (BUSINESS_ID,SYSTEM_ID,PARAM_ID,PARAM_VALUE,PARAM_COMPONENT_KEY,ACTIVITY_ID,SYSTEM_MAINTAIN,DISP_TYPE,MODIFIED_DTM,MODIFIED_BY,AUTHORISED_BY,AUTHORISED_DTM,DELETE_FLG,PARAM_DESC,CREATED_BY,CREATED_DTM) VALUES ('UGBRB','UB','SRV_NonBarcAcctDelBenef','N',null,'SHM_USSD_SERVICE_ENABLER','N',null,null,null,null,null,null,'Enable or disable service',null,null);

INSERT INTO S_SYSPARAM_MST (BUSINESS_ID,SYSTEM_ID,PARAM_ID,PARAM_VALUE,PARAM_COMPONENT_KEY,ACTIVITY_ID,SYSTEM_MAINTAIN,DISP_TYPE,MODIFIED_DTM,MODIFIED_BY,AUTHORISED_BY,AUTHORISED_DTM,DELETE_FLG,PARAM_DESC,CREATED_BY,CREATED_DTM) VALUES ('UGBRB','UB','SRV_RegisterBarclaysBenf','N',null,'SHM_USSD_SERVICE_ENABLER','N',null,null,null,null,null,null,'Enable or disable service',null,null);

INSERT INTO S_SYSPARAM_MST (BUSINESS_ID,SYSTEM_ID,PARAM_ID,PARAM_VALUE,PARAM_COMPONENT_KEY,ACTIVITY_ID,SYSTEM_MAINTAIN,DISP_TYPE,MODIFIED_DTM,MODIFIED_BY,AUTHORISED_BY,AUTHORISED_DTM,DELETE_FLG,PARAM_DESC,CREATED_BY,CREATED_DTM) VALUES ('UGBRB','UB','SRV_RegisterOtherBankBenf','N',null,'SHM_USSD_SERVICE_ENABLER','N',null,null,null,null,null,null,'Enable or disable service',null,null);

INSERT INTO S_SYSPARAM_MST (BUSINESS_ID,SYSTEM_ID,PARAM_ID,PARAM_VALUE,PARAM_COMPONENT_KEY,ACTIVITY_ID,SYSTEM_MAINTAIN,DISP_TYPE,MODIFIED_DTM,MODIFIED_BY,AUTHORISED_BY,AUTHORISED_DTM,DELETE_FLG,PARAM_DESC,CREATED_BY,CREATED_DTM) VALUES ('UGBRB','UB','SRV_RegisterBillers','N',null,'SHM_USSD_SERVICE_ENABLER','N',null,null,null,null,null,null,'Enable or disable service',null,null);

INSERT INTO S_SYSPARAM_MST (BUSINESS_ID,SYSTEM_ID,PARAM_ID,PARAM_VALUE,PARAM_COMPONENT_KEY,ACTIVITY_ID,SYSTEM_MAINTAIN,DISP_TYPE,MODIFIED_DTM,MODIFIED_BY,AUTHORISED_BY,AUTHORISED_DTM,DELETE_FLG,PARAM_DESC,CREATED_BY,CREATED_DTM) VALUES ('UGBRB','UB','SRV_DeleteBillers','N',null,'SHM_USSD_SERVICE_ENABLER','N',null,null,null,null,null,null,'Enable or disable service',null,null);

INSERT INTO S_SYSPARAM_MST (BUSINESS_ID,SYSTEM_ID,PARAM_ID,PARAM_VALUE,PARAM_COMPONENT_KEY,ACTIVITY_ID,SYSTEM_MAINTAIN,DISP_TYPE,MODIFIED_DTM,MODIFIED_BY,AUTHORISED_BY,AUTHORISED_DTM,DELETE_FLG,PARAM_DESC,CREATED_BY,CREATED_DTM) VALUES ('UGBRB','UB','SRV_OtherBarclaysAcctFundTxUnReg','N',null,'SHM_USSD_SERVICE_ENABLER','N',null,null,null,null,null,null,'Enable or disable service',null,null);

INSERT INTO S_SYSPARAM_MST (BUSINESS_ID,SYSTEM_ID,PARAM_ID,PARAM_VALUE,PARAM_COMPONENT_KEY,ACTIVITY_ID,SYSTEM_MAINTAIN,DISP_TYPE,MODIFIED_DTM,MODIFIED_BY,AUTHORISED_BY,AUTHORISED_DTM,DELETE_FLG,PARAM_DESC,CREATED_BY,CREATED_DTM) VALUES ('UGBRB','UB','SRV_OneTimePayments','N',null,'SHM_USSD_SERVICE_ENABLER','N',null,null,null,null,null,null,'Enable or disable service',null,null);

INSERT INTO S_SYSPARAM_MST (BUSINESS_ID,SYSTEM_ID,PARAM_ID,PARAM_VALUE,PARAM_COMPONENT_KEY,ACTIVITY_ID,SYSTEM_MAINTAIN,DISP_TYPE,MODIFIED_DTM,MODIFIED_BY,AUTHORISED_BY,AUTHORISED_DTM,DELETE_FLG,PARAM_DESC,CREATED_BY,CREATED_DTM) VALUES ('UGBRB','UB','SRV_ApplyFd','N',null,'SHM_USSD_SERVICE_ENABLER','N',null,null,null,null,null,null,'Enable or disable service',null,null);

INSERT INTO S_SYSPARAM_MST (BUSINESS_ID,SYSTEM_ID,PARAM_ID,PARAM_VALUE,PARAM_COMPONENT_KEY,ACTIVITY_ID,SYSTEM_MAINTAIN,DISP_TYPE,MODIFIED_DTM,MODIFIED_BY,AUTHORISED_BY,AUTHORISED_DTM,DELETE_FLG,PARAM_DESC,CREATED_BY,CREATED_DTM) VALUES ('UGBRB','UB','SRV_MobileWalletTopUp','N',null,'SHM_USSD_SERVICE_ENABLER','N',null,null,null,null,null,null,'Enable or disable service',null,null);

INSERT INTO S_SYSPARAM_MST (BUSINESS_ID,SYSTEM_ID,PARAM_ID,PARAM_VALUE,PARAM_COMPONENT_KEY,ACTIVITY_ID,SYSTEM_MAINTAIN,DISP_TYPE,MODIFIED_DTM,MODIFIED_BY,AUTHORISED_BY,AUTHORISED_DTM,DELETE_FLG,PARAM_DESC,CREATED_BY,CREATED_DTM) VALUES ('UGBRB','UB','SRV_CashSendOneTimePayment','N',null,'SHM_USSD_SERVICE_ENABLER','N',null,null,null,null,null,null,'Enable or disable service',null,null);

INSERT INTO S_SYSPARAM_MST (BUSINESS_ID,SYSTEM_ID,PARAM_ID,PARAM_VALUE,PARAM_COMPONENT_KEY,ACTIVITY_ID,SYSTEM_MAINTAIN,DISP_TYPE,MODIFIED_DTM,MODIFIED_BY,AUTHORISED_BY,AUTHORISED_DTM,DELETE_FLG,PARAM_DESC,CREATED_BY,CREATED_DTM) VALUES ('UGBRB','UB','SRV_EditBenefInternal','N',null,'SHM_USSD_SERVICE_ENABLER','N',null,null,null,null,null,null,'Enable or disable service',null,null);

INSERT INTO S_SYSPARAM_MST (BUSINESS_ID,SYSTEM_ID,PARAM_ID,PARAM_VALUE,PARAM_COMPONENT_KEY,ACTIVITY_ID,SYSTEM_MAINTAIN,DISP_TYPE,MODIFIED_DTM,MODIFIED_BY,AUTHORISED_BY,AUTHORISED_DTM,DELETE_FLG,PARAM_DESC,CREATED_BY,CREATED_DTM) VALUES ('UGBRB','UB','SRV_EditBenefExternal','N',null,'SHM_USSD_SERVICE_ENABLER','N',null,null,null,null,null,null,'Enable or disable service',null,null);

--End point interface for Debit Card List Service CR35 UGBRB

INSERT INTO S_SYSPARAM_MST (BUSINESS_ID,SYSTEM_ID,PARAM_ID,PARAM_VALUE,PARAM_COMPONENT_KEY,ACTIVITY_ID,SYSTEM_MAINTAIN,DISP_TYPE,MODIFIED_DTM,MODIFIED_BY,AUTHORISED_BY,AUTHORISED_DTM,DELETE_FLG,PARAM_DESC,CREATED_BY,CREATED_DTM)
VALUES('UGBRB','UB','FinancialTransactionCardManagment_EndPoint','https://35.98.147.70:443/tcvm','Indi_Cust_Mgmt_EP','COMMON','Y','INPUT_TEXT',null,null,null,null,null,'MW service end point',null,null);

INSERT INTO S_SYSPARAM_MST (BUSINESS_ID,SYSTEM_ID,PARAM_ID,PARAM_VALUE,PARAM_COMPONENT_KEY,ACTIVITY_ID,SYSTEM_MAINTAIN,DISP_TYPE,MODIFIED_DTM,MODIFIED_BY,AUTHORISED_BY,AUTHORISED_DTM,DELETE_FLG,PARAM_DESC,CREATED_BY,CREATED_DTM)
VALUES('UGBRB','UB','DR_FinancialTransactionCardManagment_EndPoint','https://22.126.64.153:443/tcvm','Indi_Cust_Mgmt_EP','COMMON','Y','INPUT_TEXT',null,null,null,null,null,'MW service end point',null,null);
