---------------- C_LISTVALUE_MST ----------

	DELETE  FROM C_LISTVALUE_MST where BUSINESS_ID='KEBRB' and SYSTEM_ID='MB';

	INSERT INTO  C_LISTVALUE_MST (SELECT 'MB',BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG, EDITABLE_FLG  FROM C_LISTVALUE_MST  WHERE SYSTEM_ID = 'IB'  AND  BUSINESS_ID='KEBRB');

---------------- C_LISTVALUE_RES_MST ----------

	DELETE  FROM C_LISTVALUE_RES_MST where BUSINESS_ID='KEBRB' and SYSTEM_ID='MB';

	INSERT INTO  C_LISTVALUE_RES_MST (SELECT 'MB',BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER  FROM C_LISTVALUE_RES_MST  WHERE SYSTEM_ID = 'IB'  AND  BUSINESS_ID='KEBRB');

--------------- INSERTING into C_LISTVALUE_MST - for 'FT_DELIVERY_TYPE'
	DELETE FROM C_LISTVALUE_MST where SYSTEM_ID='MB' and GROUP_ID='FT_DELIVERY_TYPE'  AND BUSINESS_ID='KEBRB';

	INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('MB','KEBRB','FT_DELIVERY_TYPE','BEN',null,null,'N',null,null,null,null,'N','Y');
	INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('MB','KEBRB','FT_DELIVERY_TYPE','BRN',null,null,'N',null,null,null,null,'N','Y');
	INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('MB','KEBRB','FT_DELIVERY_TYPE','REM',null,null,'N',null,null,null,null,'N','Y');


-------------- INSERTING into C_LISTVALUE_RES_MST - for 'FT_DELIVERY_TYPE'
	DELETE FROM C_LISTVALUE_RES_MST where SYSTEM_ID='MB' and GROUP_ID='FT_DELIVERY_TYPE' AND BUSINESS_ID='KEBRB';

	INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('MB','KEBRB','FT_DELIVERY_TYPE','REM','EN','Mail to Remitter',0);
	INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('MB','KEBRB','FT_DELIVERY_TYPE','BEN','EN','Mail to Beneficiary',2);
	INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('MB','KEBRB','FT_DELIVERY_TYPE','BRN','EN','Collect at Branch',4);

-------------- INSERTING into C_LISTVALUE_MST - for 'FT_DRAFT_TYPE'
	DELETE FROM C_LISTVALUE_MST where SYSTEM_ID='MB' and GROUP_ID='FT_DRAFT_TYPE'  AND BUSINESS_ID='KEBRB';

	INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('MB','KEBRB','FT_DRAFT_TYPE','BD',null,null,'N',null,null,null,null,'N','Y');
	INSERT INTO C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('MB','KEBRB','FT_DRAFT_TYPE','MC',null,null,'N',null,null,null,null,'N','Y');

-------------- INSERTING into C_LISTVALUE_RES_MST - for 'FT_DRAFT_TYPE'
	DELETE FROM C_LISTVALUE_RES_MST where SYSTEM_ID='MB' and GROUP_ID='FT_DRAFT_TYPE'  AND BUSINESS_ID='KEBRB';

	INSERT INTO	C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('MB','KEBRB','FT_DRAFT_TYPE','BD','EN','Bank Draft',1);
	INSERT INTO C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('MB','KEBRB','FT_DRAFT_TYPE','MC','EN','Manager''s Cheque',2);

	-DELETE FROM C_LISTVALUE_MST WHERE BUSINESS_ID='KEBRB' AND GROUP_ID='FT_FACADE_DEST' AND SYSTEM_ID='MB';

	-INSERT INTO  C_LISTVALUE_MST (SELECT 'MB',BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG, EDITABLE_FLG  FROM C_LISTVALUE_MST  WHERE SYSTEM_ID = 'IB'  AND  BUSINESS_ID='KEBRB' AND GROUP_ID='FT_FACADE_DEST');

	-DELETE FROM C_LISTVALUE_RES_MST WHERE BUSINESS_ID='KEBRB' AND GROUP_ID='FT_FACADE_DEST' AND SYSTEM_ID='MB';

	-INSERT INTO  C_LISTVALUE_RES_MST (SELECT 'MB',BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER  FROM C_LISTVALUE_RES_MST  WHERE SYSTEM_ID = 'IB'  AND  BUSINESS_ID='KEBRB' AND GROUP_ID='FT_FACADE_DEST');


---------------- C_LISTVALUE_MST ----------FT_INTL_PMT_REASON ----

	DELETE  FROM C_LISTVALUE_MST where BUSINESS_ID='KEBRB' and SYSTEM_ID='MB' AND GROUP_ID='FT_INTL_PMT_REASON';

	INSERT INTO  C_LISTVALUE_MST (SELECT 'MB',BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG, EDITABLE_FLG  FROM C_LISTVALUE_MST  WHERE SYSTEM_ID = 'IB'  AND  BUSINESS_ID='KEBRB' AND GROUP_ID='FT_INTL_PMT_REASON');

---------------- C_LISTVALUE_RES_MST ----------FT_INTL_PMT_REASON ----

	DELETE  FROM C_LISTVALUE_RES_MST where BUSINESS_ID='KEBRB' and SYSTEM_ID='MB' AND GROUP_ID='FT_INTL_PMT_REASON';

	INSERT INTO  C_LISTVALUE_RES_MST (SELECT 'MB',BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER  FROM C_LISTVALUE_RES_MST  WHERE SYSTEM_ID = 'IB'  AND  BUSINESS_ID='KEBRB' AND GROUP_ID='FT_INTL_PMT_REASON');


---------------- C_LISTVALUE_MST ----------FT_INTL_PMT_DETAILS----
	DELETE  FROM C_LISTVALUE_MST where BUSINESS_ID='KEBRB' and SYSTEM_ID='MB' AND GROUP_ID='FT_INTL_PMT_DETAILS';

	INSERT INTO  C_LISTVALUE_MST (SELECT 'MB',BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG, EDITABLE_FLG  FROM C_LISTVALUE_MST  WHERE SYSTEM_ID = 'IB'  AND  BUSINESS_ID='KEBRB' AND GROUP_ID='FT_INTL_PMT_DETAILS');

---------------- C_LISTVALUE_RES_MST ----------FT_INTL_PMT_DETAILS----
	DELETE  FROM C_LISTVALUE_RES_MST where BUSINESS_ID='KEBRB' and SYSTEM_ID='MB' AND GROUP_ID='FT_INTL_PMT_DETAILS';

	INSERT INTO  C_LISTVALUE_RES_MST (SELECT 'MB',BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER  FROM C_LISTVALUE_RES_MST  WHERE SYSTEM_ID = 'IB'  AND  BUSINESS_ID='KEBRB' AND GROUP_ID='FT_INTL_PMT_DETAILS');

---------------- C_LISTVALUE_RES_MST ----------CURR_SUPPORT_OWN_ACC----
	DELETE FROM C_LISTVALUE_MST where BUSINESS_ID='KEBRB' and SYSTEM_ID='MB' AND GROUP_ID='CURR_SUPPORT_OWN_ACC';

	Insert into C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('MB','KEBRB','CURR_SUPPORT_OWN_ACC','FCYFCY',null,null,'N',null,null,null,null,'N','Y');
	Insert into C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('MB','KEBRB','CURR_SUPPORT_OWN_ACC','LCYFCY',null,null,'N',null,null,null,null,'N','Y');
	Insert into C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('MB','KEBRB','CURR_SUPPORT_OWN_ACC','FCYLCY',null,null,'N',null,null,null,null,'N','Y');
	Insert into C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('MB','KEBRB','CURR_SUPPORT_OWN_ACC','FCY1FCY2',null,null,'N',null,null,null,null,'N','Y');
	Insert into C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('MB','KEBRB','CURR_SUPPORT_OWN_ACC','LCYLCY',null,null,'N',null,null,null,null,'N','Y');

---------------- C_LISTVALUE_RES_MST ----------CURR_SUPPORT_OWN_ACC----
	DELETE FROM C_LISTVALUE_RES_MST where BUSINESS_ID='KEBRB' and SYSTEM_ID='MB' AND GROUP_ID='CURR_SUPPORT_OWN_ACC';

	Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('MB','KEBRB','CURR_SUPPORT_OWN_ACC','LCYLCY','EN','Y',1);
	Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('MB','KEBRB','CURR_SUPPORT_OWN_ACC','FCYFCY','EN','Y',2);
	Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('MB','KEBRB','CURR_SUPPORT_OWN_ACC','LCYFCY','EN','Y',3);
	Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('MB','KEBRB','CURR_SUPPORT_OWN_ACC','FCYLCY','EN','Y',4);
	Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('MB','KEBRB','CURR_SUPPORT_OWN_ACC','FCY1FCY2','EN','N',5);

---------------- C_LISTVALUE_RES_MST ----------CURR_SUPPORT_INT_ACC----
	DELETE FROM C_LISTVALUE_MST where BUSINESS_ID='KEBRB' and SYSTEM_ID='MB' AND GROUP_ID='CURR_SUPPORT_INT_ACC';

	Insert into C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('MB','KEBRB','CURR_SUPPORT_INT_ACC','FCY1FCY2',null,null,'N',null,null,null,null,'N','Y');
	Insert into C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('MB','KEBRB','CURR_SUPPORT_INT_ACC','FCYFCY',null,null,'N',null,null,null,null,'N','Y');
	Insert into C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('MB','KEBRB','CURR_SUPPORT_INT_ACC','FCYLCY',null,null,'N',null,null,null,null,'N','Y');
	Insert into C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('MB','KEBRB','CURR_SUPPORT_INT_ACC','LCYFCY',null,null,'N',null,null,null,null,'N','Y');
	Insert into C_LISTVALUE_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,FILTER_KEY_1,FILTER_KEY_2,DEFAULT_FLG,MODIFIED_BY,MODIFIED_DTM,AUTHORIZED_BY,AUTHORIZED_DTM,DELETE_FLG,EDITABLE_FLG) values ('MB','KEBRB','CURR_SUPPORT_INT_ACC','LCYLCY',null,null,'N',null,null,null,null,'N','Y');

---------------- C_LISTVALUE_RES_MST ----------CURR_SUPPORT_INT_ACC----
	DELETE FROM C_LISTVALUE_RES_MST where BUSINESS_ID='KEBRB' and SYSTEM_ID='MB' AND GROUP_ID='CURR_SUPPORT_INT_ACC';

	Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('MB','KEBRB','CURR_SUPPORT_INT_ACC','FCY1FCY2','EN','N',5);
	Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('MB','KEBRB','CURR_SUPPORT_INT_ACC','FCYFCY','EN','Y',2);
	Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('MB','KEBRB','CURR_SUPPORT_INT_ACC','FCYLCY','EN','Y',4);
	Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('MB','KEBRB','CURR_SUPPORT_INT_ACC','LCYFCY','EN','Y',3);
	Insert into C_LISTVALUE_RES_MST (SYSTEM_ID,BUSINESS_ID,GROUP_ID,LIST_VALUE_KEY,LANGUAGE_ID,VALUE,LIST_VALUE_ORDER) values ('MB','KEBRB','CURR_SUPPORT_INT_ACC','LCYLCY','EN','Y',1);


COMMIT;