------------ C_FUNCTION_MST --------
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_FX_RATE' AND SYSTEM_ID='UB';
--Edit Beneficiary
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_PAYEE_UPD_EXTERNAL' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_PAYEE_UPD_INTERNAL' AND SYSTEM_ID='UB';
--Credit Card
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='ACT_CCD_UNBILLED_TRANS' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='ACT_CCD_STATEMENT_TRANS' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='ACT_CREDIT_CARD_DETAIL' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_FT_CARD_PAYMENT_ONETIME' AND SYSTEM_ID='UB';
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_FT_CARD_PAYMENT_OWN' AND SYSTEM_ID='UB';
--Cash send
DELETE  FROM C_FUNCTION_MST  WHERE ACTIVITY_ID='PMT_CS' AND SYSTEM_ID='UB';
commit;