CREATE OR REPLACE SYNONYM C_INTEREST_RATE_MST_ADMDB FOR C_INTEREST_RATE_MST@SHM_BOC_LINK;
CREATE OR REPLACE SYNONYM C_COMPONENT_MST_ADMDB FOR C_COMPONENT_MST@SHM_BOC_LINK;
CREATE OR REPLACE SYNONYM C_COMPONENT_RES_MST_ADMDB FOR C_COMPONENT_RES_MST@SHM_BOC_LINK;
CREATE OR REPLACE SYNONYM C_FORMATTER_MST_ADMDB FOR C_FORMATTER_MST@SHM_BOC_LINK;
CREATE OR REPLACE SYNONYM C_BUSINESS_MST_ADMDB FOR C_BUSINESS_MST@SHM_BOC_LINK;

CREATE OR REPLACE SYNONYM C_PRODUCT_MST_ADMDB FOR C_PRODUCT_MST@SHM_BOC_LINK;
CREATE OR REPLACE SYNONYM C_LISTVALUE_MST_ADMDB FOR C_LISTVALUE_MST@SHM_BOC_LINK;
CREATE OR REPLACE SYNONYM C_LISTVALUE_RES_MST_ADMDB FOR C_LISTVALUE_RES_MST@SHM_BOC_LINK;

CREATE OR REPLACE SYNONYM C_MESSAGE_MST_ADMDB FOR C_MESSAGE_MST@SHM_BOC_LINK;

CREATE OR REPLACE SYNONYM C_MESSAGE_RES_MST_ADMDB FOR C_MESSAGE_RES_MST@SHM_BOC_LINK;

COMMIT;
