
-- Need to execute in SSASHMA schema
 
GRANT SELECT ON C_BANKROUTING_MST to SSASHMR;

GRANT SELECT ON C_BILLER_MST to SSASHMR;

GRANT SELECT ON C_BUSINESS_MST to SSASHMR;

GRANT SELECT ON C_COMPONENT_MST to SSASHMR;

GRANT SELECT ON C_COMPONENT_RES_MST to SSASHMR;

GRANT SELECT ON C_FORMATTER_MST to SSASHMR;

GRANT SELECT ON C_INTEREST_RATE_MST to SSASHMR;

GRANT SELECT ON C_LISTVALUE_MST to SSASHMR;

GRANT SELECT ON C_LISTVALUE_RES_MST to SSASHMR;

GRANT SELECT ON C_MESSAGE_MST to SSASHMR;

GRANT SELECT ON C_MESSAGE_RES_MST to SSASHMR;

GRANT SELECT ON C_PRODUCT_MST to SSASHMR;

GRANT SELECT ON S_FUNCTION_CONFIG to SSASHMR;

GRANT SELECT ON S_LIMIT_CUST_TOTAL to SSASHMR;

GRANT SELECT ON S_SES_SUMMARY_HST to SSASHMR;

GRANT SELECT ON S_SYSPARAM_MST to SSASHMR;

GRANT SELECT ON S_TXN_CUT_OFF_MST to SSASHMR;

GRANT SELECT ON S_URL_BUSINESS_MAP_MST to SSASHMR;