
-- Need to execute in SSASHMA schema
 
GRANT SELECT, INSERT, UPDATE, DELETE ON C_BANKROUTING_MST to SSASHMU;

GRANT SELECT, INSERT, UPDATE, DELETE ON C_BILLER_MST to SSASHMU;

GRANT SELECT, INSERT, UPDATE, DELETE ON C_BUSINESS_MST to SSASHMU;

GRANT SELECT, INSERT, UPDATE, DELETE ON C_COMPONENT_MST to SSASHMU;

GRANT SELECT, INSERT, UPDATE, DELETE ON C_COMPONENT_RES_MST to SSASHMU;

GRANT SELECT, INSERT, UPDATE, DELETE ON C_FORMATTER_MST to SSASHMU;

GRANT SELECT, INSERT, UPDATE, DELETE ON C_INTEREST_RATE_MST to SSASHMU;

GRANT SELECT, INSERT, UPDATE, DELETE ON C_LISTVALUE_MST to SSASHMU;

GRANT SELECT, INSERT, UPDATE, DELETE ON C_LISTVALUE_RES_MST to SSASHMU;

GRANT SELECT, INSERT, UPDATE, DELETE ON C_MESSAGE_MST to SSASHMU;

GRANT SELECT, INSERT, UPDATE, DELETE ON C_MESSAGE_RES_MST to SSASHMU;

GRANT SELECT, INSERT, UPDATE, DELETE ON C_PRODUCT_MST to SSASHMU;

GRANT SELECT, INSERT, UPDATE, DELETE ON S_FUNCTION_CONFIG to SSASHMU;

GRANT SELECT, INSERT, UPDATE, DELETE ON S_LIMIT_CUST_TOTAL to SSASHMU;

GRANT SELECT, INSERT, UPDATE, DELETE ON S_SES_SUMMARY_HST to SSASHMU;

GRANT SELECT, INSERT, UPDATE, DELETE ON S_SYSPARAM_MST to SSASHMU;

GRANT SELECT, INSERT, UPDATE, DELETE ON S_TXN_CUT_OFF_MST to SSASHMU;

GRANT SELECT, INSERT, UPDATE, DELETE ON S_URL_BUSINESS_MAP_MST to SSASHMU;